### ISSUE TITLE
Bug permessi scrittura permessi messaggi multipli

### ISSUE THREAD

**Issue by Dyrr** [GDRCD/GDRCD#105]
I livelli dei permessi del pg per la scrittura dei messaggi a destinatari multipli come ai presenti e a tutti gli utenti sono controllati solo nella parte della pagina che genera il form per inserirli, ma  non nella parte di pagina che esegue l'inserimento per cui manipolando i campi del form anche con un qualsiasi strumento interno al browser che permette di modificare l'html è possibile mandare i messaggi a tutti i presenti e a tutta la land senza i permessi. Bug testato sul 5.4 e con quasi tutta certezza presente anche nelle altre versioni

**Comment by ste-camp** [comment]
Si xD è un buco di sicurezza che risale alla prima versione di gdrcd5.
L'ho notato da un po'.... Non l'ho mai chiuso perché quella pagina in realtà sarebbe da riscrivere totalmente :/

**Comment by breakeryouko** [comment]
risolto
