### ISSUE TITLE
Bug (?) oggetti in chat

### ISSUE THREAD

**Issue by jennycolvin** [GDRCD/GDRCD#106]
Premetto che ho toccato il ref_header.php, (per inserire una nuova tipologia di azione, categorizzata come F) ed il frame_chat.php, (modifiche di tipo stilistico, niente che toccasse il codice vero e proprio), ma quando tento di utilizzare un oggetto in chat, non compare alcuna scritta che ne indichi l'uso.

Se poteste darmi qualche dritta su come risolvere, ve ne sarei grata.

**Comment by breakeryouko** [comment]
chiudo per inattività.
