### ISSUE TITLE
Chat avatar in presenti estesi

### ISSUE THREAD

**Issue by Sigridhr** [GDRCD/GDRCD#107]
Premettendo che non sono un programmatore, sto lavorando con la versione 5.4 e volevo inserire l'avatar pg della chat nei presenti estesi, come avevo fatto nel 5.2, ma mi compare solo un quadrato trasparente della misura corrispondente.
Ho inserito il codice che avevo appunto già utilizzato, ovvero questo:
`{
//Altrimenti e´ semplicemente loggato
  $record[´url_img_chat´] = trim(gdrcd_filter(´in´,$record[´url_img_chat´]));
  echo ´<img class="img_chat_avatar" src="´.$record[´url_img_chat´].´" class="chat_avatar" style="width:´.$PARAMETERS[´settings´][´chat_avatar´][´width´].´px; height:´.$PARAMETERS[´settings´][´chat_avatar´][´height´].´px;" />´;
  echo ´<img class="presenti_ico" src="imgs/icons/blank.png" alt="´.gdrcd_filter(´out´,$MESSAGE[´status_pg´][´logged´]).´" title="´.gdrcd_filter(´out´,$MESSAGE[´status_pg´][´logged´]).´" />´;
}`
Sapreste darmi per favore un qualche aiuto?
Grazie.

**Comment by ste-camp** [comment]
La risposta ti è già stata data nel thread che hai postato su gdr-online (quello è il posto migliore dove fare queste domande, non qui).
http://www.gdr-online.com/readforum.asp?id=208648

Non puoi usare un dato se prima non lo recuperi. Devi aggiungere l'immagine di chat alla query che ritrova i dati.
