### ISSUE TITLE
Bug in iscrizione

### ISSUE THREAD

**Issue by cindy1979** [GDRCD/GDRCD#108]
Oggi e venuto fuori un nuovo diciamo bug nella fase di registrazione di un nuovo pg, un tipo si e iscritto inserendo nel nome del pg le " " faccio un esempio Tizzio "b.e" non so come ci sia riuscito ma quando andiamo a cliccare sul nome del pg ci appare la scritta "Non è stato specificato il none del PG oppure il PG non esiste.", il sistema non blocca l'uso di determinati caratteri speciali come sopra.

**Comment by ste-camp** [comment]
Si, il problema è che sono stati rimossi i controlli sui caratteri dei nomi dei pg. Il che non sarebbe un gran problema se tutto il resto del codice fosse scritto decentemente XD
In molte sezioni che ho modificato io ho corretto questo comportamento, ma purtroppo non succede ovunque

**Comment by cindy1979** [comment]
in che modo posso risolvere il problema???

**Comment by ste-camp** [comment]
Puoi aggiungere un controllo alla registrazione sul nome del pg, assicurandoti che abbia solo lettere.
una cosa tipo
```php
if(preg_match("/^[a-z]+$/si", $nome)==0){
  //ERRORE
}
```

**Comment by Dyrr** [comment]
Io proporrei un:
```php
    $regex = '#[^\p{L}\s]#u';

    if (preg_match($regex,$_POST['nome'])) {
        //ERRORE			
    }
```
per il significato della regex   
```
 [^\p{L}\s] match a single character not present in the list below
        \p{L} matches any kind of letter from any language
        \s match any kind of invisible character [\p{Z}\h\v]
    u modifier: unicode: Pattern strings are treated as UTF-16. Also causes escape sequences to match unicode characters
```
