### ISSUE TITLE
Nazionalità/Razza

### ISSUE THREAD

**Issue by lferraro82** [GDRCD/GDRCD#111]
Salve,non so neanche se è corretto chiedere qui,quindi mi scuso se sono fuori luogo.
Volevo sapere se in gdrcd 5.4 , non sia presente la possiblità di scelta nell'uso o della razza o della nazionalità,o in caso,se si ha intenzione di integrarla per il futuro?

Grazie

**Comment by ste-camp** [comment]
Ciao,
non sono sicuro di cosa intendi.
L'uso contemporaneo di Razza e Nazionalità non c'è, anche se su gdr-online.com puoi trovare una patch per aggiungere la nazionalità.
Se invece nel tuo gdr vuoi usare solo le razze o solo le nazionalità non c'è problema, perchè la funzionalità di razza che è attualmente implementata in gdrcd può facilmente essere rinominata per far venire fuori "nazionalità", basta andare a cambiare le definizioni nel file config e nel vocabulary
