### ISSUE TITLE
PHP5.4

### ISSUE THREAD

**Issue by ste-camp** [GDRCD/GDRCD#112]
Potrebbe essere una buona idea ritornare a supportare PHP 5.3 (? credo), dato che comunque i cambiamenti sarebbero minimi:
[*] usare

``` php
dirname(__FILE__)
```

invece che 

``` php
__DIR__
```

[*] usare array() invece che []

**Comment by Dyrr** [comment]
__DIRR__ non è 5.3?

5.3.0 	Added __DIR__ and __NAMESPACE__ constants

[http://php.net/manual/en/language.constants.predefined.php](http://php.net/manual/en/language.constants.predefined.php)

per quanto riguarda l'array, visto che di default alla fine è un array vuoto, non converrebbe passare come valore di default, null e se non è gia stato fatto commentare decentemente la funzione segnando che va passato come parametro un array?
