### ISSUE TITLE
gdrcd_query transaction

### ISSUE THREAD

**Issue by LucaMarzialetti** [GDRCD/GDRCD#113]
Ciao,
sto cercando di restare fedele alla struttura di query e filtri usata dal framework.
Mi sono accorto però che non c'è la possibilità di predisporre transazioni SQL in maniera semplice.
Nel caso specifico sarebbe utile averle nel momento che si utilizzano insert su tabelle con autoincrement per poter chiedere con gdrcd_query('','last_it') l'id generato.
Se questo non avviene in una transazione, è evidente che non è garantita l'assenza dei fenomeni di interferenza dati dalla concorrenza.

Esempio:
```
gdrcd_query("INSERT.... VALUES()...");
<----possibile altro insert su db da altro thread?
$id = gdrcd_query(''.'last_id');

```
Se ho compreso bene il codice, credo che non ci siano gli estremi per garantire che la lettura non sia una lettura sporca. A livello di DB SQL servirebbe proteggere i due statement da un BEGIN ed un COMMIT;

Possibile soluzione macchinosa:

```
gdrcd_query("BEGIN");
gdrcd_query("INSERT.... VALUES()...");
$id = gdrcd_query(''.'last_id');
gdrcd_query("COMMIT");

```

Che dite, si può fare di meglio? :) 
Un saluto,
Luca

**Comment by ste-camp** [comment]
Ciao Luca,
ti rispondo in due parti:
1. Hai assolutamente ragione nel dire che il supporto alle transazioni manca. L'astrazione per il database è effettivamente parecchio vecchia, come un po' tutto il software di GDRCD. Attualmente non abbiamo molta intenzione però di introdurre nuovi sviluppi, prevalentemente proprio perchè l'architettura del framework è fatta male e ci ritroviamo costantemente a dover mettere più delle pezze che dei veri miglioramenti.

2. Sbagli però a identificare il caso d'uso delle transazioni, credo a causa di una comprensione sbagliata di come funziona PHP e il suo collegamento con il database: partiamo dal fatto che le richieste di tipo 'last_id' o 'affected_rows' non vanno a eseguire nessuna operazione sul database, al contrario questi dati sono già resi disponibili al termine di ogni query in un'area di memoria riservata al risultato della query. Nel momento in cui tu fai la richiesta semplicemente vai a leggere quell'area di memoria che contiene i dati calcolati al termine della query, non sono quindi minimamente toccati da eventuali altre richieste al DB da parte di altri processi (quindi non ti servono le transazioni).

Studiando l'architettura di ServerWeb+PHP+DB puoi capire che la maggior parte dei problemi di programmazione parallela non toccano minimamente PHP (che infatti non ha praticamente nessuno strumento per la programmazione parallela), perchè il serverWeb e il database gestiscono tutto il parallelismo e PHP non ha visibilità al di fuori della singola richiesta HTTP. In questo modo la necessità di avere il supporto alle transazioni si riduce drasticamente a pochi casi specifici (in pratica quasi solo le occasioni in cui viene cancellato un record e bisogna cancellare anche tutti i dati sulle tabelle collegate).

**Comment by LucaMarzialetti** [comment]
Ciao @ste-camp,
ti ringrazio della risposta e dell'eccellente delucidazione, hai ragione, sono totalmente all'oscuro di come funziona l'interazione php - mysql_db. Mi sono limitato al conoscere lo stretto necessario per l'utilizzo, e pensavo che la questione delle transazioni restasse la medesima solfa come in tutti i sistemi SQL, quindi anche per il connettore db del framework gdrcd.
Dunque se ho capito bene le funzioni messe a disposizione da gdrcd_query quali "num_rows" e "last_id", e quindi dal funzionamento di php stesso, lavorano su dati già disponibili e per questo sono da considerarsi come istruzioni safe o comunque prive di interferenza.

Ancora grazie, per la spiegazione.
un saluto,
Luca


PS
In caso avessi bisogno effettivamente delle transazioni eg:modifiche multiple su più tables
la soluzione proposta di aprire e chiudere la transazione con gdrcd_query("BEGIN")/gdrcd_query("COMMIT") può risultare valida e quindi anche necessaria?

**Comment by ste-camp** [comment]
Si esatto, purtroppo non è documentata benissimo come cosa, si scopre con l'esperienza e un po' di navigazione nella documentazione di mysql.
C'è un certo numero di dati che vengono mantenuti da MySql stesso all'interno del contesto di una connessione, tipo appunto i dati riguardo l'ultima query eseguita (insert_id, affected_rows, etc) e altro.

Per iniziare una transazione si, direi che il metodo è corretto. Per approfondimenti sui parametri che gli puoi passare: http://dev.mysql.com/doc/refman/5.7/en/commit.html

**Comment by LucaMarzialetti** [comment]
Ciao @ste-camp,
grazie ancora per la questione sulle transazioni. 
Hai risolto i miei dubbi e sicuramente ampliato le mie conoscenze =)
