### ISSUE TITLE
iframe update + $.ajax post?

### ISSUE THREAD

**Issue by LucaMarzialetti** [GDRCD/GDRCD#114]
Gentile staff di GDRCD, 
anche oggi alle prese con il vostro framework :)
Stavo apportando delle modifiche al frame della chat. 
Poiché ho necessità di sviluppare con dei componenti articolati la form dei dadi mi trovo davanti l'esigenza di sottomettere la form tramite jQuery ajax. 
L'unico problema che riscontro è sulla aggiornamento dell'iframe.

Ho aperto un topic su stackoverflow poiché mi sembra una cosa di carattere più generale
http://stackoverflow.com/questions/40090065/jquery-ajax-and-php-iframe-form-target-issue

Vi ringrazio per il vostro contributo
Un saluto
Luca

**Comment by ste-camp** [comment]
Credo che tu stia cercando di mettere insieme due architetture un po' troppo diverse tra loro XD

Mi è capitato anche a me di creare per GDRCD parti dell'interfaccia di chat aggiuntive e la soluzione migliore che mi è venuta in mente è semplicemente di non usare AJAX. Cioè alla fine javascript in realtà ti serve per creare un form, nessuno ti vieta di far fare l'invio dei dati del form con la modalità tradizionale invece che con AJAX.
Imposta il target del form allo stesso target che ha il form classico della chat e aggiungi i tuoi casi speciali al file ref_header.inc.php

In questo modo mantieni l'architettura del sistema senza creare un sistema parallelo che come hai notato avrebbe bisogno di toppe inserite in giro per integrarsi bene con il sistema originale.

**Comment by LucaMarzialetti** [comment]
Ciao @ste-camp ,
si il mio file re_header.inc.php ha nuovi casi,
ho mantenuto per convenzione il vostro paradigma if($_POST["op"]=="mia_azione"){...}.
Successivamente estraggo dalla $_POST i campi settati dalla richiesta $.ajax post con successo e la insert arriva a buon fine su DB, il problema è nel gestire con ajax l'update dell'iframe :S

Mi sono accorto che settando per comodità il parametro ref=1 relativamente a pages/chat.inc.php? l'aggiornamento avviene ma non nello stesso modo pulito di quello gestito dal form submit. 
I CSS sballano e l'aggiornamento sembra coinvolgere la pagina invece che il frame.

**Comment by ste-camp** [comment]
Mmh, mi spiace credo di non capire il tuo problema xD

Iniziamo dal principio: perchè hai bisogno che la richiesta venga fatta con AJAX invece che con un normale submit del form?

**Comment by LucaMarzialetti** [comment]
Scusa, provo a fare chiarezza.
La form non è composta solo da normali elementi input/select, devo poter inviare dati di altri elementi che il normale submit non invia (es: <li> clickabile).
Ho pensato di intercettare gli eventi onclick, invocare una $ajax post componendo manualmente il json.
Credi che farei meglio ad aggiungere dinamicamente dei campi nascosti e fare una normale submit?

**Comment by ste-camp** [comment]
Ah...mmh. Si forse fai prima a creare dei campi nascosti e inviare normalmente piuttosto che usare AJAX.
Ovviamente il modo di farlo funzionare in altro modo dovrebbe esserci, ma mi è difficile capire dov'è effettivamente il punto dove esplode tutto senza avere il codice sott'occhio xD

**Comment by Dyrr** [comment]
con che sintassi tra le varie disponibili di jquery targetti l'iframe dove invii il form?

**Comment by LucaMarzialetti** [comment]
@Dyrr 
Non ho ben chiaro cosa mi hai chiesto, ma credo che è proprio quello che non riesco a fare.
L'unica cosa che targetta l'iframe è questa che invoco in $.ajax on success
$.ajax({
      type: "POST",
      url: "pages/chat.inc.php?ref=10&chat=yes",
      success:function(data){
          $("#chat_frame").html(data); 
          //oppure anche 
          $("#chat_frame").append(data); 
      }
});

Il problema di entrambe rimane che glitchano il CSS ed il refresh non sembra coinvolgere solo l'iframe. Se può servire posso farvi vedere direttamente la versione live montata su altervista così per farvi l'idea.

**Comment by LucaMarzialetti** [comment]
PS 
@ste-camp 
attualmente ho risolto aggiungendo degli <input type="hidden"/> riempiti ad hoc prima del form submit. 
Così il refresh dell'iframe è perfetto, l'unica differenza è che con questa soluzione non posso decidere manualmente il json da inviare nella post.

**Comment by Dyrr** [comment]
Con quella funzione è normale che qualcosa ti sballi nel layout,
quello che restituisce chat.inc.php non è semplicemente un pezzo di dom, ma una pagina html completa, quindi quando la sostituisci o la appendi in #chat_frame sicuramente qualcosa (ipotizzo dei css presenti nell'html caricato o proprio come è formattato il dom visto che appunto non era stato fatto per una chiamata ajax) sballano il layout.

a questo punto hai provato al success di ajax, invece di sostituire o appendere il dom recuperato, ad aggiornare l'iframe con un:
```javascript
$.ajax({
      type: "POST",
      url: "pages/chat.inc.php?ref=10&chat=yes",
      success:function(data){
          $("#chat_frame").attr('attr',url); 
      }
});
```

in maniera da lasciare ad ajax solo l'inserimento dei dati, mentre il recupero al refresh ciclico normale.

Volendo rendere la cosa un po' più performante, si può lavorare un po' sulla pagina che riceve i dati per eliminare tutta la parte html, nel caso in cui riceva i dati via ajax.

**Comment by LucaMarzialetti** [comment]
@Dyrr 
Ciao davide,
si ho provato, ma niente. Il componente no refresha. Nemmeno dopo i secondi indicati dal parametro ref in questo caso.

Come dicevo anche a @ste-camp attualmente ho risolto con l'utilizzo dei campi hidden.
Che patibolo di sofferenze queste tecnologie web ahahahaha.
Grazie ancora del supporto :) 

Come sempre disponibilissimi,
Ci aggiorniamo , tanti saluti 
Luca

**Comment by Dyrr** [comment]
una curiosità. quando invii il form e fai refreshare con il cambio di attr, guardando con gli strumenti di sviluppo, il contenuto dell'iframe come è? nel senso non vorrei mai che per qualche motivo (anche se è strano non ti prenda la part ein _GET dell'url)

**Comment by LucaMarzialetti** [comment]
Ciao @Dyrr scusa il ritardo, 
questi due giorni ho avuto un fermo delle attività.
Allora, avendo già risolto la cosa con il walkaround dei campi, devo risprisintare l'ajax.
Dammi un secondo e ti rispondo :)

**Comment by LucaMarzialetti** [comment]
Ciao @Dyrr scusa il ritardo, 
questi due giorni ho avuto un fermo delle attività.
Allora, avendo già risolto la cosa con il walkaround dei campi, devo risprisintare l'ajax.
Dammi un secondo e ti rispondo :)

**Comment by LucaMarzialetti** [comment]
Ok sono riuscito a ripristinare le cose con l'ajax non funzionante
Allora la chiamata ajax è la seguente:
```
$.ajax({
	type: "POST",
	data: {op:'dice', chat_command:'generico_20'},
	url: "pages/chat.inc.php?ref=10&chat=yes",
	success:function(data){
		//$("#chat_frame").html(data); 
		//oppure anche 
		//$("#chat_frame").append(data);
		$("#chat_frame").attr('attr',url);
	}
});
```

Nuovamente lato server viene gestita correttamente e la insert va a segno (se refresho la pagina il messaggio è visualizzato)

A questo punto il contenuto della risposta ajax è un document HTML compreso di head e body.
Nel body della risposta sono prevalentemente funzioni javascript..(sembra proprio lo stesso dom dell'iframe)

Il contenuto dell'iframe però non sembra subire variazione alcuna :(

**Comment by ste-camp** [comment]
Il body della risposta è sicuramente lo stesso dom che c'è nell'iframe, ma finchè rimane nella variabile data non viene eseguito.
Per inserire del contenuto dentro a un iframe non puoi semplicemente fare append, perchè inseriresti il codice dentro al tag <iframe> nel documento principale.

Invece tu devi accedere al DOM dell'iframe, trovando il suo oggetto document. Dopo di che devi solo sostituire il contenuto del tag html con il nuovo codice che hai ricevuto:

```javascript
$.ajax({
    type: "POST",
    data: {op:'dice', chat_command:'generico_20'},
    url: "pages/chat.inc.php?ref=10&chat=yes",
    success:function(data){
       var html_code=$(data).find('html').html();
       var f = $('#chat_frame')[0];
       var $frameDoc = $(f.contentDocument || f.contentWindow.document);
       $frameDoc.find('html').html(html_code);
    }
});
```

Prova a vedere se così te lo fa fare

**Comment by LucaMarzialetti** [comment]
Nada ancora, 
la post va e viene ma l'iframe continua a non refreshare :S 
Non so come fornirvi maggiori informazioni sul caso

**Comment by breakeryouko** [comment]
chiudo essendo una richiesta vecchia. Nel caso avessi ancora problemi scrivi pure
