### ISSUE TITLE
Lasciare commento oggetto dopo cessione

### ISSUE THREAD

**Issue by Clausus** [GDRCD/GDRCD#116]
Salve a tutti :smile:  è possibile fare in modo che il commento aggiunto da un pg ad un oggetto rimanga quando l'oggetto viene ceduto ad un altro pg? (E che ovviamente il commento sia modificabile dal pg che ha ricevuto l'oggetto) 
Spero di essere riuscito a spiegarmi. Grazie in anticipo.

**Comment by breakeryouko** [comment]
chiudo, nel caso ci fosse necessita' di questa modifica apri una nuova issue
