### ISSUE TITLE
mappaclick campo posizione: utilizzo

### ISSUE THREAD

**Issue by LucaMarzialetti** [GDRCD/GDRCD#117]
Gentile staff, questa issue è una domanda più che un problema.
sono alla prese con la land e la creazione delle mappe con relativa navigabilità, l'idea è quella di avere una struttura di questo tipo: 
(faccio riferimento alla vostra terminologia DB dove mappe=chat, mappacliccabile=macromappa contenente molteplici mappe).
- pagina home con 5 mappe-cliccabili
- cliccando su una di esse dovrei poter visionare le relative mappe/chatroom.

Attualmente tutte le mie mappe-cliccabili hanno stesso ID_posizione e sono tutte visibili, nello specifico una è sempre impostata di default come mappa attuale e le restanti raggiungibili sotto "Altre Zone".

Prima di mettermi a lavoro per fare questa modifica volevo sapere se vi era un modo già implementato nel  sistema per ottenere l'effetto desiderato, avendo notato la presenza di quel campo "posizione".

Vi ringrazio per il supporto :) 
Luca

**Comment by ste-camp** [comment]
Scusa ma da quello che hai scritto mi sembra che hai solo descritto lo stato attuale della tua land, senza specificare quale sarebbe questo "effetto desiderato" che vuoi ottenere.
Tutto quello che hai descritto è già fattibile con il sistema attuale

Inviato dal mio telefono Cyanogenmod

Il 31 gen 2017 02:03 LucaMarzialetti <notifications@github.com> ha scritto:

Gentile staff,
sono alla prese con la land e la creazione delle mappe con relativa navigabilità, l'idea è quella di avere una struttura di questo tipo:
(faccio riferimento alla vostra terminologia DB dove mappe=chat, mappacliccabile=macromappa contenente molteplici mappe).

pagina home con 5 mappe-cliccabilicliccando su una di esse dovrei poter visionare le relative mappe/chatroom. 

Attualmente tutte le mie mappe-cliccabili hanno stesso ID_posizione e sono tutte visibili, nello specifico una è sempre impostata di default come mappa attuale e le restanti raggiungibili sotto "Altre Zone".

Prima di mettermi a lavoro per fare questa modifica volevo sapere se vi era un modo già implementato nel sistema per ottenere l'effetto desiderato, avendo notato la presenza di quel campo "posizione".

Vi ringrazio per il supporto :)
Luca

**Comment by LucaMarzialetti** [comment]
Ciao @ste-camp, 
scusa se sono stato poco chiaro, provo ad esprimermi meglio.
L'effetto desiderato è quello descritto nella bullet list. Sostanzialmente mi servirebbe una specie di "preambolo" nella navigazione delle mappe, cosa che mi sembra di capire si possa fare utilizzando il campo posizione delle "mappaclick". L'inconveniente è che non capisco come questo parametro influenza la visualizzazione delle mappe, quello che noto è che la mia land attualmente usa solo il valore 1 per tutte le mappaclick le quali sono visibili, una in "focus" mostrando le sue mappe legate, le altre sotto la voce "altre zone".

La mia configurazione invece prevede una pagina nella quale mostro solo alcune mappaclick, nessuna di esse è in focus, e solamente cliccando su una di esse arrivo alla pagine con la lista di mappe relative.

Allego anche una foto in aiuto a questa mia descrizione di ancora più ardua comprensione.

Ti ringrazio come sempre per il supporto e per lo sforzo!
https://www.dropbox.com/s/bh7s9s5mrfdxr6x/Immagine.png?dl=0

**Comment by ste-camp** [comment]
Ah ok ora è chiaro. La soluzione è creare una nuova mappaclick, che ti farà da indice per le altre mappe.

Dopo di che dovrai creare dei luoghi da inserire nella mappa indice (luoghi non mappe!). Ogni luogo può essere collegato a una mappa, perciò non dovrai fare altro che collegare i luoghi inseriti nella mappa indice con le sotto mappe che vuoi far apparire.
Dopo di che potrai dare lo stile che preferisci ai luoghi mostrati sulla mappa indice

Lascia stare il campo posizione, serve solo a far apparire le mappe in "altri luoghi" xD

**Comment by LucaMarzialetti** [comment]
Ciao @ste-camp,
sto provando ad implementare la soluzione da te consigliata,
quello che mi sfugge è cosa intendi per _**luoghi**_, attualmente nel DB ho solamente mappaclick e mappa.
La relazione attualmente tra le due è quella di uno a molti: [mappaclick 1] ---- [* mappa].
Quello che a me servirebbe è una sorta di relazione che mi consenta di specificare una relazione mappaclick-mappaclick. 
Potresti essere più chiaro?
Ti ringrazio ancora anticipatamente,
Luca

**Comment by ste-camp** [comment]
Io ti consiglierei di guardare le pagine di gestione che sono già incluse nel pacchetto.
Vedrai che GDRCD include due gestioni, una si chiama Gestione Luoghi e si occupa di manipolare i dati nella tabella mappa. L'altra di chiama Gestione Mappe e si occupa di manipolare i dati nella tabella mappaclick

A causa della struttura attuale dei sistema non è possibile fare un collegamento diretto mappaclick-mappaclick
ma si può fare un collegamento mappaclick-mappa-mappaclick usando il campo id_mappa_collegata della mappa. A livello "grafico" sembrerà a tutti gli effetti che la tua mappaclick principale sia collegata a un'altra mappaclick.
Se vedi sulla pagina di Gestione dei Luoghi vedrai proprio che tra le varie indicazioni nel form è proprio scritto "questo campo può essere usato per creare un sistema di sottomappe" che è quello che vuoi te.

**Comment by LucaMarzialetti** [comment]
Ti ringrazio per la velocità con cui mi hai risposto :) 
Proverò e ti farò sapere, la questione 

> ma si può fare un collegamento mappaclick-mappa-mappaclick usando il campo id_mappa_collegata della mappa

Mi ha tolto i dubbi a riguardo.
So che sono scemenze quelle da me chieste, lo faccio però per potermi mantenere allineato il più possibile al framework senza reinventarmi le meccaniche li dove ci sono. ancora 1000thx 👍

**Comment by ste-camp** [comment]
Si non è una soluzione elegante...è più una pezza che è stata messa XD però funziona

**Comment by LucaMarzialetti** [comment]
Per il momento fa il suo lavoro, tutto ok per il momento. Alla prossima :P 
Grazie ;)
