### ISSUE TITLE
cambio skin base

### ISSUE THREAD

**Issue by ella1996** [GDRCD/GDRCD#118]
Buongiorno, chiedo scusa per il topic che sicuramente risulterà inutile ma sono ancora alle prime armi.
Ho creato la land e ora sono in fase di configurarla ma ho un problema basilare: quando utilizzo la skin "advanced" mi va tutto perfettamente mentre quando la modifico con la skin "basic" sul file config.inc.php la home cambia ma le pagine come "iscrizione", "regolamento" o "ambientazione" non funzionano più: se ci si clicca sopra, si noterà che manca proprio la pagina. Ed effettivamente le pagine mancano!
Ho tentato allora di prendere i file di iscrizione e ambientazione e incollarli nella gestione generale dei documenti, sperando così di creare le pagine "mancanti".
Conseguenza?
Il messaggio d'errore di iscrizione è: Fatal error: Call to undefined function gdrcd_filter() in /membri/link/iscrizione.php on line 3
Il messaggio d'errore di ambientazione è: Fatal error: Call to undefined function gdrcd_filter() in /membri/link/pages/user_ambientazione.inc.php on line 2
...Regolamento resta tutt'ora inesistente.
Insomma, sono molto confusa. Chi può aiutarmi? :)

**Comment by ste-camp** [comment]
è un bug nel sistema. Facendo le modifiche indicate in 4230f7a puoi sistemare il problema

**Comment by ella1996** [comment]
Ho risolto apportando le modifiche indicate in 4230f7a.
Grazie mille :)
