### ISSUE TITLE
modifica css

### ISSUE THREAD

**Issue by ella1996** [GDRCD/GDRCD#119]
Buonasera, sono di nuovo qui con una nuova domanda che non so se sia dovuta a un bug o una mia poca competenza con i codici.
Sto tentando di modificare il CSS della mia land con il gdrcd 5.4 andando in themes-> basic e da lì cercando modificare i parametri inizialmente in piccole cose per capire "cosa" è "cosa" quindi ho tentato di cambiare il colore ai bordi e le varie larghezze ma.... non si modifica nulla.
Non una piccolissima modifica, rimane tutto invariato. Rendo la larghezza della scheda 400 invece che 500? resta invariata.
Rendo i riquadri tratteggiati della home preimpostati rossi? Restano bianchi come sono stati settati. Insomma, cerco aiuto :)
Grazie in anticipo

**Comment by LucaMarzialetti** [comment]
Domanda lecita:
1) stai lavorando in locale o su server? ricordati in caso di uppare i file al server se lavori in locale :)
2) attento alle cache dei browser e dei server. Controlla dalla console del browser se le versioni dei file (css e script) sono quelli giusti. In caso non lo siano vai di ctrl+shift+r per un refresh con flush delle cache.
3) ultima ma non meno importante attento che il CSS non venga sovrascritto. Controlla, sempre dalla console, il cascading.
