### ISSUE TITLE
Errore in gestione_mercato.ing.php

### ISSUE THREAD

**Issue by Dyrr** [GDRCD/GDRCD#121]
Quando si cancella un oggetto dalla land e il gdrcd controlla i pg che lo possiedono per restituire i soldi se ci sono personaggi che lo possiedono che hanno un nome con apici la query si pianta perchè manca l'escape dei caratteri.
```php
    while ($do_refound = gdrcd_query($refound, 'fetch'))  {
        gdrcd_query("UPDATE personaggio SET soldi = soldi + ".gdrcd_filter('num',$rec['costo'])." WHERE nome = '".$do_refound['nome']."'");
    }
```

da correggere con

```php
    while ($do_refound = gdrcd_query($refound, 'fetch'))  {
        gdrcd_query("UPDATE personaggio SET soldi = soldi + ".gdrcd_filter('num',$rec['costo'])." WHERE nome = '".gdrcd_filter_in($do_refound['nome'])."'");
    }
```

lascio qui come nota, se ho tempo correggo direttamente io

**Comment by breakeryouko** [comment]
implementato
