### ISSUE TITLE
Fatal error: Allowed memory size of 536870912 bytes exhausted su Server privato.

### ISSUE THREAD

**Issue by Mancy-eye** [GDRCD/GDRCD#123]
Ciao a tutti, 

stavo provando ad hostare GDRCD (V5.3.2) sul mio NAS Synology, ma ho questo errore: 
`Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 77 bytes) in /volume1/web/GDRCD-5.3.2/includes/functions.inc.php on line 211 `
La cosa assurda è che ho già modificato il php.ini, ho aumentato il memory_limit da 64M a 128M fino a 512M ma continua a darmi il fatal error. 
Per assurdo ho anche provato a dargli il -1 e mi ha preso tutti gli 8GB di RAM crashando il NAS. 
- PHP 5.6
- Apache 2.4

Avete qualche suggerimento?

**Comment by Mancy-eye** [comment]
Con xdebug:

`

( ! )  Fatal error: Uncaught Error: Maximum function nesting level of '256'  reached, aborting! in /volume1/web/lumos/includes/functions.inc.php on  line 211
--



1 | 0.0014 | 390008 | {main}(  ) | .../installer.php:0
2 | 0.0020 | 390384 | require( '/volume1/web/lumos/header.inc.php' ) | .../installer.php:3
3 | 0.0183 | 496752 | gdrcd_connect(  ) | .../header.inc.php:35
4 | 0.0193 | 497152 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
5 | 0.0237 | 499592 | gdrcd_connect(  ) | .../functions.inc.php:214
6 | 0.0239 | 499592 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
7 | 0.0239 | 503248 | gdrcd_connect(  ) | .../functions.inc.php:214
8 | 0.0241 | 503248 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
9 | 0.0241 | 508088 | gdrcd_connect(  ) | .../functions.inc.php:214
10 | 0.0242 | 508088 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
11 | 0.0242 | 514432 | gdrcd_connect(  ) | .../functions.inc.php:214
12 | 0.0243 | 514432 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
13 | 0.0243 | 521960 | gdrcd_connect(  ) | .../functions.inc.php:214
14 | 0.0244 | 521960 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
15 | 0.0245 | 530672 | gdrcd_connect(  ) | .../functions.inc.php:214
16 | 0.0246 | 530672 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
17 | 0.0246 | 540568 | gdrcd_connect(  ) | .../functions.inc.php:214
18 | 0.0247 | 540568 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
19 | 0.0247 | 552288 | gdrcd_connect(  ) | .../functions.inc.php:214
20 | 0.0248 | 552288 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
21 | 0.0249 | 565192 | gdrcd_connect(  ) | .../functions.inc.php:214
22 | 0.0250 | 565192 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
23 | 0.0250 | 579280 | gdrcd_connect(  ) | .../functions.inc.php:214
24 | 0.0251 | 579280 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
25 | 0.0251 | 594552 | gdrcd_connect(  ) | .../functions.inc.php:214
26 | 0.0252 | 594552 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
27 | 0.0253 | 611008 | gdrcd_connect(  ) | .../functions.inc.php:214
28 | 0.0254 | 611008 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
29 | 0.0254 | 628648 | gdrcd_connect(  ) | .../functions.inc.php:214
30 | 0.0255 | 628648 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
31 | 0.0255 | 647472 | gdrcd_connect(  ) | .../functions.inc.php:214
32 | 0.0256 | 647472 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
33 | 0.0257 | 667480 | gdrcd_connect(  ) | .../functions.inc.php:214
34 | 0.0258 | 667480 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
35 | 0.0258 | 689952 | gdrcd_connect(  ) | .../functions.inc.php:214
36 | 0.0259 | 689952 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
37 | 0.0259 | 713608 | gdrcd_connect(  ) | .../functions.inc.php:214
38 | 0.0261 | 713608 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
39 | 0.0261 | 738448 | gdrcd_connect(  ) | .../functions.inc.php:214
40 | 0.0262 | 738448 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
41 | 0.0262 | 764472 | gdrcd_connect(  ) | .../functions.inc.php:214
42 | 0.0263 | 764472 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
43 | 0.0264 | 791680 | gdrcd_connect(  ) | .../functions.inc.php:214
44 | 0.0265 | 791680 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
45 | 0.0265 | 820072 | gdrcd_connect(  ) | .../functions.inc.php:214
46 | 0.0266 | 820072 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
47 | 0.0267 | 849648 | gdrcd_connect(  ) | .../functions.inc.php:214
48 | 0.0268 | 849648 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
49 | 0.0268 | 880408 | gdrcd_connect(  ) | .../functions.inc.php:214
50 | 0.0269 | 880408 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
51 | 0.0270 | 912352 | gdrcd_connect(  ) | .../functions.inc.php:214
52 | 0.0271 | 912352 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
53 | 0.0271 | 944728 | gdrcd_connect(  ) | .../functions.inc.php:214
54 | 0.0272 | 944728 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
55 | 0.0273 | 977104 | gdrcd_connect(  ) | .../functions.inc.php:214
56 | 0.0274 | 977104 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
57 | 0.0274 | 1009480 | gdrcd_connect(  ) | .../functions.inc.php:214
58 | 0.0275 | 1009480 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
59 | 0.0276 | 1041856 | gdrcd_connect(  ) | .../functions.inc.php:214
60 | 0.0277 | 1041856 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
61 | 0.0277 | 1074232 | gdrcd_connect(  ) | .../functions.inc.php:214
62 | 0.0278 | 1074232 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
63 | 0.0279 | 1106608 | gdrcd_connect(  ) | .../functions.inc.php:214
64 | 0.0280 | 1106608 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
65 | 0.0280 | 1138984 | gdrcd_connect(  ) | .../functions.inc.php:214
66 | 0.0281 | 1138984 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
67 | 0.0281 | 1171360 | gdrcd_connect(  ) | .../functions.inc.php:214
68 | 0.0282 | 1171360 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
69 | 0.0283 | 1203736 | gdrcd_connect(  ) | .../functions.inc.php:214
70 | 0.0284 | 1203736 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
71 | 0.0284 | 1236112 | gdrcd_connect(  ) | .../functions.inc.php:214
72 | 0.0285 | 1236112 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
73 | 0.0286 | 1268488 | gdrcd_connect(  ) | .../functions.inc.php:214
74 | 0.0287 | 1268488 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
75 | 0.0287 | 1300864 | gdrcd_connect(  ) | .../functions.inc.php:214
76 | 0.0288 | 1300864 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
77 | 0.0289 | 1333240 | gdrcd_connect(  ) | .../functions.inc.php:214
78 | 0.0290 | 1333240 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
79 | 0.0290 | 1365616 | gdrcd_connect(  ) | .../functions.inc.php:214
80 | 0.0291 | 1365616 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
81 | 0.0291 | 1397992 | gdrcd_connect(  ) | .../functions.inc.php:214
82 | 0.0292 | 1397992 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
83 | 0.0293 | 1430368 | gdrcd_connect(  ) | .../functions.inc.php:214
84 | 0.0294 | 1430368 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
85 | 0.0294 | 1462744 | gdrcd_connect(  ) | .../functions.inc.php:214
86 | 0.0295 | 1462744 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
87 | 0.0295 | 1495120 | gdrcd_connect(  ) | .../functions.inc.php:214
88 | 0.0297 | 1495120 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
89 | 0.0297 | 1527496 | gdrcd_connect(  ) | .../functions.inc.php:214
90 | 0.0298 | 1527496 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
91 | 0.0299 | 1559872 | gdrcd_connect(  ) | .../functions.inc.php:214
92 | 0.0300 | 1559872 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
93 | 0.0300 | 1592248 | gdrcd_connect(  ) | .../functions.inc.php:214
94 | 0.0301 | 1592248 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
95 | 0.0301 | 1624624 | gdrcd_connect(  ) | .../functions.inc.php:214
96 | 0.0303 | 1624624 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
97 | 0.0303 | 1657000 | gdrcd_connect(  ) | .../functions.inc.php:214
98 | 0.0304 | 1657000 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
99 | 0.0305 | 1689376 | gdrcd_connect(  ) | .../functions.inc.php:214
100 | 0.0306 | 1689376 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
101 | 0.0306 | 1721752 | gdrcd_connect(  ) | .../functions.inc.php:214
102 | 0.0308 | 1721752 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
103 | 0.0308 | 1754128 | gdrcd_connect(  ) | .../functions.inc.php:214
104 | 0.0309 | 1754128 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
105 | 0.0310 | 1786504 | gdrcd_connect(  ) | .../functions.inc.php:214
106 | 0.0311 | 1786504 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
107 | 0.0311 | 1818880 | gdrcd_connect(  ) | .../functions.inc.php:214
108 | 0.0312 | 1818880 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
109 | 0.0313 | 1851256 | gdrcd_connect(  ) | .../functions.inc.php:214
110 | 0.0314 | 1851256 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
111 | 0.0314 | 1883632 | gdrcd_connect(  ) | .../functions.inc.php:214
112 | 0.0316 | 1883632 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
113 | 0.0316 | 1916008 | gdrcd_connect(  ) | .../functions.inc.php:214
114 | 0.0318 | 1916008 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
115 | 0.0318 | 1948384 | gdrcd_connect(  ) | .../functions.inc.php:214
116 | 0.0320 | 1948384 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
117 | 0.0320 | 1980760 | gdrcd_connect(  ) | .../functions.inc.php:214
118 | 0.0321 | 1980760 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
119 | 0.0322 | 2013136 | gdrcd_connect(  ) | .../functions.inc.php:214
120 | 0.0323 | 2013136 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
121 | 0.0323 | 2045512 | gdrcd_connect(  ) | .../functions.inc.php:214
122 | 0.0324 | 2045512 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
123 | 0.0325 | 2077888 | gdrcd_connect(  ) | .../functions.inc.php:214
124 | 0.0326 | 2077888 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
125 | 0.0327 | 2110264 | gdrcd_connect(  ) | .../functions.inc.php:214
126 | 0.0328 | 2110264 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
127 | 0.0328 | 2142640 | gdrcd_connect(  ) | .../functions.inc.php:214
128 | 0.0330 | 2142640 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
129 | 0.0330 | 2175016 | gdrcd_connect(  ) | .../functions.inc.php:214
130 | 0.0331 | 2175016 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
131 | 0.0331 | 2207392 | gdrcd_connect(  ) | .../functions.inc.php:214
132 | 0.0333 | 2207392 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
133 | 0.0333 | 2239768 | gdrcd_connect(  ) | .../functions.inc.php:214
134 | 0.0334 | 2239768 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
135 | 0.0335 | 2272144 | gdrcd_connect(  ) | .../functions.inc.php:214
136 | 0.0336 | 2272144 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
137 | 0.0337 | 2304520 | gdrcd_connect(  ) | .../functions.inc.php:214
138 | 0.0338 | 2304520 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
139 | 0.0338 | 2336896 | gdrcd_connect(  ) | .../functions.inc.php:214
140 | 0.0339 | 2336896 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
141 | 0.0340 | 2369272 | gdrcd_connect(  ) | .../functions.inc.php:214
142 | 0.0341 | 2369272 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
143 | 0.0341 | 2401648 | gdrcd_connect(  ) | .../functions.inc.php:214
144 | 0.0343 | 2401648 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
145 | 0.0343 | 2434024 | gdrcd_connect(  ) | .../functions.inc.php:214
146 | 0.0344 | 2434024 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
147 | 0.0345 | 2466400 | gdrcd_connect(  ) | .../functions.inc.php:214
148 | 0.0346 | 2466400 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
149 | 0.0346 | 2498776 | gdrcd_connect(  ) | .../functions.inc.php:214
150 | 0.0347 | 2498776 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
151 | 0.0348 | 2531152 | gdrcd_connect(  ) | .../functions.inc.php:214
152 | 0.0349 | 2531152 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
153 | 0.0349 | 2563528 | gdrcd_connect(  ) | .../functions.inc.php:214
154 | 0.0351 | 2563528 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
155 | 0.0351 | 2595904 | gdrcd_connect(  ) | .../functions.inc.php:214
156 | 0.0352 | 2595904 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
157 | 0.0353 | 2628280 | gdrcd_connect(  ) | .../functions.inc.php:214
158 | 0.0354 | 2628280 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
159 | 0.0354 | 2660656 | gdrcd_connect(  ) | .../functions.inc.php:214
160 | 0.0355 | 2660656 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
161 | 0.0356 | 2693032 | gdrcd_connect(  ) | .../functions.inc.php:214
162 | 0.0358 | 2693032 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
163 | 0.0358 | 2725408 | gdrcd_connect(  ) | .../functions.inc.php:214
164 | 0.0360 | 2725408 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
165 | 0.0360 | 2757784 | gdrcd_connect(  ) | .../functions.inc.php:214
166 | 0.0361 | 2757784 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
167 | 0.0361 | 2790160 | gdrcd_connect(  ) | .../functions.inc.php:214
168 | 0.0363 | 2790160 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
169 | 0.0363 | 2822536 | gdrcd_connect(  ) | .../functions.inc.php:214
170 | 0.0364 | 2822536 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
171 | 0.0365 | 2854912 | gdrcd_connect(  ) | .../functions.inc.php:214
172 | 0.0366 | 2854912 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
173 | 0.0367 | 2887288 | gdrcd_connect(  ) | .../functions.inc.php:214
174 | 0.0368 | 2887288 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
175 | 0.0368 | 2919664 | gdrcd_connect(  ) | .../functions.inc.php:214
176 | 0.0369 | 2919664 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
177 | 0.0370 | 2952040 | gdrcd_connect(  ) | .../functions.inc.php:214
178 | 0.0371 | 2952040 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
179 | 0.0371 | 2984416 | gdrcd_connect(  ) | .../functions.inc.php:214
180 | 0.0372 | 2984416 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
181 | 0.0373 | 3016792 | gdrcd_connect(  ) | .../functions.inc.php:214
182 | 0.0374 | 3016792 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
183 | 0.0374 | 3049168 | gdrcd_connect(  ) | .../functions.inc.php:214
184 | 0.0376 | 3049168 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
185 | 0.0376 | 3081544 | gdrcd_connect(  ) | .../functions.inc.php:214
186 | 0.0378 | 3081544 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
187 | 0.0378 | 3113920 | gdrcd_connect(  ) | .../functions.inc.php:214
188 | 0.0379 | 3113920 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
189 | 0.0380 | 3146296 | gdrcd_connect(  ) | .../functions.inc.php:214
190 | 0.0381 | 3146296 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
191 | 0.0381 | 3178672 | gdrcd_connect(  ) | .../functions.inc.php:214
192 | 0.0382 | 3178672 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
193 | 0.0383 | 3211048 | gdrcd_connect(  ) | .../functions.inc.php:214
194 | 0.0385 | 3211048 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
195 | 0.0385 | 3243424 | gdrcd_connect(  ) | .../functions.inc.php:214
196 | 0.0386 | 3243424 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
197 | 0.0387 | 3275800 | gdrcd_connect(  ) | .../functions.inc.php:214
198 | 0.0388 | 3275800 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
199 | 0.0389 | 3308176 | gdrcd_connect(  ) | .../functions.inc.php:214
200 | 0.0390 | 3308176 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
201 | 0.0390 | 3340552 | gdrcd_connect(  ) | .../functions.inc.php:214
202 | 0.0391 | 3340552 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
203 | 0.0392 | 3372928 | gdrcd_connect(  ) | .../functions.inc.php:214
204 | 0.0393 | 3372928 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
205 | 0.0394 | 3405304 | gdrcd_connect(  ) | .../functions.inc.php:214
206 | 0.0395 | 3405304 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
207 | 0.0396 | 3437680 | gdrcd_connect(  ) | .../functions.inc.php:214
208 | 0.0397 | 3437680 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
209 | 0.0398 | 3470056 | gdrcd_connect(  ) | .../functions.inc.php:214
210 | 0.0399 | 3470056 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
211 | 0.0399 | 3502432 | gdrcd_connect(  ) | .../functions.inc.php:214
212 | 0.0401 | 3502432 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
213 | 0.0401 | 3534808 | gdrcd_connect(  ) | .../functions.inc.php:214
214 | 0.0402 | 3534808 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
215 | 0.0403 | 3567184 | gdrcd_connect(  ) | .../functions.inc.php:214
216 | 0.0404 | 3567184 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
217 | 0.0404 | 3599560 | gdrcd_connect(  ) | .../functions.inc.php:214
218 | 0.0405 | 3599560 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
219 | 0.0406 | 3631936 | gdrcd_connect(  ) | .../functions.inc.php:214
220 | 0.0407 | 3631936 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
221 | 0.0408 | 3664312 | gdrcd_connect(  ) | .../functions.inc.php:214
222 | 0.0409 | 3664312 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
223 | 0.0409 | 3696688 | gdrcd_connect(  ) | .../functions.inc.php:214
224 | 0.0410 | 3696688 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
225 | 0.0411 | 3729064 | gdrcd_connect(  ) | .../functions.inc.php:214
226 | 0.0412 | 3729064 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
227 | 0.0413 | 3761440 | gdrcd_connect(  ) | .../functions.inc.php:214
228 | 0.0414 | 3761440 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
229 | 0.0414 | 3793816 | gdrcd_connect(  ) | .../functions.inc.php:214
230 | 0.0415 | 3793816 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
231 | 0.0416 | 3826192 | gdrcd_connect(  ) | .../functions.inc.php:214
232 | 0.0417 | 3826192 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
233 | 0.0418 | 3858568 | gdrcd_connect(  ) | .../functions.inc.php:214
234 | 0.0419 | 3858568 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
235 | 0.0419 | 3890944 | gdrcd_connect(  ) | .../functions.inc.php:214
236 | 0.0420 | 3890944 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
237 | 0.0421 | 3923320 | gdrcd_connect(  ) | .../functions.inc.php:214
238 | 0.0422 | 3923320 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
239 | 0.0422 | 3955696 | gdrcd_connect(  ) | .../functions.inc.php:214
240 | 0.0424 | 3955696 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
241 | 0.0424 | 3988072 | gdrcd_connect(  ) | .../functions.inc.php:214
242 | 0.0425 | 3988072 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
243 | 0.0426 | 4020448 | gdrcd_connect(  ) | .../functions.inc.php:214
244 | 0.0427 | 4020448 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
245 | 0.0428 | 4052824 | gdrcd_connect(  ) | .../functions.inc.php:214
246 | 0.0429 | 4052824 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
247 | 0.0429 | 4085200 | gdrcd_connect(  ) | .../functions.inc.php:214
248 | 0.0430 | 4085200 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
249 | 0.0431 | 4117576 | gdrcd_connect(  ) | .../functions.inc.php:214
250 | 0.0432 | 4117576 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
251 | 0.0433 | 4149952 | gdrcd_connect(  ) | .../functions.inc.php:214
252 | 0.0434 | 4149952 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
253 | 0.0434 | 4182328 | gdrcd_connect(  ) | .../functions.inc.php:214
254 | 0.0436 | 4182328 | gdrcd_mysql_error(  ) | .../functions.inc.php:36
255 | 0.0436 | 4214704 | gdrcd_connect(  ) | .../functions.inc.php:214
256 | 0.0438 | 4214704 | gdrcd_mysql_error(  ) | .../functions.inc.php:36

`

**Comment by ste-camp** [comment]
Ciao!
Questo è un problema noto di gdrcd, che si prende tutte le risorse disponibili a sistema mentre cerca di stampare un errore sql.
Il difetto è dovuto a due funzioni mutualmente ricorsive nella gestione degli errori sql.

Semplicemente assicurati che la tua configurazione del db sia corretta, che il db sia raggiungibile e con le credenziali corrette. E l'errore sparirà.

Se non riesci a risolvere senza avere la stringa di errore sql dovresti modificare il file includes/functions.inc.php e modificare la gdrcd_mysql_error per evitare che chiami la gdrcd_connect

**Comment by Mancy-eye** [comment]
Ti ringrazio!

**Comment by Mancy-eye** [comment]
E' molto strano, le informazioni sono corrette, ho un sito wordpress hostato e connesso con le stesse info, ma GDRCD continua a darmi lo stesso error.
In breve il NAS usa Maria DB 10, il path del db è localhost:/run/mysqld/mysqld10.sock già provato sostituendo 127.0.0.1 a localhost e localhost e 127.0.0.1 senza il path completo. 
L'unica cosa che ho notato è che avevo due account diversi Admin e root, con DB diversi, ma anche dando l'user corretto (owner del db gdrcd) continua a stampare il fatal error. 
PS: Che versione di PHP è consigliabile usare? 5.6 7.0 o 7.2?

**Comment by ste-camp** [comment]
Mmh purtroppo dipende tutto da come è configurato il tuo server/nas. È difficile aiutarti così.
Puoi passare in configurazione di gdrcd qualunque cosa che la libreria mysqli accetti come parametro per la connessione.
Assicurati che ci sia installata l'estensione mysqli sul tuo server.

Per la versione di php nonostante credo che funzioni con php 7, non l'ho mai provato. Quindi ti suggerirei di usare la versione più recente che hai di php 5.

**Comment by Mancy-eye** [comment]
Imbarazzante, mi è bastato specificare la porta dopo localhost e funziona perfettamente *facepalm*, grazie comunque per il tuo tempo! 
Grazie anche per la risposta sulla versione php, buona giornata :)
