### ISSUE TITLE
Informativa privacy

### ISSUE THREAD

**Issue by iloveireland** [GDRCD/GDRCD#124]
Buongiorno.
Ho scaricato i pacchetti di GDRCD (compresa l'ultima versione) e ho notato che l'informativa privacy fa rifermento a leggi del 2003, che nel frattempo (soprattutto negli ultimi anni) sono state sostituite.

E' disponibile una versione delle pagine di iscrizione con normative aggiornate?

**Comment by breakeryouko** [comment]
Se noti il codice non viene aggiornato da anni. In linea teorica non è l'informativa sulla privacy l'unico problema. Anche il livello di sicurezza sono al di sotto dello standard richiesto ai giorni nostri. Se hai voglia di aggiornare l'informativa nulla ti viene di creare una PR. Ti ringrazio nel caso volessi contribuire

**Comment by iloveireland** [comment]
Ahimè non ne sono in grado.
Vi ringrazio per il lavoro fatto su gdrcd, perchè anche chi sa fare ben poco possa aprire una sua land, ma questo lavoro a parer mio è "deleterio" se poi si mettono i gestori meno attenti in posizioni di "illegalità". 
Passatemi i termini non corretti... 
Credo che con lo stesso spirito con cui si è creato gdrcd, bisognerebbe renderlo "legale" così che possa essere utilizzato in sicurezza. 
Spero che qualche programmatore più esperto di me in codici e questioni legali, voglia contribuire.
Grazie

**Comment by breakeryouko** [comment]
Il problema è che molte parti di gdrcd sono fuori norma a partire dal fatto che le password possono essere salvate in chiaro.

**Comment by breakeryouko** [comment]
Ho fatto un controllo, per quando riguarda il GDPR l'unico dato sensibile che viene trattato e' l'indirizzo email quindi non penso sia un grosso lavoro. Appena ho tempo vedo di farlo

**Comment by iloveireland** [comment]
Grazie :)

**Comment by breakeryouko** [comment]
Con la versione 5.5 non vengono piu' trattati dati sensibili, l'unico e' l'indirizzo IP.
Essendo l'argomento ancora incerto non vi e' l'obbligo di dichiarare l'utilizzo degli indirizzi IP e quindi GDRCD 5.5 non ha problemi con il nuovo GDPR, chi usa vecchie versioni può aggiornare i file criptando gli indirizzi email oppure dichiarare l'utilizzo che ne fa secondo la normativa vigente.
