### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by birkolo90** [GDRCD/GDRCD#132]
ciao a tutti, sono nuovo in nella programmazione e vorrei provare a fare un gdr, ma mi da in fatal error dicendomi che la memoria non è sufficente, come posso risolvere questo incoveniente?

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 72 bytes) in /membri/onepiecerevolution/includes/functions.inc.php on line 213

**Comment by breakeryouko** [comment]
hai dimenticato di configurare i dati nel config.inc.php, solitamente sono i dati del database di altervista

**Comment by birkolo90** [comment]
come posso configurarli?

**Comment by breakeryouko** [comment]
vai sul file e fai modifica. Esiste un file chiamato come fare la land, leggimi. Ti consiglio di leggerlo

**Comment by birkolo90** [comment]
grazie, ho risolto ma credo che si sia attivata la protezione e non capisco come toglierla?

**Comment by breakeryouko** [comment]
Apri una nuova issue in modo da tenere tutto più ordinato. Comunque nel tuo caso specifico ti basta impostare su OFF nel file config.inc.php la voce protezione
