### ISSUE TITLE
Gdrcd 5.5 Bacheca - Visualizzazione discussioni Bug

### ISSUE THREAD

**Issue by ardagdr** [GDRCD/GDRCD#133]
Immetto qui di seguito le stringe che escono come errore nel tentar di aprire le discussioni della bacheca. Premetto che ho solo caricato fin a questo momento il pacchetto di base presente senza apportare modifiche di codice, sto ancora smanettando solo sulle impostazioni del tema e dei moduli.

`GDRCD MySQLi Error [File: visit.inc.php; Line: 51]
Error Code: 1054
Error String: Unknown column 'MA.data_ultimo_messaggio' in 'field list'

Error Detail: SELECT MA.id_messaggio, MA.titolo, MA.autore, MA.data_messaggio, MA.data_ultimo_messaggio, MA.importante, MA.chiuso, AL.id AS new_msg FROM messaggioaraldo AS MA LEFT JOIN araldo_letto AS AL ON MA.id_messaggio=AL.thread_id AND AL.nome='Super' WHERE MA.id_messaggio_padre = -1 AND MA.id_araldo = 2 ORDER BY MA.importante DESC, MA.data_ultimo_messaggio DESC LIMIT 0, 15`

**Comment by Kheperet** [comment]
Hai istallato il DB di GDRCD5.5?
Il DB 5.5, rispetto a 5.4, ha un campo in più nella tabella "messaggioaraldo":
data_ultimo_messaggio datetime default NULL,

L'errore che ci sembrerebbe indicare che questo campo non è presente, quindi che il DB installato sia quello della versione 5.4 di GDRCD

**Comment by breakeryouko** [comment]
Hai installato GDRCD tramite installer.php?

**Comment by ardagdr** [comment]
rifatto la procedura, si errore mio chiedo venia. Avevo caricato semplicemente. Ho rifatto seguendo la procedura installer e funziona. Chiedo scusa

**Comment by breakeryouko** [comment]
chiudo essendo risolto
