### ISSUE TITLE
Bug AGGIORNA chat

### ISSUE THREAD

**Issue by Rander89** [GDRCD/GDRCD#134]
Mi sono accorto di un'anomalia presente nell'aggiorna chat (sia premendo F5 sia clikkando il tasto AGGIORNA), per cui la chat viene completamente cancellata. 
Qualora io restassi sulla chat senza premere nulla, e quindi senza aggiornare, leggerei tutte le azioni... Ma appena mi azzardo a uscire dalla chat e poi rientrare (per qualsiasi motivo e in qualsiasi modo) la chat scompare

**Comment by breakeryouko** [comment]
Ho controllato il codice, in pratica e' dovuto dal fatto che ogni volta che carichi le chat ti si aggiorna la variabile $_SESSION['last_message'], questo registra l'ultimo messaggio che hai caricato. D'ora in avanti ti carica solo le chat che compaiono dopo questo valore

**Comment by Rander89** [comment]
Quibdi devo andare a modificare la pagina ref, giusto?

**Comment by breakeryouko** [comment]
si, le pagine sono:
frame_chat, ref_header

**Comment by Johnsilv3r** [comment]
Ciao, ho caricato una versione di prova ieri (22 giu) e ho tentato l'accesso con super su un browser e test su un altro, quando invio i messaggi su una chat, l'uno non vede quelli dell'altro. Il suono viene riprodotto correttamente.

**Comment by breakeryouko** [comment]
Aggiorna alla 5.5.1 e riprova

**Comment by Johnsilv3r** [comment]
Ho fatto diverse prove fra ieri e oggi, i risultati (post visibile, suono riprodotto) cambiano da browser a browser
Da altri browser verso Chrome, i primi post iniziano a passare dopo un minuto circa che i due utenti sono connessi nella stessa chat (o dopo che hai scritto la prima volta con l'utente su Chrome), non so se è un problema soltanto mio.

Ho utilizzato (e incrociato in vari modi) Explorer, Opera, Opera GX, Chrome, spero che il feedback possa essere utile
In tutti i casi, se aggiorno anche senza F5, scompare tutto

**Comment by Rander89** [comment]
Niente, ho provato a fare quanto detto da breaker, ma il problema resta immutato.
Ho letto su gdr on-line che inserendo il codice della versione 4.1 il bug si risolve (ed è vero). 
Ho provato anche io a trovare delle differenze fra i 2 codici, ma sono sostanzialmente uguali. 
Voi avete idee?

**Comment by Seralia** [comment]
Mi sembra il problema riguardi l'aggiornamento per l'audio in chat. Non ho tentato di risolverlo, ma dovrebbe essere qualcosa nella gestione della variabile sui nuovi messaggi  per cui attivare l'audio che impatta con il refresh...

**Comment by Kasui92** [comment]
Il motivo dell'errore è legato alla valorizzazione di **$_SESSION['last_message']**.

Come giustamente ha detto @breakeryouko , nel contenitore della chat vengono caricate le azioni ( i record nella tabella `chat` ) il cui `id` è superiore a **$_SESSION['last_message']**.  Quest'ultimo viene inizializzato a 0 nel momento del login e viene aggiornato ogni volta che viene chiamato _ref_header.inc.php_ , in modo da non dover ogni volta ricostruire la chat ma appenderci sotto solo le ultime azioni inviate. Essendo questa una variabile di sessione, è persistente fino a quando la sessione rimane istanziata.

Pertanto, se carico una chat dove ci sono 5 azioni, _ref_header.inc.php_ me le mostra e poi valorizza **$_SESSION['last_message']** con l'ultimo _id_ di queste 5 azioni, in modo che quando avviene il refresh automatico mi carichi solo le azioni superiori a quest'ultimo _id_. Se io aggiorno la pagina, tramite il refresh del browser o il pulsante **Aggiorna**, **$_SESSION['last_message']**, che è appunto persistente, ha mantenuto l'ultimo id associato e _ref_header.inc.php_ caricherà solo ed esclusivamente le azioni con _id_ superiore a questo, che potrebbero essere appunto nessuna. E questo spiega il bug.

Il motivo per cui inviando una azione questa viene subito visualizzata è perchè quando si invia viene richiamato comunque _ref_header.inc.php_, ma prima si effettua l'operazione di inserimento e poi si controlla le azioni superiori a **$_SESSION['last_message']**. Per un ordine logico, questa viene aggiunta, come deve giustamente avvenire.

Andrebbe escogitato un altro modo per caricare i messaggi della chat, poichè questo metodo non è propriamente corretto.

**Comment by Kasui92** [comment]
Abbiamo implementato la succitata modifica nella versione `dev`, in modo che possa essere compresa nelle future versioni.

**Comment by gianni10049** [comment]
Soluzione a commit:
51028ad35c54ffe78317d3a811f8d7429bd7fcc7
