### ISSUE TITLE
MySQli

### ISSUE THREAD

**Issue by birkolo90** [GDRCD/GDRCD#135]
ciao, scusate la rottura di scatole ma mi compare questo nuovo errore ora che ho configurato il file inc.php. non capisco dove devo intervenire

GDRCD MySQLi Error [File: index.php; Line: 35]
Error Code: 1146
Error String: Table 'my_onepiecerevolution.personaggio' doesn't exist

Error Detail: SELECT COUNT(nome) AS online FROM personaggio WHERE ora_entrata > ora_uscita AND DATE_ADD(ultimo_refresh, INTERVAL 4 MINUTE) > NOW()

**Comment by breakeryouko** [comment]
hai lanciato l'installer.php?

**Comment by birkolo90** [comment]
si lo lasciato, perche non doveo?

**Comment by breakeryouko** [comment]
pare che non sia andata a buon fine la creazione delle tabelle. Ti consiglio di entrare su PhpMyAdmin dal pannello di AlterVista e vedere se esiste la tabella personaggio, nel caso contrario cancella tutto e rilancia installer.php

**Comment by birkolo90** [comment]
sono sicuro che non c'è nessuna cartella su PhpMyAdmin, quindi cancello e vado a ricaricare tutto?

**Comment by breakeryouko** [comment]
allora non e' stato ancora lanciato l'installer. Vai su http://onepiecerevolution.altervista.org/installer.php in modo da creare il database

**Comment by birkolo90** [comment]
ok, mi ha creato il database, solo che quando entro sul sito mi da una pagina bianca  .-. grazie dell'aiuto sono ancora una frana!

**Comment by breakeryouko** [comment]
Su quale pagina? Index.php, main.php o altro?

**Comment by birkolo90** [comment]
Risolto, sembra che si sia caricato bene, anche se provo a entrare in registrazione mi dice index non trovata,scusami tanto ma sto uscendo fuori fase. E ora che me ne accorgo se modifico il css non mi si modifica

**Comment by breakeryouko** [comment]
Manda un link se possibile e vediamo che genere di errore hai. Cosi' non ho modo di aiutarti.
