### ISSUE TITLE
Bug invio messaggi

### ISSUE THREAD

**Issue by ardagdr** [GDRCD/GDRCD#136]
Ho riscontrato un bug al momento dell'invio dei messaggi privati. Al momento in cui si clicca per inviarlo infatti esce questa stringa:

`Parse error: syntax error, unexpected end of file in /membri2/sito/pages/messages/send_message.inc.php on line 61`

per sicurezza ho ricaricato le pagine di base così come si presentavano nel pacchetto pensando di aver fatto qualcosa io, ma il risultato è stato sempre questo.

**Comment by breakeryouko** [comment]
Non riesco a riprodurre l'errore

**Comment by kyurenai** [comment]
Lo fa anche a me (pacchetto 5.5 base). Basta cancellare l'ultima riga di codice (la 61) che riapre il <?php senza chiuderlo (?)

**Comment by ste-camp** [comment]
Il problema potrebbe essere legato alla versione di PHP usata o ad una configurazione specifica dell'installazione.
Togliere l'apertura di php alla fine non è corretto, perchè lasciare php aperto è una best practice per scrivere codice pulito.
Piuttosto io proverei ad aggiungere semplicemente un ritorno a capo dopo la riga 61, a volte alcuni programmi si arrabbiano se il file non termina con un newline

**Comment by gianni10049** [comment]
Chiusa, risposta abbastanza esaustiva.
