### ISSUE TITLE
Bug - skillsystem OFF

### ISSUE THREAD

**Issue by iloveireland** [GDRCD/GDRCD#142]
Buonasera :)
Uso GDRCD 5.2.
Ho impostato in config ['skillsystem']='OFF'; e mantenuto il sistema dadi.
Quando però lancio un semplice dado, mi va a sommare un valore X (che credo sia di una caratteristica).

In pratica invece di:
01:08 Test lancia 1d100: Risultato 85 
(che compare quando il skillsystem è impostato su ON ed è quello di cui ho bisogno)

La stringa in chat appare così:
01:18 Test usa : 7, dado 85, totale 92

Ho provato a guardare in ref_header e fare qualche prova ma ho solo peggiorato la situazione.

Ci sono consigli?
Grazie mille

**Comment by gianni10049** [comment]
Problema risolto:

Commit: e120adddd912ff0266ddf7a72bf7692c063f69c9
