### ISSUE TITLE
Bug recupero password

### ISSUE THREAD

**Issue by haruka13** [GDRCD/GDRCD#144]
Niente, la funzione nel file index.php non sembra andare. 

Restituisce errore "Impossibile eseguire", che poi è collegato al file del vocabolario e corrisponde, nel file index, al warning:

 $RP_response = gdrcd_filter('out', $MESSAGE['warning']['cant_do']);

Qualche idea su come si possa risolvere?

**Comment by breakeryouko** [comment]
È un errore dovuto al fatto che il campo email risulta criptato, vedo di rilasciare il bugfix appena possibile. Nel caso volessi farlo tu devi criptare nuovamente il valore email prima di confrontarlo nel database

**Comment by breakeryouko** [comment]
Prova a modificare questa riga


gdrcd_password_check($_POST['email'], $row['email'])

In


gdrcd_password_check(gdrcd_encript($_POST['email']), $row['email'])

**Comment by haruka13** [comment]
> 
> 
> È un errore dovuto al fatto che il campo email risulta criptato, vedo di rilasciare il bugfix appena possibile. Nel caso volessi farlo tu devi criptare nuovamente il valore email prima di confrontarlo nel database

Eh vorrei avere le conoscenze necessarie a farlo ^^'

Ho provato la soluzione che suggerivi, ma il problema rimane.

**Comment by Aikanairo** [comment]
magari lo fixo io se riesco a capire

<?php echo gdrcd_filter('out', $record['email']); ?>

mi potresti scrivere la sintassi per il decrypt

**Comment by Aikanairo** [comment]
se mi dai inicazioni provo a fixarlo io

`<?php echo gdrcd_filter('out', $record['email']); ?>`

coe dovrebbe avvenire il decrypt

**Comment by Aikanairo** [comment]
vorrei capire come effettuare il decrypt quanto meno per il player 

esiste la funzione di decrypt? ho visto solo la encript spulciando il codice

**Comment by ste-camp** [comment]
In realtà il bug non è più presente nell'ultima versione di GDRCD.
La correzione è stata effettuata nel commit 7c11e9f80ac0c9e8b14c6ea057167824364d13f3

**Comment by ste-camp** [comment]
> vorrei capire come effettuare il decrypt quanto meno per il player
> 
> esiste la funzione di decrypt? ho visto solo la encript spulciando il codice

Per rispondere a questa domanda: no, non esiste una funzione di decrypt perchè le email non sono criptate, ma sono memorizzate sotto forma di hash, che non sono proprio decriptabili.
