### ISSUE TITLE
Id_messaggio in altra tabella

### ISSUE THREAD

**Issue by Rander89** [GDRCD/GDRCD#145]
Ciao ragazzi, una domanda. Nella pagina insert di GDRCD 5.5, questo è il pezzo in cui un messaggio viene inserito nella tabella "messaggioaraldo":

[code]if($_POST['padre'] == -1) {
    $cond = ' araldo.id_araldo='.gdrcd_filter('num', $_POST['araldo']);
} else {
    $fields = ', MA.chiuso';
    $join = ' INNER JOIN messaggioaraldo AS MA ON MA.id_araldo=araldo.id_araldo ';
    $cond = " MA.id_messaggio=".gdrcd_filter('num', $_POST['padre'])." AND id_messaggio_padre=-1";
}

$thread = gdrcd_query("SELECT araldo.id_araldo, araldo.tipo, araldo.proprietari".$fields." FROM araldo ".$join.(! empty($cond) ? ' WHERE '.$cond : ''),'result');

if(gdrcd_query($thread, 'num_rows')) {
    $araldoData = gdrcd_query($thread, 'fetch');
    if(($araldoData['tipo'] == SOLORAZZA and ($_SESSION['id_razza'] == $araldoData['proprietari'] || $_SESSION['permessi'] >= MODERATOR)) || ($araldoData['tipo'] == SOLOGILDA and (strpos($_SESSION['gilda'],'*'.$araldoData['proprietari'].'*') !== false || $_SESSION['permessi'] >= MODERATOR)) || ($araldoData['tipo'] >= SOLOMASTERS and $_SESSION['permessi'] >= GAMEMASTER) || ($araldoData['tipo'] >= SOLOMODERATORS and $_SESSION['permessi'] >= MODERATOR) || ($araldoData['tipo'] == PERTUTTI) || ($araldoData['tipo'] == INGIOCO) || $_POST['padre'] == -1 or ($araldoData['chiuso'] != 1 || $_SESSION['permessi'] >= MODERATOR)) {
        //Solo se il thread non è chiuso
        gdrcd_query("INSERT INTO messaggioaraldo (id_messaggio_padre, id_araldo, titolo, messaggio, autore, data_messaggio, data_ultimo_messaggio ) VALUES (".gdrcd_filter('num', $_POST['padre']).", ".gdrcd_filter('num', $araldoData['id_araldo']).", '".gdrcd_filter('in', $_POST['titolo'])."', '".gdrcd_filter('in', $_POST['messaggio'])."', '".gdrcd_filter('in', $_SESSION['login'])."', NOW(), NOW())");[/code]

Avrei qui bisogno del vostro aiuto. Ho creato una nuova tabella (TableA) all'interno della quale ho un campo chiamato id_messaggio (che sarebbe l'id del messaggio in "messaggioaraldo").
L'inserimento dei dati funziona benissimo (i dati in TableA vengono caricati quando si flagga una casellina nella pagina composer), TRANNE il campo id_messaggio. Se io volessi estrarre l'id del messaggio inserito (caricato ottimamente nella tabella messaggioaraldo) e associarlo allo specifico campo di TableA, quale sarebbe la procedura?
Inserendo

[code]".gdrcd_filter('num', $_POST['padre'])."[/code]

Quel campo verrebbe riempito con -1 (valore per indicare l'apertura di un nuovo argomento e che nella tabella mesaggioaraldo ha un campo proprio chiamato id_messaggio_padre)

**Comment by Kasui92** [comment]
La procedura migliore sarebbe quella di prevedere, prima dell'inserimento nella tabella `messaggioaraldo`, quale sarà l'id_messaggio del nuovo record e quindi salvarlo in una variabile apposita che andrai ad utilizzare per l'accoppiamento con `TableA`.

Per fare una cosa del genere, puoi andare a recuperare l'ultimo ID della tabella `messaggioaraldo` (tramite SELECT query), salvarlo in una variabile, come $id_messaggio, e poi usarlo sia nella query del messaggio in `messaggioaraldo` che in quella di `TableA`.

**Comment by ste-camp** [comment]
Ma in realtà più che fare quel giro basterebbe chiamare
```
gdrcd_query($query, 'last_id')
```
dopo aver fatto la query che inserisce il record in `messaggioaraldo`.
Ti restituisce l'ID del messaggio inserito e ce l'hai a disposizione per fare l'inserimento in TableA

**Comment by gianni10049** [comment]
La risposta mi sembra più che esaustiva, quindi chiudo e nel caso se serve si sposta la discussione in Discussions e non in Issue.
