### ISSUE TITLE
Diverse difficoltà

### ISSUE THREAD

**Issue by Giulyz** [GDRCD/GDRCD#146]
Ciao a tutti. 
È passato parecchio tempo da quando ho programmato la mia ultima land e sono parecchio arruginita, anche perchè non sono esperta e quel poco che so, me lo sono insegnata da sola.

Adesso mi sono "ri-" appassionata al gdrcd e sto cercando di programmare una land con il nuovo pacchetto del gdrcd 5.5.1. 
Sto affrontando diversi "problemi" lungo il percorso che proprio non riesco a risolvere. Spero possiate darmi un consiglio così da capire esattamente dove sbaglio.

Nel database per esempio, caricando il gdrcd.5.5.1.sql,, volendo implentare alcuni dati nelle tabelle (value=car" nella tabella personaggi) mi si apre sempre l'errore nel default della data_esilio. Non importa come correggo quella tabella, non funziona nulla. Non mi permette di fare implementazioni in personaggio di alcun genere perchè mi mostra sempre lo stesso errore. 

Nei file, sto cercando di creare la sezione delle Tribù (sto cercando di programmare una land WOD), uso anche gli stessi dati, riscrivo le tabelle in merito ai parametri che voglio inserire, ma non mi funziona dandomi sempre l'errore del 1064. 

Dove sbaglio? 
Grazie in anticipo per i vostri suggerimenti!

**Comment by ste-camp** [comment]
Ciao,
il file .sql non fa più parte di GDRCD, ma è solo un backup della struttura del database; nessuna modifica apportata a quel file viene riportata sulla land dopo l'installazione, e non deve essere importato sul database.
Le modifiche alla struttura del database dovresti farle direttamente sullo strumento che ti fornisce il tuo hosting, dopo aver eseguito la procedura di installazione di GDRCD.

**Comment by Giulyz** [comment]
Oddio, ero così convinta che fosse tutto ancora con il database che non mi sono nemmeno fermata a leggere.
L'installazione è completa e adesso ritento. 
Grazie mille!!!
