### ISSUE TITLE
Collegamento css

### ISSUE THREAD

**Issue by Giulyz** [GDRCD/GDRCD#147]
Buonasera a tutti!
Sono di nuovo io con un altro quesito.
La land è in piedi e le implementazioni che ho fatto, funzionano perfettamente. Adesso però ho un problema con il css. Main.css e Chat.css in particolare, non rispondono, ne online ne in locale.
C'è  un errore da qualche parte che non vedo?
Grazie mille in anticipo!

**Comment by ste-camp** [comment]
Non è chiaro cosa intendi con "non rispondono".

I riferimenti ai css danno un errore HTTP? Se sì, quale?

Oppure i riferimenti restano in caricamento fino al timeout del browser?

O altro?

**Comment by Giulyz** [comment]
Sorry. Intendo dire che le modifiche che effettuo sul css, non compaiono in land. È come modificare a vuoto. Non mi dà nessun errore ne altro, è solo come se non avessi fatto nulla. 
Può essere un errore di collegamento?

**Comment by ste-camp** [comment]
Se stai modificando i file nella cartella /themes/nometema/*.css non dovresti avere problemi e le modifiche dovrebbero essere subito visibili. GDRCD5 non implementa nessun tipo di cache o bundling dei css.

Assicurati che il tuo browser stia refreshando la propria cache interna (in alcuni browser tipo chrome è possibile dirgli di non usare proprio la cache da una spunta negli strumenti per sviluppatori).
Sempre dagli strumenti per gli sviluppatori in genere puoi verificare i link dei css che sta caricando, per assicurarti che siano davvero quelli che stai modificando e puoi consultarne il contenuto.

Se il tuo sito remoto è su Altervista assicurati che le funzioni di cloudflare siano o disattivate o in modalità sviluppo.

Quando carichi i file sul tuo sito remoto assicurati di caricarli nella cartella corretta.

**Comment by Giulyz** [comment]
Non avevo proprio pensato al browser. 
Usavo Opera e non mi indicava nulla, mentre Firefox funziona perfettamente. 
Grazie mille per la spinta nella giusta direzione!!
