### ISSUE TITLE
Programmazione Tasto bacheca in iframe messaggi

### ISSUE THREAD

**Issue by ardagdr** [GDRCD/GDRCD#148]
Buongiorno, per via di problemi di estetica, mi ritrovo a dover cercare di modificare l'aspetto del pulsante della bacheca posto nell'iframe messaggi. Il cambiamento del pulsante è riuscito perfettamente da config.inc ma risulta particolarmente fastidiosa la scritta (Nuovo) al sopraggiungere di nuovi treadh e messaggi in bacheca. 
La domanda è: risulta possibile fare in modo che invece di far uscire la scritta (Nuovo) venga fuori un immagine come parametro $PARAMETERS['names']['private_message']['image_file_new'] ?

Fin adesso sono riuscito solo a sdoppiare il pulsante, ma non a creare una sequenza di codice tale che se c'è un nuovo messaggio mi compare solo il pulsante nuovo, e in caso di assenza torni quello normale.

(il riferimento è in messaggi.inc)
`           if($new_msg2['num'] > $new_msg['num']) {
                $new = true;
            }
        }
    }
    echo ($new) ? $PARAMETERS['text']['check_forum']['new'].' ' : '';

    if(empty ($PARAMETERS['names']['forum']['image_file']) === false) {
        //echo '<img src="../themes/'.$PARAMETERS['themes']['current_theme'].'/imgs/menu/'.$PARAMETERS['names']['forum']['image_file'].'" alt="'.gdrcd_filter('out',$PARAMETERS['names']['forum']['sing']).'" title=="'.gdrcd_filter('out',$PARAMETERS['names']['forum']['sing']).'" />';

        if(($PARAMETERS['names']['forum']['image_file_onclick']) === true) {
            $img_up = $PARAMETERS['names']['forum']['image_file'];
            $img_down = $PARAMETERS['names']['forum']['image_file'];
        } else {
            $img_up = $PARAMETERS['names']['forum']['image_file'];
            $img_down = $PARAMETERS['names']['forum']['image_file_onclick'];
        }

        echo '<script type="text/javascript"> if (document.images) { var forum_button1_up = new Image(); forum_button1_up.src = "../themes/'.$PARAMETERS['themes']['current_theme'].'/imgs/menu/'.$img_up.'"; var forum_button1_over = new Image(); forum_button1_over.src = "../themes/'.$PARAMETERS['themes']['current_theme'].'/imgs/menu/'.$img_down.'";} function forum_over_button() { if (document.images) { document["forum_buttonOne"].src = forum_button1_over.src;}} function forum_up_button() { if (document.images) { document["forum_buttonOne"].src = forum_button1_up.src}}</script>';

        echo '<a onMouseOver="forum_over_button()" onMouseOut="forum_up_button()" href="../main.php?page=forum"  target="_top"><img src="../themes/'.$PARAMETERS['themes']['current_theme'].'/imgs/menu/'.$PARAMETERS['names']['forum']['image_file'].'" alt="'.gdrcd_filter('out',$PARAMETERS['names']['forum']['plur']).'" title="'.gdrcd_filter('out', $PARAMETERS['names']['forum']['plur']).'" name="forum_buttonOne" /></a>';

    } else {
        echo gdrcd_filter('out', $PARAMETERS['names']['forum']['sing']);
    }
    echo '</a></div>';
}`

**Comment by Kasui92** [comment]
Ho provato a risolvere il tuo problema allineando la gestione del pulsante delle Bacheche con quello dei Messaggi. 
In questo modo, non dovresti avere molte difficoltà a rimuovere la scritta Nuovo e ad impostare una immagine per il pulsante delle Bacheche in caso di nuovi Topic.

**Comment by gianni10049** [comment]
Per me con i commit:
cb971db66bb286ca5aaa22cd348f1ccec1a51a85
c2e61767bbff02b24cd0a5d7335f63626a0a44e6
8559e910378c25fe8fe29a8e131346544c4219a3

Risulta risolto, quindi chiudo l'issue e nel caso se ne apre uno nuovo con il problema eventuale, data la mancanza di risposta.
