### ISSUE TITLE
Primo login e lista presenti

### ISSUE THREAD

**Issue by musicamus4** [GDRCD/GDRCD#153]
Al primo login il personaggio non compare nella lista dei presenti online insieme a tutti gli altri. Sembra che si risolva sloggando e riloggando.
Il problema è stato riscontrato in un gioco che usa la 5.5, ma pare che si tratti di un bug "nativo" e ricorrente, che prescinde dalla singola piattaforma.

**Comment by Dyrr** [comment]
con quasi tutta certezza il problema deriva da una impostazione nel file installer.php nella query che inizia a riga 322

```
        gdrcd_query("CREATE TABLE personaggio (
            nome varchar(20) NOT NULL default '',
            cognome varchar(50) NOT NULL default '-',
            pass varchar(60) NOT NULL default '',
            ultimo_cambiopass datetime DEFAULT NULL,
            data_iscrizione datetime default NULL,
            email varchar(60) default NULL,
            permessi tinyint(1) default '0',
            ultima_mappa int(4) NOT NULL default '1',
            ultimo_luogo int(4) NOT NULL default '-1',
            esilio date default NULL,
            data_esilio date NOT NULL default '2009-07-01',
            motivo_esilio varchar(255) default NULL,
            autore_esilio varchar(20) default NULL,
            sesso char(1) default 'm',
            id_razza int(4) default '1000',
            descrizione text,
            affetti text,
            stato varchar(255) default 'nessuna',
            online_status varchar(100) DEFAULT NULL,
            disponibile tinyint(1) NOT NULL default '1',
            url_img varchar(255) default 'imgs/avatars/empty.png',
            url_img_chat varchar(255) NOT NULL DEFAULT ' ',
            url_media varchar(255) default NULL,
            blocca_media binary(1) NOT NULL DEFAULT '0',
            esperienza decimal(14,5) default '0',
            car0 int(4) NOT NULL default '5',
            car1 int(4) NOT NULL default '5',
            car2 int(4) NOT NULL default '5',
            car3 int(4) NOT NULL default '5',
            car4 int(4) NOT NULL default '5',
            car5 int(4) NOT NULL default '5',
            salute int(4) NOT NULL default '100',
            salute_max int(4) NOT NULL default '100',
            data_ultima_gilda datetime NOT NULL default '2009-07-01 00:00:00',
            soldi int(11) default '50',
            banca int(11) default '0',
            ultimo_stipendio date NOT NULL default '2009-07-01',
            last_ip varchar(60) default NULL,
            is_invisible tinyint(1) NOT NULL default '0',
            ultimo_refresh datetime default NULL,
            ora_entrata datetime default NULL,
            ora_uscita datetime default NULL,
            posizione int(4) NOT NULL default '1',
            ultimo_messaggio bigint(20) NOT NULL default '0',
            PRIMARY KEY  (nome),
            KEY IDRazza (id_razza),
            KEY Esilio (esilio)
        ) ENGINE=MyISAM DEFAULT CHARSET=utf8;");
```
e precisamente il punto è ora_uscita datetime default **NULL**
quando viene fatto il primo ingresso il confronto fra la data di entrata e la data di uscita sballa e fa sembrare il pg invicibile, quando esci viene aggiornatata e quindi al primo funziona tutto.
Per risolverlo andrebbe:
- per chi ha gia installato il gdrcd andare nel phpmyadmin e cambiare il valore di default del campo: **ora_uscita** con un qualsiasi data e ora antecedente a quella odierna;
- per chi non lo ha ancora installato va corretto il file installer.php correggendo quel valore di default allo stesso modo di come scritto sopra. 
  ,

**Comment by Kasui92** [comment]
@Dyrr 
Non potrebbe avere senso lasciare il valore default del campo a NULL sul DB e, nella costruzione della lista dei presenti, aggiungere una qualche condizione che possa raccogliere anche i nuovi iscritti (ossia quelli con ora_uscita  = NULL)?

**Comment by Kasui92** [comment]
@musicamus4 
Il problema è legato solo alla lista dei Presenti (quella estesa, per intenderci) o anche a quella solitamente contenuta nei riquadri a lato delle chat? L'ingresso dell'utente viene però segnalato?

**Comment by Kasui92** [comment]
Abbiamo seguito le indicazioni di @Dyrr ed abbiamo impostato un valore di default per il campo personaggio.ora_uscita, in modo da non far fallire più i controlli per il primo accesso dell'utente. 

Qui sotto la query da eseguire per allineare i GDR già attivi con la correzione succitata:

```
ALTER TABLE personaggio CHANGE ora_uscita ora_uscita datetime NOT NULL default '2009-07-01 00:00:00';
```

**Comment by gianni10049** [comment]
La soluzione a questo issue e' al commit:
3316afe06cd27ebec75a2c73634cc3522b2a1f40

Se si riscontrano altri problemi si crea una nuova issue o si fa confusione, quindi per ora chiudo questa.
