### ISSUE TITLE
Topic forum

### ISSUE THREAD

**Issue by strangerbee** [GDRCD/GDRCD#154]
Ciao, non so se è già stato implementato nell'ultima versione disponibile ma nel caso in cui non lo fosse, sarebbe possibile applicare questi fix al forum? Grazie.

1. Un utente può vedere solo le sezioni a cui è abilitato (es. no corporazioni a cui non fa parte)
2. I post nelle sezioni si ordinano in ordine di ultima risposta (esclusi quelli pinnati che rimangono in alto)

Mi pare che sulla versione, ancora sulla 5, non fosse possibile ma non so se è stato implementato in qualche pacchetto della 5.x

**Comment by Kasui92** [comment]
Innanzitutto, ti ringraziamo per i suggerimenti che ci hai dato! 

Veniamo ai Fix:
1) Abbiamo implementato il fix nel commit [bf0efa5](https://github.com/GDRCD/GDRCD/commit/bf0efa59b28cf4bf561bb9e5ab5abacf35619676), dove puoi trovare tutte le modifiche da applicare per disabilitare la visione delle bacheche a chi non è autorizzato a vederle; questa modifica sarà già presente nella prossima versione di GDRCD
2) Abbiamo eseguito diverse verifiche su questo fix e ci risulta che i vari Forum hanno i topic già ordinati per la data dell'ultima risposta inviata (contando il messaggio iniziale del topic come risposta ), quindi è già stata implementato questo fix nell'ultima versione di GDRCD (la versione 5.5.1, intendo).
