### ISSUE TITLE
Bug modifica e-mail

### ISSUE THREAD

**Issue by Jansna** [GDRCD/GDRCD#159]
Il problema si trova nella pagina scheda_gst.inc.php, alla riga 16-17

gdrcd_query("UPDATE personaggio SET **email = '" . gdrcd_filter('in', $_POST['modifica_email']) . "'**

La parte evidenziata dovrebbe essere:
**email = '" . gdrcd_filter('in', gdrcd_encript($_POST['modifica_email'])) . "'**

Per far sì che la mail venga criptata di nuovo quando aggiornata.

**Comment by Kasui92** [comment]
La soluzione da te proposta è stata adottata nel commit [cc55093](https://github.com/GDRCD/GDRCD/commit/cc55093408ebd23d369b29c9bb8588eb7ebaba54). Inoltre abbiamo migliorato la leggibilità della query di modifica.

Grazie!
