### ISSUE TITLE
Bug conteggio presenti

### ISSUE THREAD

**Issue by Jansna** [GDRCD/GDRCD#160]
Più che un bug è una questione che viene spesso "sfruttata" dagli utenti per capire se ci sono master invisibili al momento. 
Il problema si trova a riga 238 della pagina presenti.inc.php

`$record = gdrcd_query("SELECT COUNT(*) AS numero FROM personaggio WHERE (personaggio.ora_entrata > personaggio.ora_uscita AND DATE_ADD(personaggio.ultimo_refresh, INTERVAL 4 MINUTE) > NOW())");`

La query non verifica che il personaggio sia invisibile e restituisce di conseguenza il numero di utenti loggati, comprensivi di quelli invisibili. 

La query corretta dovrebbe essere:

`$record = gdrcd_query("SELECT COUNT(*) AS numero FROM personaggio WHERE (personaggio.ora_entrata > personaggio.ora_uscita **AND personaggio.is_invisibile = 0** AND DATE_ADD(personaggio.ultimo_refresh, INTERVAL 4 MINUTE) > NOW())");`

**Comment by Kasui92** [comment]
La soluzione da te proposta è stata adottata nel commit [a5cd658](https://github.com/GDRCD/GDRCD/commit/a5cd658118692f1813b09a6f118246f7f22c32ee) .
Grazie!
