### ISSUE TITLE
Bug "invisibilità" nei presenti

### ISSUE THREAD

**Issue by Jansna** [GDRCD/GDRCD#161]
Bug estremamente popolare (nel senso che viene abusato costantemente) e mai corretto di gdrcd.
Capita a volte quando ci si connette anche da cellulare che si creino problemi di sessione, cioè la sessione resta aperta anche se si è effettuato il logout. Questo chiaramente manda in palla il sistema di conteggio dei presenti:

Per esempio, in presenti.inc.php, riga 154

`$query = "SELECT personaggio.nome, personaggio.cognome, personaggio.permessi, personaggio.sesso, personaggio.id_razza, razza.sing_m, razza.sing_f, razza.icon, personaggio.disponibile, personaggio.is_invisible, mappa.stanza_apparente, mappa.nome as luogo FROM personaggio LEFT JOIN mappa ON personaggio.ultimo_luogo = mappa.id LEFT JOIN razza ON personaggio.id_razza = razza.id_razza WHERE (personaggio.ora_entrata > personaggio.ora_uscita AND DATE_ADD(personaggio.ultimo_refresh, INTERVAL 4 MINUTE) > NOW()) AND personaggio.ultimo_luogo = " . $_SESSION['luogo'] . " AND personaggio.ultima_mappa= " . $_SESSION['mappa'] . " ORDER BY personaggio.is_invisible, personaggio.ultimo_luogo, personaggio.nome";`

**personaggio.ora_entrata > personaggio.ora_uscita** fa sì che i pg che incappano in questo bug diventino invisibili perché non rispettano questa condizione. Infatti l'orario di uscita è maggiore di quello di entrata, perché i pg appaiono come se fossero a tutti gli effetti sloggati.

Personalmente non ho trovato una soluzione definitiva alla cosa, ma ho creato una "soluzione tampone" per evitare che la gente si approfitti in chat di questo bug per spiare gli altri (cosa che accade al momento nel 90% delle land gdrcd, perché sto bug lo conoscono tutti). 

ref_header, riga 15:
`if ((gdrcd_filter_get($_REQUEST['chat']) == 'yes') && (empty($_SESSION['login']) === false)) {`

Nella condizione aggiungerei il controllo **personaggio.ora_entrata > personaggio.ora_uscita**. Io ho fatto così:

```
	$hour = gdrcd_query("SELECT ora_entrata, ora_uscita FROM personaggio WHERE nome = '".$_SESSION['login']."'" );
if((gdrcd_filter_get($_REQUEST['chat'])=='yes')&&(empty($_SESSION['login'])===FALSE)&&($hour['ora_entrata']>$hour['ora_uscita'])) {
```

Ovviamente sarebbe meglio risolvere il problema alla radice, ma temo che andrebbe riscritta la logica con cui sono gestiti i presenti ora.

**Comment by gianni10049** [comment]
Il problema non nasce da li', ma da un problema nel controllo del login.

Risolto con il commit 77fb6510a53d9d1fe990fe19e2cd7bca3598ba7d
