### ISSUE TITLE
Parse error: syntax error, unexpected '}' in pages/gestione_razze.inc.php

### ISSUE THREAD

**Issue by annamereu** [GDRCD/GDRCD#169]
Nel file pages/gestione_razze.inc.php alla riga 224 è presente un errore di sintassi ed è presente ad installazione nuova prelevata da git. 
 
![image](https://user-images.githubusercontent.com/74818550/135842713-64d913c2-8eac-468c-b96a-a69b00e56328.png)

In questo punto andrebbe semplicemente aggiunto uno spazio dopo <?php 

![image](https://user-images.githubusercontent.com/74818550/135842764-296c4830-e86f-447b-8041-e0f741280577.png)

Ho visto che è un problema segnato diverse volte sul forum, e veramente molto easy da risolvere

**Comment by Kasui92** [comment]
L'errore da te segnalato è stato risolto con il commit [0f4501e](https://github.com/GDRCD/GDRCD/commit/0f4501e28fe306b6d548b81d26df27a3a6a74619). La soluzione sarà totalmente integrata con la prossima versione di GDRCD, che verrà rilasciata a breve. 

Hai fatto comunque bene a segnalare e ti ringraziamo per il contributo!
