### ISSUE TITLE
Mancata ricezione email di sistema

### ISSUE THREAD

**Issue by musicamus4** [GDRCD/GDRCD#183]
Ho provato ad iscrivere un personaggio ma al termine della procedura non mi è stata inviata alcuna mail (ho controllato nello spam e ho aspettato più di un'ora per essere sicura che non fosse solo una questione di lentezza del sistema). Ho provato ad effettuare la procedura di recupero password, ma anche in quel caso non ho ricevuto la mail di recupero.
Sono sicura di aver inserito un indirizzo email valido e correttamente digitato.

Dispositivo: Windows 10
Browser: Chrome
Gestore mail: Gmail

**Comment by gianni10049** [comment]
Il problema purtroppo nasce da una errata configurazione del server su cui gira il sito di prova, quindi non e' un bug del codice, che su un normale shared host funziona senza alcun problema.

Chiudo la issue per questo motivo.
