### ISSUE TITLE
Meteo Luna

### ISSUE THREAD

**Issue by laenre** [GDRCD/GDRCD#19]
Scusate, mi chiedevo se fosse possibile aggiungere direttamente alla nuova release la possibilità di avere il meteo luna incorporato! Esiste una patch a parte, lo so, ma perchè non aggiungerla direttamente assieme al classico meteo? E' possibile? Grazie mille, complimenti per quello che state facendo e buon lavoro!

**Comment by breakeryouko** [comment]
chiudo per inattività.
