### ISSUE TITLE
[BUG] - {CSS-Tabella Diario}

### ISSUE THREAD

**Issue by Nuvolagdr** [GDRCD/GDRCD#194]
**Describe the bug**
Non è proprio un bug ma un'intabellamento sballato.
Nel diario una volta inserita la prima pagina, l'effetto della lista è confusionario. O lo lasciate così e se lo sistemano gli altri o lo aggiustate.

**To Reproduce**
1-Scheda
2-Menu diario
3-Inserisci pagina diario
4-Torna alla pagina diario

**Expected behavior**
Spazi tabelle-css (grafica)

**Screenshots**
https://i.ibb.co/L59MJ1w/diario.png

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Firefox 
 - Version aggiornato

**Comment by gianni10049** [comment]
Dato un po' di stile alle tabelle del diario, effettivamente erano confusionarie.

commit: 9397992abd808dc5e6ff460e5657bbff71b185fc
