### ISSUE TITLE
[BUG] - Campo storia mancante nel database

### ISSUE THREAD

**Issue by annamereu** [GDRCD/GDRCD#222]
**Describe the bug**
Mancata creazione del campo "storia" in database nella tabella "personaggio"

**To Reproduce**
1. effettuare una nuova installazione della versione 5.6
2. recarsi nella scheda, alla sezione "modifica" per vedere l'errore:
```
GDRCD MySQLi Error [File: scheda_modifica.inc.php; Line: 138]
Error Code: 1054
Error String: Unknown column 'storia' in 'field list'

Error Detail: SELECT descrizione, storia, affetti, cognome, online_status, url_img, url_img_chat, url_media, blocca_media, stato, salute FROM personaggio WHERE nome='personaggioprova'
```

**Comment by gianni10049** [comment]
Problema risolto col commit hotfix f8927a7eaa2205b54d7e1726e2c03881548ced41

Chiudo.
