### ISSUE TITLE
[BUG] - Mancanza tabella diario 

### ISSUE THREAD

**Issue by Kasui92** [GDRCD/GDRCD#224]
In fase di installazione di GDRCD, non viene creata la tabella `diario` all'interno del database e questo genera successivamente un errore MySQL all'interno del software, nelle pagine della sezione Diario della scheda del Personaggio. 

>GDRCD MySQLi Error [File: index.inc.php; Line: 38]
Error Code: 1146
Error String: Table 'my_name.diario' doesn't exist
Error Detail: SELECT id, data, titolo, testo, visibile FROM diario WHERE personaggio='Staff' ORDER BY data DESC

**Comment by gianni10049** [comment]
Risolto col commit f8927a7eaa2205b54d7e1726e2c03881548ced41.

Chiudo.
