### ISSUE TITLE
[BUG] - Errore in Giocate registrate

### ISSUE THREAD

**Issue by Kasui92** [GDRCD/GDRCD#225]
Aprendo la scheda personaggio e cliccando in Giocate Registrate esce il seguente errore:

>GDRCD MySQLi Error [File: index.inc.php; Line: 71]
Error Code: 1055
Error String: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'Sqlxxxxxxx_x.segnalazione_role.data_inizio' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Error Detail: SELECT YEAR(data_inizio) as year FROM segnalazione_role WHERE mittente = 'Super' GROUP BY YEAR(data_inizio) ORDER BY data_inizio DESC

**Comment by Kasui92** [comment]
@Jansna 
L'opzione `sql_mode=only_full_group_by`  è abbastanza rognosa, soprattutto quando si va ad agire su query scritte in plain dove bisogna sempre assicurarsi che tutto sia molto standardizzato. Probabilmente, la query in questione va riscritta meglio sotto il punto di vista del GROUP BY.

**Comment by gianni10049** [comment]
Risolto col commit hotfix 596ff2c081bc2e809f1b5d631672f0a679b216fb

Chiudo.
