### ISSUE TITLE
[BUG] - {POSTA}

### ISSUE THREAD

**Issue by Khalesa** [GDRCD/GDRCD#236]
**Describe the bug**
Istallato il gdr cd se mando un messaggio a pg test sparisce la scritta messaggi e riappare solo se dal db cancello il messaggio se l'invio a me stesso cioè il pg Super si apre in automatoco la pagina dei messaggi, sparisce sempre la scritta messaggi dal box se se apro il messaggio riappare.
Potreste aiutarmi al momento nel forum di gdr on line non ho visto nulla a  riguardo.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Kasui92** [comment]
Provo a capire nel dettaglio l'anomalia che ti si presenta:
la scritta Messaggi nel menù a lato (presumo) ti sparisce quando provi ad inviare un messaggio all'utente Test. Riappare questa scritta SOLO quando cancelli il messaggio da DB. Se invii un messaggio a te stesso questa appare, ma ti apre in automatico la pagina dei messaggi e quindi, aprendola, questa scompare. 

La scritta, di per sè, è presente al momento della prima installazione?
Quando ricevi un messaggio, essa diventa in grassetto e ti segnala i messaggi non letti?

Perchè mi viene da pensare che probabilmente è stato fatto qualcosa nella configurazione dell'engine.

**Comment by Khalesa** [comment]
Si la scrittta all'istallazione è regolare.
Se test o super mandano un messaggio scompare e non si può accedere alla posta se provo con super a mandarlo a super stesso mi si apre in automatico la posta nel schermata principale (main) e sparisce la scritta, quindi se apro il messaggio riappare la scritta "pulsante" regolarmente sul lato.
Chiedo scusa se non sono riuscito ad essere abbastanza chiaro

**Comment by Kasui92** [comment]
Quale versione di GDRCD utilizzi?

**Comment by Khalesa** [comment]
5.6.0.1 scaricata da gdr on line

**Comment by Kasui92** [comment]
Per caso hai modificato il file **config.inc.php** compilando la variabile di configurazione **$PARAMETERS['names']['private_message']['image_file_new']** ?

**Comment by Khalesa** [comment]
Allora nella versione della land che sto montando si no inserito l'immg ma nella versione che tengo vergine per fare le prove no ed il difetto lo fa in entrambi i casi, se vuoi posso provare a reistallare il gdr cd e vedo se continua a fare il problema, dimmi tu come fare ?
grazie mille :)

**Comment by Kasui92** [comment]
Per il momento non occorre, vediamo di sbatterci la testa e capire l'anomalia.
Sempre parlando della variabile **$PARAMETERS['names']['private_message']['image_file_new']** in config.inc.php, come l'hai valorizzata in quello senza immagine?

**Comment by Khalesa** [comment]
$PARAMETERS['names']['private_message']['image_file_new'] = 'Messaggi_c.png'; //immagine nuovi messaggi

te la copio
Ma questo difetto non risulata a nessun altro se lo metti tu su un data base non te lo fa perchè se lo fa solo a me allora devo capire che ho combinato conviene che ripeto tutto d'accapo, la versione del gdr on line è l'ultima la migliore ecc ecc ?

**Comment by Khalesa** [comment]
ah spe non avevo letto bene, sta cosa mi sta facendo scervellare sto provando pure io a fare prove
 la versione senza immg è rimasta invariata come in origine

**Comment by Kasui92** [comment]
Se provi a mettere:
`$PARAMETERS['names']['private_message']['image_file_new'] = ''; //immagine nuovi messaggi`
ti compare la scritta MESSAGGI[X] (dove X è il numero di messaggi ricevuti), giusto?

**Comment by Khalesa** [comment]
In verità non mi compare affatto nella versione precedente 5.6 che poi ho eliminato per passare a questa lo faceva di darmi il numero dei messaggi su messaggi ed in bacheca.

ho messaggi senza che appaia nulla cioè Messaggi senza [x]

**Comment by Kasui92** [comment]
In grassetto nero o con il colore normale?

**Comment by Khalesa** [comment]
allora quando c'è il messaggio in bacheca ho notato prima diventa grassetto nero se no la scritta non è in grassetto

**Comment by Khalesa** [comment]
non posso vederlo su messaggi perchè sparisce, ma quando messaggi è normale cioè senza messaggi in arrivo è senza grassetto

**Comment by Kasui92** [comment]
Ok, quindi il motivo per cui scompare è legato all'immagine. Probabilmente non trova il percorso corretto dell'immagine. 
L'immagine che avevi messo, ossia 'Messaggi_c.png' deve essere salvata su GDRCD nel percorso:
/themes/{CARTELLA_TEMA}/imgs/menu/ 

Se provi a salvare lì e ripopoli la variabile così:
`$PARAMETERS['names']['private_message']['image_file_new'] = 'Messaggi_c.png'; //immagine nuovi messaggi`

Ti compare l'immagine?

**Comment by Khalesa** [comment]
themes/advanced/imgs/menu/
 così è salvata

per cartella tema intendi una cartella che ci dovrebbe esser e m'è sfuggita ?

ma il problema è che sulla versione vergine che non ha l'immg scopare la scritta Messaggi che c'è di base

**Comment by Kasui92** [comment]
Ma nella versione base, il parametro **$PARAMETERS['names']['private_message']['image_file_new']** è valorizzato?

**Comment by Khalesa** [comment]
No no è come in originale

**Comment by Khalesa** [comment]
per sicurezza adesso dalla db vergine cancello tutto e reinstallo tutto ma nella tua versione di base sta cosa non succede ?

**Comment by Kasui92** [comment]
Ammetto di no.

**Comment by Khalesa** [comment]
e allora vedo io riscarico di nuovo il gdr cd faccio tutto da capo

**Comment by Khalesa** [comment]
ti aggiorno appena fatto

**Comment by Khalesa** [comment]
Nulla uguale posso darti il link entri tu con super e vedi come fa ?

**Comment by Kasui92** [comment]
Nessun problema!

**Comment by Khalesa** [comment]
http://officinagdr.altervista.org/

questo è dove faccio le prove, ho cancellato tutto anche se era intonso ho scaricato di nuovo il gdr cd da gdr on line ho caricato tutto e fa lo stesso entra con super e mandati un messaggio e guarda come ti sparisce la scritta messaggia dal box a sinistra se apri o concelli il messaggio riappare

**Comment by Khalesa** [comment]
Hai visto ? Hai idea di cosa possa essere?

**Comment by Kasui92** [comment]
Scovato l'errore!
Si tratta di una anomalia nei parametri di AudioController. Questa l'abbiamo già corretta in questo commit, ma è ancora nel branch `hotfix` ([https://github.com/GDRCD/GDRCD/commit/53a1232d97ad7f5af0c149713497e7ae20e3fa85](qui) il dettaglio del commit con le relative correzioni ).

Potresti provare ad applicare la correzione e a verificare se tutto torna a funzionare?

**Comment by Khalesa** [comment]
ah era quello io l'ho vista ma immagginando che era sull'audio non mi tornava  provo e ti dico 
grazie

**Comment by Khalesa** [comment]
fatto devo sostituire la riga verde a quella rosa giusto ?

**Comment by Khalesa** [comment]
fatto funziona pare  
grazie
 ma se metto l'immg poi appare sempre il numero a fianco ? o per mantenere quell uso non mi conviene mettere l'immg?

**Comment by Kasui92** [comment]
> fatto funziona pare  
> grazie
>  ma se metto l'immg poi appare sempre il numero a fianco ? o per mantenere quell uso non mi conviene mettere l'immg?
> 

Se metti la immagine, il numero dei messaggi non letti non compare nel box. Lo puoi inserire volendo, la variabile da usare è la stessa che si trova nella parte dedicata alla voce scritta nel box.

**Comment by Khalesa** [comment]
Grazie mille davvero, stavo diventado scemo a capire cosa succedeva, se dovessi avere altri problemi posso s crivere qui invece che in gdr on line ho anche qualche suggerimento da dare poi con calma su cose che si potrebbero implementare :)

**Comment by Kasui92** [comment]
Perfetto!
Anche per noi sono meglio le issues come metodo di correzione anomalie e se hai proposte o migliorie siamo tutt'orecchie! 

Se preferisci, abbiamo anche un Server Discorso ufficiale che usiamo per queste esigenze.

Qui il Link:
[https://discord.gg/TcDXrcQD]

**Comment by Khalesa** [comment]
Grazie mille ancora sei stato prezioso! :)
