### ISSUE TITLE
[BUG] - {Login contemporaneamente con lo stesso pg da due browser diversi su MAC}

### ISSUE THREAD

**Issue by Pumbaa49** [GDRCD/GDRCD#237]
**Describe the bug**
Premetto che uso Mac e chi usa Windows non riscontra questo problema.

Riesco a connettermi alla stessa land, con lo stesso PG, sia su Chrome che su Firefox contemporaneamente. 
Ho la possibilità di entrare in due chat diverse e di scrivere su entrambe contemporaneamente e non vengo sloggata da nessuno dei due browser. Nemmeno quando avviene il refresh automatico o manuale.

Non compare nemmeno il messaggio di errore durante la fase di login.

**To Reproduce**
Aprire Firefox e loggare in land, poi aprire chrome e loggare anche da lì. 

**Expected behavior**
//

**Screenshots**
//

**Desktop (please complete the following information):**
 - OS: MacOS Sierra versione 10.12.6
 - Browser-Firefox e Chrome ultima versione

**Smartphone (please complete the following information):**
//

**Additional context**
//

**Comment by gianni10049** [comment]
Versione: 5.4.1

**Comment by gianni10049** [comment]
Fix risolto nelle versioni successive, chiudo.
