### ISSUE TITLE
[BUG] - {title} frame messaggi comprende anche la bacheca

### ISSUE THREAD

**Issue by Lucyfer93** [GDRCD/GDRCD#238]
Salve a tutti ragazzi, sto lavorando su gdrcd 5.5

$PARAMETERS['right_column']['box']['frame_messaggi']['page'] = 'frame_messaggi';

questo parametro di fileconfig.php unisce insieme ai messaggi anche la bacheca.
E' ore che mi scervello per capire come eliminare la parte della bacheca, ma non riesco a capirlo.
Qualcuno sa dove devo andare a mettere le mani?
Vorrei rimanere su gdrcd 5.5 perchè ormai ho modificato parecchia roba

**Comment by gianni10049** [comment]
Ciao, devi togliere il link dalla pagina frame_messaggi.inc.php che riporta alla bacheca, se la domanda é come togliere la scritta che porta alla bacheca dal frame dei messaggi.

Nel caso non fosse questo, se riesci a spiegarmi meglio , provo ad essere più preciso!

**Comment by Lucyfer93** [comment]
> Ciao, devi togliere il link dalla pagina frame_messaggi.inc.php che riporta alla bacheca, se la domanda é come togliere la scritta che porta alla bacheca dal frame dei messaggi.
> 
> Nel caso non fosse questo, se riesci a spiegarmi meglio , provo ad essere più preciso!

Si, intendevo togliere la scritta bacheca dal link dei messaggi! Perché la bacheca è gia presente nel box del menu utente.

Il codice di frame_messaggi.inc.php è il seguente:

<?php /*Frame del box con il link alle bacheche e ai messaggi */ ?>
<iframe src="pages/messaggi.inc.php?ref=30" class="iframe_messaggi" allowtransparency="true" frameborder="0"
        scrolling="no">
    <p><?php gdrcd_filter_out(print $MESSAGE['errors']['can_t_load_frame']) . ' (http://' . $PARAMETERS['info']['site_url'] . '/pages/messaggi.inc.php'; ?></p>
</iframe>



Non capisco cosa devo rimuovere

**Comment by annamereu** [comment]
Nella pagina che fa riferimento il frame, la pages/messaggi.inc.php, dovresti poter togliere i riferimenti alla bacheca. 
Il primo if (dalla riga 14 alla 50 in teoria sul mio editor) riguarda proprio il check della bacheca. 
```
if($PARAMETERS['mode']['check_forum'] === 'ON') {
    echo '    <div class="messaggio_forum"><a href="../main.php?page=forum" target="_top">';
    $new = false;
    $result = gdrcd_query("SELECT id_araldo, nome, tipo, proprietari FROM araldo ORDER BY tipo, nome", 'result');
    while($row = gdrcd_query($result, 'fetch')) {
        if(($row['tipo'] <= PERTUTTI) || (($row['tipo'] == SOLORAZZA) && ($_SESSION['id_razza'] == $row['proprietari'])) || (($row['tipo'] == SOLOGILDA) && (strpos($_SESSION['gilda'], '*'.$row['proprietari'].'*') != false)) || (($row['tipo'] == SOLOMASTERS) && ($_SESSION['permessi'] >= GAMEMASTER)) || ($_SESSION['permessi'] >= MODERATOR)) {
            $new_msg = gdrcd_query("SELECT COUNT(id) AS num FROM araldo_letto WHERE araldo_id = ".$row['id_araldo']." AND nome = '".$_SESSION['login']."';");

            $new_msg2 = gdrcd_query("SELECT COUNT(id_messaggio) AS num FROM messaggioaraldo WHERE id_araldo = ".$row['id_araldo']." AND id_messaggio_padre = -1");

            if($new_msg2['num'] > $new_msg['num']) {
                $new = true;
            }
        }
    }
    echo ($new) ? $PARAMETERS['text']['check_forum']['new'].' ' : '';

    if(empty ($PARAMETERS['names']['forum']['image_file']) === false) {
        //echo '<img src="../themes/'.$PARAMETERS['themes']['current_theme'].'/imgs/menu/'.$PARAMETERS['names']['forum']['image_file'].'" alt="'.gdrcd_filter('out',$PARAMETERS['names']['forum']['sing']).'" title=="'.gdrcd_filter('out',$PARAMETERS['names']['forum']['sing']).'" />';

        if(($PARAMETERS['names']['forum']['image_file_onclick']) === true) {
            $img_up = $PARAMETERS['names']['forum']['image_file'];
            $img_down = $PARAMETERS['names']['forum']['image_file'];
        } else {
            $img_up = $PARAMETERS['names']['forum']['image_file'];
            $img_down = $PARAMETERS['names']['forum']['image_file_onclick'];
        }

        echo '<script type="text/javascript"> if (document.images) { var forum_button1_up = new Image(); forum_button1_up.src = "../themes/'.$PARAMETERS['themes']['current_theme'].'/imgs/menu/'.$img_up.'"; var forum_button1_over = new Image(); forum_button1_over.src = "../themes/'.$PARAMETERS['themes']['current_theme'].'/imgs/menu/'.$img_down.'";} function forum_over_button() { if (document.images) { document["forum_buttonOne"].src = forum_button1_over.src;}} function forum_up_button() { if (document.images) { document["forum_buttonOne"].src = forum_button1_up.src}}</script>';

        echo '<a onMouseOver="forum_over_button()" onMouseOut="forum_up_button()" href="../main.php?page=forum"  target="_top"><img src="../themes/'.$PARAMETERS['themes']['current_theme'].'/imgs/menu/'.$PARAMETERS['names']['forum']['image_file'].'" alt="'.gdrcd_filter('out',$PARAMETERS['names']['forum']['plur']).'" title="'.gdrcd_filter('out', $PARAMETERS['names']['forum']['plur']).'" name="forum_buttonOne" /></a>';

    } else {
        echo gdrcd_filter('out', $PARAMETERS['names']['forum']['sing']);
    }
    echo '</a></div>';
}
```
Rimuovendo (anche se ti consiglio di commentarlo) questa parte dovresti teoricamente vedere solo il box dei messaggi

**Comment by annamereu** [comment]
ottimo :)
per le immagini, si trovano nel file config.inc.php. Prova a cercare una di queste righe, dovresti trovarlo:

```
$PARAMETERS['names']['private_message']['image_file'] = ''; //immagine del link ai messaggi
$PARAMETERS['names']['private_message']['image_file_onclick'] = ''; //immagine al passaggio del mouse dei messaggi
$PARAMETERS['names']['private_message']['image_file_new'] = ''; //immagine nuovi messaggi
```
