### ISSUE TITLE
Creazione pannello Utenti per incremento caratteristiche

### ISSUE THREAD

**Issue by Lucyfer93** [GDRCD/GDRCD#244]
Salve a tutti, premetto che ho il sistema "abilità" disattivato nel gdr perchè non è quello che cerco.
Ho creato due nuove stats (attacco e difesa)
Ho anche un valore simile all'esperienza (che però, a differenza di questa, non deve scalare, può solo aumentare) chiamato PTC
Vorrei trovare il modo di fornire un pannello ai player dove ogni 5000PTC che accumulano, hanno 3 punti da distribuire tra la stats attacco e la stats difesa.
Qualcuno ha idea di come possa fare? ^^"
grazie mille in anticipo

**Comment by gianni10049** [comment]
Chiudo questa issue che non e' una issue ma una richiesta e rimando l'autore a chiedere attraverso gdronline!

Grazie
