### ISSUE TITLE
[Master Screen automatici ed aumento abilità automatico] - {proposta}

### ISSUE THREAD

**Issue by Marvinandro88** [GDRCD/GDRCD#245]
Salve, 
non mi intendo molto di codici ma in passato ho provato un sistema con MS automatici che davano diritto a drops, li ho trovati molto comodi, mi chiedevo se fosse una cosa implementabile sul GDRCD base, da attivare o no in una o più chat con apposito tastino; nella versione che ho provato io c'erano mostri da sconfiggere e man mano si fleggavano quelli eliminati nel MS pop-up, per avere drops.
Un'altra cosa che sarebbe molto comoda sono gli aumenti di abilità automatici, per esempio dopo 10 volte che si utilizza la data abilità in chat, con comparsa nella scheda (o nei servizi) della possibilità di aumentarla autonomamente; anche per questo non so se sia fattibile, ma penso che sarebbe rivoluzionario!

**Comment by gianni10049** [comment]
Prendiamo nota nella lista delle implementazioni, per ora chiudo!
