### ISSUE TITLE
Abilità ad un "gruppo" generico

### ISSUE THREAD

**Issue by nikido** [GDRCD/GDRCD#25]
Riprendo una risposta di leoblacksoul su gdr-online.com
http://www.gdr-online.com/readforum.asp?id=166096

«Per allargare le abilità non solo alle razze ma anche ad altri gruppi dovresti cambiare la tabella abilita nel db. Rinominare il campo id_razza con un nome più significativo: tipo id_gruppo. E aggiungere un altro campo chiamato per esempio Tipo che rappresenta il tipo di gruppo associato all´abilità (razza, gilda, altro)
Dopo di che devi cambiare ogni pagina che usa le abilità però, anche quelle di razza, ed eventualmente creare la gestione abilità per le gilde»

Effettivamente potrebbe essere interessante "slegare" le abilità dalle razze in modo che possano essere assegnate a gruppi ad hoc, come ad esempio le gilde.

**Comment by breakeryouko** [comment]
chiudo per inattività.
