### ISSUE TITLE
Notifica messaggi nel titolo della pagina/scheda

### ISSUE THREAD

**Issue by nikido** [GDRCD/GDRCD#26]
Credo sia un bug... Alla ricezione di un messaggio privato la notifica continua a lampeggiare nel titolo a prescindere dall'aver letto o meno il messaggio in questione.

**Comment by BreakerYouko** [comment]
Credo sia un problema dovuto al codice che aveva ancora delle richieste di type "all" oppure con destinatario vuoto. Risolto nella versione 5.3
Per risolvere il tuo problema devi andare nel database e cancellare il messaggio incriminato
