### ISSUE TITLE
[BUG] - {errore di visualizzare nome oggetto in chat}

### ISSUE THREAD

**Issue by Celiene90** [GDRCD/GDRCD#260]
Ciao ho la versione installata di 5.6.0.2.
Il mio problema e un bug relativo agli oggetti che vengono inviati in chat.
In pratica quando invio un oggetto in chat mi appare la scritta : 
Tizio usa : .... 
Ma senza il nome dell'oggetto , cosa dovrei fare per sistemare questa cosa , se per favore me lo spiegate dove devo modificare per risolvere il problema ve ne sarei grata .
Grazie in anticipo a chi mi risponderà  .^^

**Comment by Kasui92** [comment]
Ciao @Celiene90 ! 
Abbiamo aggiunto un commit nel branch `dev` che risolve l'errore da te segnalato.

**Comment by Celiene90** [comment]
Ok Grazie mille ho risolto ^^
