### ISSUE TITLE
[BUG] - Versione 5.6.0.3 errore menù scheda

### ISSUE THREAD

**Issue by josephwilford** [GDRCD/GDRCD#268]
Ciao, 
ho fatto installazione di GDRCD versione 5.6.0.3 e ho visto che, cliccando sul menù scheda, restituisce un errore. Il database è stato creato correttamente e non da altri problemi ad eccezione della scheda, di cui allego screenshot.

Lo fa sia da browser pc che da mobile.

Fatal error: Uncaught TypeError: mysqli_free_result(): Argument #1 ($result) must be of type mysqli_result, array given in /membri/dmk/includes/functions.inc.php:133 Stack trace: #0 /membri/dmk/includes/functions.inc.php(133): mysqli_free_result(Array) #1 /membri/dmk/pages/scheda.inc.php(22): gdrcd_query(Array, 'free') #2 /membri/dmk/includes/functions.inc.php(518): include('/membri/dmk/pag...') #3 /membri/dmk/layouts/left-right_frames.php(138): gdrcd_load_modules('pages/scheda.in...') #4 /membri/dmk/main.php(46): require('/membri/dmk/lay...') #5 {main} thrown in /membri/dmk/includes/functions.inc.php on line 133

![immagine](https://user-images.githubusercontent.com/108751878/177373504-a5834f7c-be53-4e6e-8579-4f2d903f03b2.png)

**Comment by gianni10049** [comment]
Ciao, intanto grazie per la segnalazione.

Abbiamo provato a replicare il problema e non sembra esserci.

Abbiamo pero' notato che in realta' e' un problema simile a quello segnalato da un altro utente in passato. Quale versione di php utilizzi per gdrcd 5.6.0.3?

**Comment by gianni10049** [comment]
Gdrcd allo stato attuale consiglia la 7.3.

Supportiamo dalla 5.6 alla 7.4, ma la compatibilita' al 100% e' alla 7.3.

La 8 al momento non e' supportata perche' cambiano un bel po' di logiche.

Chiudo l'issue, grazie comunque della segnalazione.
