### ISSUE TITLE
[BUG] - {5.6.0.4} Pannello esiti

### ISSUE THREAD

**Issue by Marvinandro88** [GDRCD/GDRCD#282]
Aprendo una nuova serie esiti si apre una nuova pagina sul browser che sdoppia la principale.
Ho installato il pacchetto e non ho apportato modifiche ancora.

**Comment by gianni10049** [comment]
Ciao, nella pagina pages/gestione/segnalazioni/esiti_master.php troverai alcuni link che hanno nel loro html un'attributo:
target="_blank" , devi rimuovere dove lo trovi per evitare che il link venga aperto in una seconda pagina. 

Devono esserci sfuggiti, nella prossima release li rimuoveremo di default.

Grazie della segnalazione.

**Comment by gianni10049** [comment]
Ci siamo accorti di altre due ricorrende anche in pages/servizi_esiti.inc.php, per la parte utente del pacchetto.

Grazie.

**Comment by Kasui92** [comment]
@Marvinandro88 
Nella pull request linkata sopra puoi trovare la correzione alla segnalazione da te indicata.
[Qui](https://github.com/GDRCD/GDRCD/commit/845e02ada572fe56ea69aabbd9b1f7f03df247df) il dettaglio nello specifico.
