### ISSUE TITLE
[BUG] - {GDRCD 5.6.0.5 Disabilita tutti i suoni non funzionante}

### ISSUE THREAD

**Issue by deadbyxmas** [GDRCD/GDRCD#314]
**Describe the bug**
La funzione disabilita tutti i suoni presente nella scheda del personaggio , pur attivata col flag non sortisce alcun cambiamento, il suono di notifica dei messaggi continua a sentirsi.

Provato su Edge, Opera e Firefox anche con versione pulita di Gdrcd 5.6.0.5

**Comment by Kasui92** [comment]
@deadbyxmas 
La pull request che ho linkato a questa issue dovrebbe correggere l'errore da te segnalato.
Si tratta di un errore logico che evidentamente è rimasto di versione in versione.

(Scusa per il ritardo nella risposta!)

**Comment by Kasui92** [comment]
Ti lascio anche il link al commit sul branch dev
https://github.com/GDRCD/GDRCD/commit/99dbe1c84d03349896bddb80cd049cbdde16c00f
