### ISSUE TITLE
[BUG] - Fatal Errore su bacheca e presenti estesi

### ISSUE THREAD

**Issue by 100s3r** [GDRCD/GDRCD#315]
Ho caricato il pacchetto gdr-cd ultima release, non ho apportato modifiche al codice, se non alla parte grafica, solo lato css e mi compaiono questi due errori:

Quando viene inserito un nuovo messaggio in bacheca, questo compare nel frame della segnalazione del nuovo messaggio.

```
Fatal error:  Uncaught TypeError: mysqli_close(): Argument #1 ($mysql) must be of type mysqli, null given in /membri/gdrprova/includes/functions.inc.php:48
Stack trace:
#0 /membri/gdrprova/includes/functions.inc.php(48): mysqli_close(NULL)
#1 /membri/gdrprova/footer.inc.php(40): gdrcd_close_connection(NULL)
#2 /membri/gdrprova/pages/frame/forums/index.inc.php(117): include('/membri/gdrprova/fo...')
#3 {main}
  thrown in /membri/gdrprova/includes/functions.inc.php on line 
```
Nei presenti estesi, compare in modo randomico, senza un'apparente logica, a volte sì, a volte no

`Fatal error: Uncaught TypeError: Unsupported operand types: string + int in /membri/gdrprova/includes/functions.inc.php:544 Stack trace: #0 /membri/gdrprova/pages/presenti_estesi.inc.php(83): gdrcd_check_time('2023-01-21 21:5...') #1 /membri/gdrprova/includes/functions.inc.php(582): include('/membri/gdrprova/pa...') #2 /membri/gdrprova/layouts/left-bottom_frames.php(150): gdrcd_load_modules('presenti_estesi') #3 /membri/gdrprova/main.php(51): require('/membri/gdrprova/la...') #4 {main} thrown in /membri/gdrprova/includes/functions.inc.php on line 544`

OS: windows 10
Browser: Chrome, Firefox

**Comment by Kasui92** [comment]
@100s3r 
Posso chiederti quale versione di PHP stai utilizzando?

**Comment by 100s3r** [comment]
@Kasui92 

Certo, **php8,** è la prima cosa che ho controllato, perché anche a me è venuto quel sospetto (ho ricontrollato anche ora)

**Comment by Kasui92** [comment]
@100s3r 
Perfetto!

Allora, dovrei aver risolto entrambi gli errori da te segnalati, qui sotto le soluzioni con i relativi commit:
- Fatal Error in Frame (Forum/Messaggi) -> [a8e1835](https://github.com/GDRCD/GDRCD/pull/320/commits/a8e183592a82a8400cee8c13fbde4909f1a56235)
- Fatal Error in Presenti Estesi -> [4681a24](https://github.com/GDRCD/GDRCD/pull/320/commits/4681a2421ccae1399ed9910464b66edc80c49d16)

Potresti verificare se ti vengono mostrati o meno i messaggi di errore con questi aggiustamenti?

**Comment by 100s3r** [comment]
Ho corretto e controllato più volte, ma ma mi compaiono ora questi errori:

In cima alla main (quindi ovunque sulla piattaforma), nei presenti sul posto

`Fatal error: Uncaught Error: mysqli object is already closed in /membri/gdrprova/includes/functions.inc.php:48 Stack trace: #0 /membri/gdrprova/includes/functions.inc.php(48): mysqli_close(Object(mysqli)) #1 /membri/gdrprova/footer.inc.php(44): gdrcd_close_connection(Object(mysqli)) #2 /membri/gdrprova/main.php(54): require('/membri/gdrprova/fo...') #3 {main} thrown in /membri/gdrprova/includes/functions.inc.php on line 48`

Per quanto riguarda il frame del nuovo messaggio in bacheca, compare questo

```
Fatal error:  Uncaught TypeError: mysqli_close(): Argument #1 ($mysql) must be of type mysqli, null given in /membri/gdrprova/includes/functions.inc.php:48
--
  | Stack trace:
  | #0 /membri/gdrprova/includes/functions.inc.php(48): mysqli_close(NULL)
  | #1 /membri/gdrprova/footer.inc.php(40): gdrcd_close_connection(NULL)
  | #2 /membri/gdrprova/pages/frame/forums/index.inc.php(117): include('/membri/gdrprova/fo...')
  | #3 {main}  thrown in /membri/gdrprova/includes/functions.inc.php on line 48
```

**Comment by Kasui92** [comment]
Se provi a cambiare in footer.inc.php questa riga:

```
/*Chiudo la connessione al database, se presente*/
if(isset($handleDBConnection)) {
    gdrcd_close_connection($handleDBConnection);
}
```

in

```
/*Chiudo la connessione al database, se presente*/
if(isset($handleDBConnection)) {
    // Chiudo la connessione al database
    gdrcd_close_connection($handleDBConnection);
    // Libero la memoria occupata dalla variabile
    unset($handleDBConnection);
}
```

ti da ancora gli stessi errori?

**Comment by 100s3r** [comment]
Sì, stesso identico errore

**Comment by Kasui92** [comment]
Stai per caso usando altervista.org per l'host del progetto?

**Comment by 100s3r** [comment]
Sì, altervista.

**Comment by Kasui92** [comment]
Per caso hai inserito il progetto in una cartella diversa da quella principale?
Quindi non in `/ ` ma in `/nome_cartella`

**Comment by 100s3r** [comment]
No, è tutto nella cartella principale. Ho usato gdr cd in tutte le precedenti versioni, e ho sempre estratto tutti i file e messi nella cartella principale in /

**Comment by Kasui92** [comment]
Hai per caso attivato qualche impostazione particolare per il tuo spazio altervista.org o per la versione PHP che utilizzi?
Ho provato a riprodurre qui il tuo problema, ma oltre agli errori iniziali risolti, non ho trovato altro.

**Comment by Kasui92** [comment]
Hai per caso modificato footer o i frames in qualche modo?

@gianni10049 @Dyrr  
Vi taggo per darmi supporto sulla questione dato che siete più veterani di me su GDRCD.

**Comment by Kasui92** [comment]
@100s3r 
Riusciresti a mettere qui tutto il contenuto del tuo file footer.inc.php ?

**Comment by gianni10049** [comment]
Ho fatto vari test e l'unico modo in cui sono riuscito ad ottenere un risultato simile e' questo:
![Schermata 2023-01-26 alle 15 42 17](https://user-images.githubusercontent.com/38789905/214865204-86d85dd4-6cc0-426f-aeec-3a8f3eee8e29.png)

Ovvero chiudendo due volte la connessione nella stessa pagina. Non e' che nelle tue modifiche alla bacheca hai duplicato qualche chiusura di connessione che ti da' quell'errore? Se riesci a fare un po' di controlli sarebbe ottimo.

Intanto noi risolviamo il problema a monte.

Grazie.

**Comment by 100s3r** [comment]
Vi rispondo subito, non ho settato nulla sul sito di altervista, ma mi sono limitato a controllare che ci fosse il php8.

Questo è il footer intero come richiesto da @Kasui92 

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script type="text/javascript" src="/includes/corefunctions.js"></script>
<!--<script type="text/javascript" src="includes/gdrcdskills.js"></script>-->
<script type="text/javascript" src="/includes/modal.js"></script>
<?php
/** * Abilitazione tooltip
 * @author Blancks
 */
if($PARAMETERS['mode']['map_tooltip'] == 'ON' || $PARAMETERS['mode']['user_online_state'] == 'ON') { ?>
    <script type="text/javascript">
        var tooltip_offsetX = <?php echo $PARAMETERS['settings']['map_tooltip']['offset_x']; ?>;
        var tooltip_offsetY = <?php echo $PARAMETERS['settings']['map_tooltip']['offset_y']; ?>;
    </script>
    <script type="text/javascript" src="/includes/tooltip.js"></script>
    <?php
}
/** * Caricamento script per il titolo "lampeggiante" per i nuovi pm
 * @author Blancks
 */
if($PARAMETERS['mode']['alert_pm_via_pagetitle'] == 'ON') {
    echo '<script type="text/javascript" src="/includes/changetitle.js"></script>';
}
/** * Caricamento script per la scelta popup nel login
 * @author Blancks
 */
if($PARAMETERS['mode']['popup_choise'] == 'ON') {
    echo '<script type="text/javascript" src="/includes/popupchoise.js"></script>';
}
?>
<!--<script type="text/javascript">
    setTimeout("self.location.href.reload();",<?php //echo (int) $_GET['ref'] * 1000; ?>);
</script-->
</body>
</html>
<?php
/*Chiudo la connessione al database*/
gdrcd_close_connection($handleDBConnection);

/*Chiudo la connessione al database, se presente*/
if(isset($handleDBConnection)) {
    // Chiudo la connessione al database
    gdrcd_close_connection($handleDBConnection);
    // Libero la memoria occupata dalla variabile
    unset($handleDBConnection);
}

/**    * Per ottimizzare le risorse impiegate le liberiamo dopo che non ne abbiamo pi� bisogno
 * @author Blancks
 */
unset($MESSAGE);
unset($PARAMETERS);
?>
```

Per rispondere a @gianni10049 
- i file presenti_estesi, forum, presenti, non li ho toccati, né lato php, né lato css, nel dubbio li ho ricaricati originali e l'errore è sempre quello.

L'unico file che ho corretto manualmente è: left_bottom_frames nei css iniziali (ma l'errore me lo dava prima della correzione, me lo ha dato proprio al secondo login quando ancora non avevo toccato neanche i css).

**Comment by Kasui92** [comment]
Ecco l'errore:

```
/*Chiudo la connessione al database*/
gdrcd_close_connection($handleDBConnection);

/*Chiudo la connessione al database, se presente*/
if(isset($handleDBConnection)) {
    // Chiudo la connessione al database
    gdrcd_close_connection($handleDBConnection);
    // Libero la memoria occupata dalla variabile
    unset($handleDBConnection);
}
```

Come vedi, qui effettui due volte la chiusura della connessione.
Prova a cancellare questo:

```
/*Chiudo la connessione al database*/
gdrcd_close_connection($handleDBConnection);
```

e vedi se ti da errore.

**Comment by Kasui92** [comment]
Credo che sia una parentesi chiusa non correttamente, nello specifico a ridosso della modifica sul controllo orario di entrata. 

Modifica questo passaggio:

```php
//Controllo da quanto il pg e' loggato
            $activity = gdrcd_check_time($record['ora_entrata']);
            //Se e' loggato da meno di 2 minuti
            if ($activity <= 2)   {
                //Lo segnalo come appena entrato
                echo '<img class="presenti_ico" src="imgs/icons/enter.gif" alt="'.gdrcd_filter('out', $MESSAGE['status_pg']['enter']).'" title="'.gdrcd_filter('out', $MESSAGE['status_pg']['enter']).'" />';
            } else  {
                 //Altrimenti e' semplicemente loggato
                    echo '<img class="presenti_ico" src="imgs/icons/blank.png" alt="'.gdrcd_filter('out', $MESSAGE['status_pg']['logged']).'" title="'.gdrcd_filter('out', $MESSAGE['status_pg']['logged']).'" />';
                }//else
                          //Altrimenti e' semplicemente loggato
                echo '<img class="presenti_ico" src="imgs/icons/blank.png" alt="'.gdrcd_filter('out', $MESSAGE['status_pg']['logged']).'" title="'.gdrcd_filter('out', $MESSAGE['status_pg']['logged']).'" />';
            }//else
```

in:

```php
            //Controllo da quanto il pg e' loggato
            $activity = gdrcd_check_time($record['ora_entrata']);
            //Se e' loggato da meno di 2 minuti
            if ($activity <= 2)   {
                //Lo segnalo come appena entrato
                echo '<img class="presenti_ico" src="imgs/icons/enter.gif" alt="'.gdrcd_filter('out', $MESSAGE['status_pg']['enter']).'" title="'.gdrcd_filter('out', $MESSAGE['status_pg']['enter']).'" />';
            } else {
             //Altrimenti e' semplicemente loggato
                echo '<img class="presenti_ico" src="imgs/icons/blank.png" alt="'.gdrcd_filter('out', $MESSAGE['status_pg']['logged']).'" title="'.gdrcd_filter('out', $MESSAGE['status_pg']['logged']).'" />';
            }//else
```

**Comment by 100s3r** [comment]
Ora sembra funzionare tutto alla perfezione, grazie!
