### ISSUE TITLE
[BUG] - {Audio - ossia musica in scheda personaggio non funziona}

### ISSUE THREAD

**Issue by deadbyxmas** [GDRCD/GDRCD#317]
Come da titolo, la musica nella scheda del personaggio non funziona, neanche con una versione pulita utilizzata da zero e non dovrebbe essere un problema riguardante gli hosting musicali, i link funzionanti con passate versioni di gdrcd per esempio non vanno

Versione: Gdrcd 5.6.05

**Comment by Kasui92** [comment]
@deadbyxmas 
Con l'aggiornamento linkato a questa issue dovrebbe essersi risolto il problema dell'audio in scheda (oltre a diverse funzionalità sbloccate sempre in quella stessa pagina).
