### ISSUE TITLE
[BUG] - Mancato funzionamento della funzione "cancella account"

### ISSUE THREAD

**Issue by PB80** [GDRCD/GDRCD#318]
Versione 5.6 aggiornata con con tutti i fix del git

Dalla sezione del menu' si accede alla voce Cancella Account, tramite la quale si dovrebbe poter avere modo di eliminare appunto account. La proceduta del pannello non presenta errori, seleziono l'account che vorrei eliminare, mi da il messaggio di "modifica eseguita" ma l'account rimane attivo e funzionante.

**Comment by Kasui92** [comment]
@PB80 
Allo stato attuale, dopo l'eliminazione dell'account dal **Menu Utente** occorre effettuare un ulteriore passaggio per la completa cancellazione attraverso il pannello **Gestione** > **Manutenzione** e quindi **_Elimina i personaggi provvisoriamente cancellati_**  . Solo così saranno completamente rimossi gli account cancellati.

Sappiamo che si tratta di una operazione non proprio intuitiva e stiamo provvedendo a migliorarla.

Lascio la issue aperta per comunicarti la nostra soluzione alla cosa.

**Comment by Kasui92** [comment]
Ciao @Pumbaa49 ! 
Prova a scaricare quest'[ultima versione di GDRCD](https://github.com/GDRCD/GDRCD/releases/tag/5.6.0.6) e fammi sapere se il problema è risolto.
