### ISSUE TITLE
Scheda pg LOG

### ISSUE THREAD

**Issue by Eriannen** [GDRCD/GDRCD#32]
nella scheda premendo sul menù log si vedono le date e gli ip di accesso oltre ai doppi ed eventuale cambio nome, oggi mi sono accorto che è comparso alla fine della pagina questo errore

Warning: mysqli_free_result() [function.mysqli-free-result]: Couldn't fetch mysqli_result in includes/functions.inc.php on line 128

url pagina
main.php?page=scheda_log&pg=pgprova

**Comment by breakeryouko** [comment]
chiudo per inattività.
