### ISSUE TITLE
[FEATURE] - Bug notifica messaggi [RISOLTO]

### ISSUE THREAD

**Issue by Pumbaa49** [GDRCD/GDRCD#332]
**La richiesta nasce da che tipo di necessita'?**
Ho notato che, quando viene inviato un messaggio, non compare nessuna notifica di messaggio ricevuto a meno che non si aggiorna manualmente la pagina. 

**Descrizione della soluzione che avevi immaginato.**
Inizialmente pensavo che ci fosse qualche problema con il refresh automatico, ma dopo un breve confronto con altri utenti mi è stato segnalato un errore di battitura nel codice di GDRCD che, dopo aver corretto, ha risolto il problema.

**Contenuto addizionale**
Allego qui di seguito il codice errato e la successiva correzione.

CODICE ERRATO:

pages > frame > messages> index.inc.php a riga 98 

` $cntMessagesFrame .= '<script type="text/javascript">parent.blink_title("('.$MESSAGE['interface']['forums']['topic']['new_posts']['sing'].')" '.$PARAMETERS['info']['site_name'].'););</script>';`

CODICE CORRETTO

` $cntMessagesFrame .= '<script type="text/javascript">parent.blink_title("('.$MESSAGE['interface']['forums']['topic']['new_posts']['sing'].')" '.$PARAMETERS['info']['site_name'].'"););</script>';`

SPIEGAZIONE

Manca il doppio apice " a chiusura della stringa, dopo ['site_name'].' e prima della parentesi tonda )

**Comment by gianni10049** [comment]
Risolto.
