### ISSUE TITLE
[BUG] - Possibilità di lettura Chat Privata

### ISSUE THREAD

**Issue by Branci89** [GDRCD/GDRCD#338]
Ciao a tutti, 
Segnalo un bug che permette ai PG non autorizzati perché non invitati , di leggere e scrivere nelle chat private. 

Di seguito, la procedure per replicare la issue:

1. Avere un PG utente, quindi non gestore, e andare su una chat pubblica qualsiasi.
2. Duplicare la scheda della chat pubblica in modo da avere la land aperta su due schede con lo stesso PG.
3. nella scheda appena duplicata entrare in una chat privata dove due player stanno già giocando e dove non si è stati invitati
4. Nella prima scheda (quella con la chat pubblica) appariranno le azioni e si può scrivere come se si fosse dentro la chat privata. Infatti, chi sta giocando, vedrà le azioni che noi manderemo nella pubblica.

Grazie

**Comment by gianni10049** [comment]
Bug risolto con questa revisione:
7d3e4ca45a179faa0ad00ba76c2378322ceec151
