### ISSUE TITLE
[BUG] - {Bug dadi in chat}

### ISSUE THREAD

**Issue by Pumbaa49** [GDRCD/GDRCD#339]
**Describe the bug**
Installando una versione pulita di GDRCD (quindi senza nessuna modifica apportata) ho visto che, quando si tira un dado in chat, il risultato non somma il valore della caratteristica a quello del dado e/o dell'abilità, ma restituisce solo il valore dell'abilità più il dado (nel caso si usi un'abilità), oppure solo del dado (nel caso in cui viene usata una caratteristica + il dado). 

**Screenshots**
Allego uno screen del mio test ^^
<img width="2556" alt="Screenshot 2023-09-04 alle 15 02 10" src="https://github.com/GDRCD/GDRCD/assets/97109894/2b4d8029-9fb6-44db-b172-9aed2922fb92">

**Comment by Kasui92** [comment]
Ciao @Pumbaa49 ! 
Si tratta di un errore noto che abbiamo risolto nell'ultima Release di GDRCD, nello specifico [v5.6.0.6](https://github.com/GDRCD/GDRCD/releases/tag/5.6.0.6) .

Puoi trovare la correzione al problema in questo [commit](https://github.com/GDRCD/GDRCD/commit/30e4af12b41e19156bf4e957a0f548f236ea8767)
