### ISSUE TITLE
[BUG] - Installazione Database

### ISSUE THREAD

**Issue by gwenborgato** [GDRCD/GDRCD#344]
Appena configurato il config, apro il sito e mi chiede “vuoi installate il db?” clicco: “Sì”.
Mi dice che la sessione è scaduta, bene. Dunque clicco su Homepage, oppure vado direttamente su index e, di nuovo: “vuoi installate il db?” “Sì” “vuoi installate il db?” “Sì” “vuoi installate il db?” “Sì” e in pratica mi è toccato installarlo manualmente perché non riuscivo ad uscire dal loop.

**Comment by Kasui92** [comment]
Ciao @gwenborgato ! 
Posso chiederti che versione di GDRCD stai utilizzando?
E se stai utilizzando GDRCD-stack?

**Comment by baki2211** [comment]
Appena fatto un test. Clonata la repository e lanciato gdrcd. DB installato correttamente.

**Comment by gianni10049** [comment]
Data mancanza di risposta e test positivi, chiudo.

Grazie!
