### ISSUE TITLE
[BUG] - Non ricevo password via mail

### ISSUE THREAD

**Issue by gwenborgato** [GDRCD/GDRCD#345]
All'iscrizione, il nuovo personaggio non riceve via mail la password.

**Comment by Kasui92** [comment]
Ciao @gwenborgato !
Questa tipologia di malfunzionamento può essere dovuta da diversi fattori:

- l'utilizzo di un account GMAIL per l'invio della e-mail su di un host che ha un proprio dominio, come altervista.org;
- indirizzo email non settato correttamente o non valido in `config.inc.php`;
-l'host non presenta una libreria per l'invio delle email (se per esempio stai utilizzando versioni vecchie di GDRCD-stack);
- eventuali filtri anti SPAM da parte di chi riceve, che buttano la e-mail in Posta indesiderata o Spam;

Riesci a darmi riscontro su queste verifiche?

**Comment by gianni10049** [comment]
Mancata risposta e test andati positivamente sulla ricezione email, chiudo!

Grazie!
