### ISSUE TITLE
[BUG] - Accenti

### ISSUE THREAD

**Issue by gwenborgato** [GDRCD/GDRCD#346]
Gli accenti non vanno.

Esempio:
Ricevuto il: 04/01/2024 alle 09:31
Mittente: GB
Tipo: OFF
Oggetto:
Lo staff &egrave; lieto di darti il benvenuto e ti augura buon divertimento! Hai gi&agrave; letto lambientazione ed il regolameto? Se non &egrave; cos&igrave; ti invitiamo a farlo al pi&ugrave; presto!.

**Comment by Kasui92** [comment]
Ciao @gwenborgato ! 
Posso chiederti quale versione di GDRCD stai utilizzando? L'ultima?

**Comment by iechiveler** [comment]
Ciao,
Ho scaricato l'ultima versione di GDRCD e confermo quanto accaduto a @gwenborgato, sul DB mi ritrovo la scritta con gli accenti tutti sballati. Il campo Testo sul DB è in utf8_general_ci.

**Comment by iechiveler** [comment]
Ho risolto impostando questo spezzone di codice dalla riga 48 alla 50 del file read.inc.php

`<div class="read_message_box_text">
            <?php echo nl2br(gdrcd_bbcoder(gdrcd_html_filter($record['testo']))); ?>
        </div>`

ho modificato da gdrcd_filter in gdrcd_html_filter, rimuovendo il parametro 'out',

Prima:

`<div class="read_message_box_text">
            <?php echo nl2br(gdrcd_bbcoder(gdrcd_filter('out', $record['testo']))); ?>
        </div>`

**Comment by gianni10049** [comment]
La soluzione in realta' e' molto piu' semplice perche' e' un errore in fase di inserimento del testo messaggio di benvenuto all'interno del DB.

La soluzione proposta da @iechiveler causerebbe la possibilita' di utilizzare html all'interno dei messaggi inviati, causando vari errori.

La soluzione corretta puo' essere trovata qui:
c82c0ee0dc3fa64787837092dcbd01d7a1cbe800

Chiuso, grazie!

**Comment by Kasui92** [comment]
@gianni10049 
Per caso la soluzione a questa issue era quella poi proposta in #352  ? 
Perché se è così, concordo con te che la PR di @annamereu la chiude.
