### ISSUE TITLE
[TEXT REVIEW] - config.inc.php

### ISSUE THREAD

**Issue by simplyfear** [GDRCD/GDRCD#347]
riga 10
```php
 * HELP [-- IMPORTANTE!!! --]: Il corrente file contiene un elenco di parametri essenziali alla configurazione ed al funzionamento di GDRCD. È  richiesto che vengano configurati i parametri alla voce "parametri di connessione" per eseguire una corretta connessione al database, altrimenti GDRCD non è in grado di operare.
 * I parametri alle voci successive hanno la funzione di personalizzare il sito in funzione delle esigenze del proprio gioco. In particolare è possibile selezionare il tema dell'interfaccia del sito, personalizzare alcuni nomi chiave all'interno del gioco, e selezionare quali funzioni attivare o disattivare tra le opzioni di gioco disponibile. 
 * Per ogni voce è presente un help esaustivo. Nel dubbio, leggerlo con attenzione.
```

riga 93 
```php
 * SCELTA DEL TIPO DI LAYOUT
 * Tutti i layout sono cross-browser, compatibili cioè con tutti i browser.
 * Il css di ogni singolo layout è disponibile nel file del layout nella cartella "layouts"
 * se avete intenzione di editarli fatelo con cura
 * @author Blancks
 **** Descrizione dei tipi di frames_layout selezionabili:
 *
 * left-right: [ LAYOUT DI DEFAULT ] layout a frames con colonne fisse a destra e sinistra
 * * Questo layout consente di abilitare e di usare left_column e right_column per decidere quali moduli caricare e dove inserirli
 *
 * left-top: Layout a frames con colonna fissa a sinistra e riga fissa in alto, contenuti in basso adattabili
 * * Questo layout consente di abilitare e di usare left_column e top_column per decidere quali moduli caricare e dove inserirli
 *
 * left-bottom: Layout a frames con colonna fissa a sinistra e riga fissa in basso, contenuti in alto adattabili
 * * Questo layout consente di abilitare e di usare left_column e bottom_column per decidere quali moduli caricare e dove inserirli
 *
 * top-bottom: Layout a frames con riga fissa in alto e riga fissa in basso, contenuti al centro
 * * Questo layout consente di abilitare e di usare top_column e bottom_column per decidere quali moduli caricare e dove inserirli
 *
 *
 * * AVVERTENZA: ricordare di ordinare il css dei moduli di modo che sostino bene, su di una riga, altrimenti è normale
 * * avere problemi di visualizzazione
 *
 *
 * left-top-right: Layout a frames con colonna fissa a sinistra e a destra e riga fissa in alto, contenuti in basso al
 *     centro adattabili
 * * Questo layout consente di abilitare e di usare left_column, top_column e right_column per decidere quali moduli caricare e dove inserirli
 *
 *
 * * AVVERTENZA: ricordare di ordinare il css dei moduli di modo che sostino bene sulla riga superiore, altrimenti è
 *     normale avere problemi di visualizzazione
 *
 *
 * left-right-bottom: Layout a frames con colonna fissa a sinistra e a destra e riga fissa in basso, contenuti in alto
 *     al centro adattabili
 * * Questo layout consente di abilitare e di usare left_column, bottom_column e right_column per decidere quali moduli caricare e dove inserirli
 *
 *
 * * AVVERTENZA: ricordare di ordinare il css dei moduli di modo che sostino bene sulla riga superiore, altrimenti è
 *     normale avere problemi di visualizzazione
 *
 *
 * left-top-bottom: Layout a frames con colonna fissa a sinistra e riga fissa in basso e in alto, contenuti al centro
 *     adattabili
 * * Questo layout consente di abilitare e di usare left_column, bottom_column e top_column per decidere quali moduli caricare e dove inserirli
 *
 *
 * * AVVERTENZA: ricordare di ordinare il css dei moduli di modo che sostino bene sulla riga superiore, altrimenti è
 *     normale avere problemi di visualizzazione
 *
 *
 * left-top-right-bottom: Layout a frames con colonna fissa a sinistra e a destra e riga fissa in basso e in alto,
 *     contenuti al centro adattabili
 * * Questo layout consente di abilitare e di usare left_column, bottom_column, top_column e right_column per decidere quali moduli caricare e dove
 *    
 *
 * * AVVERTENZA: ricordare di ordinare il css dei moduli di modo che sostino bene sulla riga superiore e inferiore,
 *     altrimenti è normale avere problemi di visualizzazione
 *
 *
 * left: layout a frames con una colonna di sinistra fissa e contenuto adattabile
 * * Questo layout consente di abilitare e di usare solo left_column per caricare i moduli (menu, messaggi, presenti, etc)
 *
 * right: Layout a frames con una colonna di destra fissa e contenuto adattablile
 * * Questo layout consente di abilitare e di usare solo right_column per caricare i moduli

 * top: Layout a frames con una riga in alto e contenuti adattabili in basso
 * * Questo layout consente di abilitare e di usare solo top_column per caricare i moduli

 * bottom: Layout a frames con una riga in basso e contenuti adattabili in alto
 * * Questo layout consente di abilitare e di usare solo bottom_column per caricare i moduli

 *
 * * AVVERTENZA: ricordare di ordinare il css dei moduli di modo che sostino bene, su di una riga, altrimenti è normale
 * * avere problemi di visualizzazione
 *
 */
```

riga 490 ( correggere seconda scelta in off)
```php
$PARAMETERS['mode']['privaterooms'] = 'ON';
//ON: Il gioco prevede stanze private temporanee prenotabili dai giocatori.
//OFF: Il gioco non prevede stanze private prenotabili dai giocatori.
```

riga 496 ( corretto carattere )
```php
$PARAMETERS['mode']['chatsave'] = 'ON';
//ON: È abilitato il pulsante Salva chat.
//OFF: È disabilitato il pulsante Salva chat.
$PARAMETERS['mode']['chatsavepvt'] = 'OFF';
//ON: È abilitato il pulsante Salva chat per le chat private, SCONSIGLIATO.
//OFF: È disabilitato il pulsante Salva chat per le chat private.
```

riga 509 ( corretto bensi' nella mappa in : ma nella mappa principale )
```php
/* HELP: Le voci di questa categoria abilitano o disabilitano funzioni presenti nel gioco. Ad esempio, se non si desidera che il personaggio si riconnetta nello stesso luogo di gioco in cui si è disconnesso, ma  nella mappa principale, occorre impostare in OFF la relativa voce */
```

riga 546 ( corretto carattere ) 
```php
/* HELP: Decommentare (rimuovere //) una coppia immagine-testo, fra quelle elencate sopra, fa apparire il corrispondente simbolo PEGI in homepage. È necessario decommentare sia la riga corrispondente all'immagine che quella corrispondente al testo */
```

riga 551 ( corretto carattere  e risistemata visualizzazione testo)
```php
 * Le seguenti voci configurano i menù opzioni interni al gioco. 
 * Specificare un diverso testo visualizzato (text) o un immagine (image_file) modifica l'aspetto del menu.
 * Alterare l'indirizzo di riferimento (url) o cancellare voci potrebbe pregiudicare il funzionamento di parte del gioco.
 * Le immagini specificate in image_file e image_file_onclick devono essere nella cartella imgs/menu del tema
 * e sono, rispettivamente, l'immagine di base del tasto e l'immagine al passaggio del mouse.
 * Nel caso la seconda mancasse viene visualizzata la prima in entrambi i casi.
 *
 * Alternativamente per gli utenti esperti: al posto delle immagini image_file e image_file_onclick
 * (che vengono modificare con javascript) è possibile utilizzare un'immagine sola come sprite ( https://css-tricks.com/css sprites/ ). 
 * Per impostare la sprite inserire la chiave 'sprite' nella configurazione della voce di menù e dargli un valore true.
 * Per impostare l'immagine usare solo la chiave 'image_file'.
 * Ricordarsi però di personalizzare correttamente le dimensioni delle immagini nel css (main.css): di default sono impostate a 50x50px
 */
```

riga 646 ( correzione carattere )
```php
/* HELP: Queste voci compariranno nel menu di gioco. È possibile scegliere se farle comparire come immagini o semplice testo. Se, per ciascuna voce, è specificato il campo image_file allora la voce di menu compare come immagine e text viene interpretato come testo alternativo all'immagine.
* text - Testo visualizzato come voce di menu o testo alternativo dell'immagine
* url - Destinazione del link. È  sconsigliato modificare questa voce.
* image_file - File dell'immagine che appare come voce di menu. L'immagine deve trovarsi nella cartella themes/[nome tema]/img/menu (per il template preimpostato themes/extreme/img/menu)*/
```

riga 780 ( correzione carattere )
```php
/* HELP: Elenco delle voci dei menù dei servizi e di gestione.  È sconsigliato operare modifiche. Le opzioni sono disponibili solo agli account con il livello d'accesso specificato o superiore. sconsigliato operare modifiche. Le opzioni sono disponibili solo agli account con il livello d'accesso specificato o superiore.
```

**Comment by simplyfear** [comment]
riga 10 =  * HELP [-- IMPORTANTE!!! --]: Il corrente file contiene un elenco di parametri essenziali alla configurazione ed al funzionamento di GDRCD. È  richiesto che vengano configurati i parametri alla voce "parametri di connessione" per eseguire una corretta connessione al database, altrimenti GDRCD non è in grado di operare.
 * I parametri alle voci successive hanno la funzione di personalizzare il sito in funzione delle esigenze del proprio gioco. In particolare è possibile selezionare il tema dell'interfaccia del sito, personalizzare alcuni nomi chiave all'interno del gioco, e selezionare quali funzioni attivare o disattivare tra le opzioni di gioco disponibile. 
 * Per ogni voce è presente un help esaustivo. Nel dubbio, leggerlo con attenzione.
----------------------------------------------------
da riga 93 =* SCELTA DEL TIPO DI LAYOUT ( sistemazione visiva del descritto)
* SCELTA DEL TIPO DI LAYOUT
 * Tutti i layout sono cross-browser, compatibili cioè con tutti i browser.
 * Il css di ogni singolo layout è disponibile nel file del layout nella cartella "layouts"
 * se avete intenzione di editarli fatelo con cura
 * @author Blancks
 **** Descrizione dei tipi di frames_layout selezionabili:
 *
 * left-right: [ LAYOUT DI DEFAULT ] layout a frames con colonne fisse a destra e sinistra
 * * Questo layout consente di abilitare e di usare left_column e right_column per decidere quali moduli caricare e dove inserirli
 * left-top: Layout a frames con colonna fissa a sinistra e riga fissa in alto, contenuti in basso adattabili
 * * Questo layout consente di abilitare e di usare left_column e top_column per decidere quali moduli caricare e dove inserirli
 * left-bottom: Layout a frames con colonna fissa a sinistra e riga fissa in basso, contenuti in alto adattabili
 * * Questo layout consente di abilitare e di usare left_column e bottom_column per decidere quali moduli caricare e dove inserirli
 * top-bottom: Layout a frames con riga fissa in alto e riga fissa in basso, contenuti al centro
 * * Questo layout consente di abilitare e di usare top_column e bottom_column per decidere quali moduli caricare e dove inserirli
 *
 * * AVVERTENZA: ricordare di ordinare il css dei moduli di modo che sostino bene, su di una riga, altrimenti è normale
 * * avere problemi di visualizzazione
 *	
 * left-top-right: Layout a frames con colonna fissa a sinistra e a destra e riga fissa in alto, contenuti in basso al
 *     centro adattabili
 * * Questo layout consente di abilitare e di usare left_column, top_column e right_column per decidere quali moduli caricare e dove inserirli
 *
 * * AVVERTENZA: ricordare di ordinare il css dei moduli di modo che sostino bene sulla riga superiore, altrimenti è
 *     normale avere problemi di visualizzazione
 *
 * left-right-bottom: Layout a frames con colonna fissa a sinistra e a destra e riga fissa in basso, contenuti in alto
 *     al centro adattabili
 * * Questo layout consente di abilitare e di usare left_column, bottom_column e right_column per decidere quali moduli caricare e dove inserirli
 *
 * * AVVERTENZA: ricordare di ordinare il css dei moduli di modo che sostino bene sulla riga superiore, altrimenti è
 *     normale avere problemi di visualizzazione
 *
 * left-top-bottom: Layout a frames con colonna fissa a sinistra e riga fissa in basso e in alto, contenuti al centro
 *     adattabili
 * * Questo layout consente di abilitare e di usare left_column, bottom_column e top_column per decidere quali moduli caricare e dove inserirli
 *
 * * AVVERTENZA: ricordare di ordinare il css dei moduli di modo che sostino bene sulla riga superiore, altrimenti è
 *     normale avere problemi di visualizzazione
 *
 * left-top-right-bottom: Layout a frames con colonna fissa a sinistra e a destra e riga fissa in basso e in alto,
 *     contenuti al centro adattabili
 * * Questo layout consente di abilitare e di usare left_column, bottom_column, top_column e right_column per decidere quali moduli caricare e dove    
 *
 * * AVVERTENZA: ricordare di ordinare il css dei moduli di modo che sostino bene sulla riga superiore e inferiore,
 *     altrimenti è normale avere problemi di visualizzazione
 *
 * left: layout a frames con una colonna di sinistra fissa e contenuto adattabile
 * * Questo layout consente di abilitare e di usare solo left_column per caricare i moduli (menu, messaggi, presenti, etc)
 * right: Layout a frames con una colonna di destra fissa e contenuto adattablile
 * * Questo layout consente di abilitare e di usare solo right_column per caricare i moduli
 * top: Layout a frames con una riga in alto e contenuti adattabili in basso
 * * Questo layout consente di abilitare e di usare solo top_column per caricare i moduli
 * bottom: Layout a frames con una riga in basso e contenuti adattabili in alto
 * * Questo layout consente di abilitare e di usare solo bottom_column per caricare i moduli
 *
 * * AVVERTENZA: ricordare di ordinare il css dei moduli di modo che sostino bene, su di una riga, altrimenti è normale
 * * avere problemi di visualizzazione
 *
 */
--------------------
riga 490 ( correggere seconda scelta in off)
$PARAMETERS['mode']['privaterooms'] = 'ON';
//ON: Il gioco prevede stanze private temporanee prenotabili dai giocatori.
//OFF: Il gioco non prevede stanze private prenotabili dai giocatori.
______________________
riga 496 ( corretto carattere )
$PARAMETERS['mode']['chatsave'] = 'ON';
//ON: È abilitato il pulsante Salva chat.
//OFF: È disabilitato il pulsante Salva chat.
$PARAMETERS['mode']['chatsavepvt'] = 'OFF';
//ON: È abilitato il pulsante Salva chat per le chat private, SCONSIGLIATO.
//OFF: È disabilitato il pulsante Salva chat per le chat private.
________________________________
riga 509 ( corretto bensi' nella mappa in : ma nella mappa principale )/* HELP: Le voci di questa categoria abilitano o disabilitano funzioni presenti nel gioco. Ad esempio, se non si desidera che il personaggio si riconnetta nello stesso luogo di gioco in cui si è disconnesso, ma  nella mappa principale, occorre impostare in OFF la relativa voce */
---------------------------------
riga 546 ( corretto carattere ) /* HELP: Decommentare (rimuovere //) una coppia immagine-testo, fra quelle elencate sopra, fa apparire il corrispondente simbolo PEGI in homepage. È necessario decommentare sia la riga corrispondente all'immagine che quella corrispondente al testo */
--------------------------------
riga 551 ( corretto carattere  e risistemata visualizzazione testo)
 * Le seguenti voci configurano i menù opzioni interni al gioco. 
 * Specificare un diverso testo visualizzato (text) o un immagine (image_file) modifica l'aspetto del menu.
 * Alterare l'indirizzo di riferimento (url) o cancellare voci potrebbe pregiudicare il funzionamento di parte del gioco.
 *  Le immagini specificate in image_file e image_file_onclick devono essere nella cartella imgs/menu del tema
 * e sono, rispettivamente, l'immagine di base del tasto e l'immagine al passaggio del mouse.
 * Nel caso la seconda mancasse viene visualizzata la prima in entrambi i casi.
 *
 * Alternativamente per gli utenti esperti: al posto delle immagini image_file e image_file_onclick
 * (che vengono modificare con javascript) è possibile utilizzare un'immagine sola come sprite ( https://css-tricks.com/css sprites/ ). 
 * Per impostare la sprite inserire la chiave 'sprite' nella configurazione della voce di menù e dargli un valore true.
 *  Per impostare l'immagine usare solo la chiave 'image_file'.
 *  Ricordarsi però di personalizzare correttamente le dimensioni delle immagini nel css (main.css): di default sono impostate a 50x50px
 */
_________________________________________
da riga 646 ( correzione carattere )
/* HELP: Queste voci compariranno nel menu di gioco. È possibile scegliere se farle comparire come immagini o semplice testo. Se, per ciascuna voce, è specificato il campo image_file allora la voce di menu compare come immagine e text viene interpretato come testo alternativo all'immagine.
* text - Testo visualizzato come voce di menu o testo alternativo dell'immagine
* url - Destinazione del link. È  sconsigliato modificare questa voce.
* image_file - File dell'immagine che appare come voce di menu. L'immagine deve trovarsi nella cartella themes/[nome tema]/img/menu (per il template preimpostato themes/extreme/img/menu)*/
__________________________________________
riga 780 ( correzione carattere )
/* HELP: Elenco delle voci dei menù dei servizi e di gestione.  È sconsigliato operare modifiche. Le opzioni sono disponibili solo agli account con il livello d'accesso specificato o superiore. sconsigliato operare modifiche. Le opzioni sono disponibili solo agli account con il livello d'accesso specificato o superiore.
------------------------------------------

**Comment by blancks** [comment]
Sta lavorando su un fork, chiuso la issue in quanto non più necessaria.
