### ISSUE TITLE
Assegnazione punti exp

### ISSUE THREAD

**Issue by Eriannen** [GDRCD/GDRCD#35]
nella 5.1 il messaggio dell'assegnazione punti px veniva scritto nella bacheca diario quest, qui noto che viene scritto solo nella scheda del pg "esperienza" se non è un bug elimino la bacheca diario quest
grazie

**Comment by BreakerYouko** [comment]
Qual'è la bacheca diario quest?

**Comment by breakeryouko** [comment]
chiudo per inattività.
