### ISSUE TITLE
[BUG GDRCD 5.6.0.5] - Pannelli per gli Esiti senza tasti

### ISSUE THREAD

**Issue by Idas94** [GDRCD/GDRCD#350]
Premettendo che l'unica modifica effettuata al codice sorgente è di aver messo tutti dentro a modali, quando si accede al pannello degli esiti lato utente, o master, il risultato è il medesimo. Qui si possono vedere gli screenshot:

<img width="895" alt="Screenshot 2024-05-13 alle 4 41 04 PM" src="https://github.com/GDRCD/GDRCD/assets/166132622/75a9aafa-994a-483c-b01b-831aaf8e2c1b">

<img width="895" alt="Screenshot 2024-05-13 alle 4 41 15 PM" src="https://github.com/GDRCD/GDRCD/assets/166132622/4189308f-959c-497a-a8d2-3eee296afba8">

**Comment by Kasui92** [comment]
Con la PR #360  abbiamo risolto questo problema, sarà presente nella prossima versione.
Puoi comunque utilizzare le correzioni che trovi nel [commit](https://github.com/GDRCD/GDRCD/commit/131aa8cc13384fc17b89002df8945e6c0186dd60) .
