### ISSUE TITLE
[FEATURE] - Logoff se ritornato sul sito principale

### ISSUE THREAD

**Issue by hydantonio** [GDRCD/GDRCD#353]
**La richiesta nasce da che tipo di necessita'?**
Se si chiude la scheda bisogna aspettare cinque minuti o andare sul sito web #/logout.php prima di poter riaccedere.

**Descrizione della soluzione che avevi immaginato.**
Lo script legge se si è presenti nella pagina una volta caricata, nel momento in cui viene chiusa, bisogna effettuare il login di nuovo. Aggiorna automaticamente il Database con l'orario di logout.

**Descrivi eventuali alternative a cui avevi pensato per risolvere il problema.**
Sto pensando...

**Contenuto addizionale - Codice da inserire in Index.php**

$user_time = 'ora_entrata';
$current_time = time();
$logout_after = 1*60;

if(($user_time+$logout_after) < $current_time) {
    gdrcd_query("UPDATE personaggio SET ora_uscita = NOW() WHERE nome='" . gdrcd_filter('in', $_SESSION['login']) . "'");
} else { }

Da inserire appena sotto la connessione al Database.

**Comment by Kasui92** [comment]
Ciao @hydantonio ! 

Riesci a creare una Pull Request con la modifica così come l'hai proposta?
In questo modo possiamo fare la review direttamente sulla PR. nel caso, tagga la PR anche qui. 

Ti ringrazio per l'iniziativa e scusa per il terribile ritardo nella risposta.
