### ISSUE TITLE
Problema salva chat

### ISSUE THREAD

**Issue by Eriannen** [GDRCD/GDRCD#37]
hp provato a salvare la chat ha aperto il popup ma nel file savato ho trovato una miriade di righe tutte ripetendo lo stesso messaggio ogni due righe.

Warning: feof() expects parameter 1 to be resource, boolean given in /*****/chat_save.proc.php on line 414

Warning: fread() expects parameter 1 to be resource, boolean given in /*****/chat_save.proc.php on line 416

**Comment by BreakerYouko** [comment]
Il problema persiste?

**Comment by breakeryouko** [comment]
chiudo per inattività.
