### ISSUE TITLE
Problemi di encoding

### ISSUE THREAD

**Issue by ste-camp** [GDRCD/GDRCD#42]
A quanto pare da qualche parte del progetto ci sono problemi di encoding, perchè il carattere § per le frasi dei master non viene riconosciuto.

Ho controllato il file che sono inclusi quando si apre una chat ma sono tutti i utf-8...viene anche inviato l'header corretto per specificare al browser la codifica....

**Comment by breakeryouko** [comment]
chiudo per inattività.
