### ISSUE TITLE
Gestione gilde

### ISSUE THREAD

**Issue by Eriannen** [GDRCD/GDRCD#43]
Ho notato una inconcruenza nella gestione delle gilde. nell'amministrazione delle gilde se ho un personaggio con i permessi di capogilda, logicamente mi appare la gestione della gilda in 
main.php?page=servizi_adm_gilde
ma se lo stesso personaggio è per esempio un novizio in'altra gilda ( visto che ogni pg può essere in massimo 2 gilde). oltre a gestire la sua gilda da master gli appare quella dove è novizio, e questo non è normale, perchè chiunque col permesso di capogilda, in questo caso può gestire le gilde anche se non è admin.

**Comment by breakeryouko** [comment]
chiudo per inattività.
