### ISSUE TITLE
Anagrafe

### ISSUE THREAD

**Issue by cindy1979** [GDRCD/GDRCD#52]
chiedo se sia possibile, modificare l'attuale anagrafe invece che a tendina come e attualmente a sistema alfabetico, cè una patch si gdr-online fatta per il vecchio 5.0/5.1, ma essendo stati fatti cambiamenti nell'accesso al database nel nuovo 5.2 essa non funziona piu.

**Comment by corocoropollon** [comment]
e come si fa a mettere l'avatar oltre al nome nell'anagrafe?
