### ISSUE TITLE
Messaggi ad aderenti a gilde

### ISSUE THREAD

**Issue by Shantix** [GDRCD/GDRCD#57]
Buongiorno a tutti :-)
Quando provo ad inserire come destinatario di un messaggio privato il nome di una gilda, mi compare il seguente errore: 

GDRCD MySQLi Error [File: messages_center.inc.php; Line: 84]
Error Code: 1064
Error String: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ´´ at line 1

Error Detail: INSERT INTO messaggi (mittente, destinatario, spedito, testo) VALUE

Questa è la parte di codice interessata:
```php
<?php 
if (empty($_SESSION[´gilda´])===FALSE)
{
$gilde=explode(´,´, $_SESSION[´gilda´]);
foreach ($gilde as $getname)
{
if ((is_numeric($getname)===TRUE) && ($getname>-1))
{
$row_getname=gdrcd_query("SELECT nome FROM gilda WHERE id_gilda=".$getname."");
?>
```

Purtroppo in questo forum non visualizza correttamente la parte di codice con l'option, a cui tolgo <>:
```php
option value="<?php echo $getname; ?>">
<?php echo gdrcd_filter(´out´,$row_getname[´nome´]); ?> 
/option
<?php }
}
}
?>
```
Sapreste dirmi come fare perchè un qualsiasi utente possa inviare un messaggio ad una intera gilda conoscendone l'id?
Grazie in anticipo

**Comment by BreakerYouko** [comment]
Questa possibilità è stata rimossa in quanto la funzione message type "all" è stata rimossa nella versione 5.2
Dalla versione 5.3 rimuoverò i vari riferimenti che sono rimasti.
