### ISSUE TITLE
Prepared Statements

### ISSUE THREAD

**Issue by ste-camp** [GDRCD/GDRCD#65]
Ho scoperto un problemuccio nell'implementazione dei prepared statements per l'engine scritto da  @blancks (mentre scrivevo la stessa cosa per GDRCD6 XD)
La funzione get_result() usata per ottenere i risultati degli statement non è disponibile in tutte le versioni di php/mysql. è una funzione inclusa solo se si usa il driver nativo di mysql (mysqlnd), ma questo driver non è quello usato di default da molte distribuzioni di linux. Quindi quella chiamata risulta semplicemente in un: Fatal Error funzione non trovata.

Bisognerebbe passare a usare la (ben più scomoda) bind_results

**Comment by breakeryouko** [comment]
chiudo per inattività.
