### ISSUE TITLE
Visibilità bacheche

### ISSUE THREAD

**Issue by LenaLondon** [GDRCD/GDRCD#68]
Esiste una patch sul sito gdr-online che permette di visualizzare solo le bacheche a cui si  ha accesso. Solo che quando provo ad adattarla con il codice presente qui non riesco a farla funzionare. Sono sicura che sia un problema stupido che non riesco a capire perché non so di programmazione, sono solo una smanettona che ci prova (magari non tengo conto di qualche apice o qualche parentesi).
Se qualcuno potesse indicarmi come fare, quale parte del codice implementare... magari non sono l'unica a cui interesserebbe questa funzione.
Grazie!

**Comment by breakeryouko** [comment]
chiudo essendo una vecchia richiesta
