### ISSUE TITLE
Errore durante un cambio nome

### ISSUE THREAD

**Issue by cindy1979** [GDRCD/GDRCD#70]
oggi mentre tentavo di cambiare un nome a un PG mi e apparso questo errore, premetto che ho il pg gestore, ma lo stesso e successo ad un altro gestore

GDRCD MySQLi Error [File: user_cambio_nome.inc.php; Line: 101]
Error Code: 1054
Error String: Unknown column 'permessi' in 'where clause'

Error Detail: UPDATE log SET nome_interessato = 'Laura' WHERE nome_interessato = 'Lauradolce' AND permessi < 4 

Soluzioni??

**Comment by BreakerYouko** [comment]
Risolto nella versione 5.3
