### ISSUE TITLE
Problema Cancellazione PG

### ISSUE THREAD

**Issue by cindy1979** [GDRCD/GDRCD#71]
mi e stato fatto presente da un nuovo player iscritto, si e ritrovato nella casella di posta del proprio nuovo pg iscritto, una moltitudine di messaggi appartenenti al precedente player che aveva lo stesso pg cancellato, sarebbe da implementare nella nuova versione del gdrcd quando avviene la cancellazione di un pg, in automatico vengano cancellati tutti i messaggi log, ecc. ecc. relativi ad esso

**Comment by BreakerYouko** [comment]
Il problema è che non esiste una funzione cancella pg su gdrcd, esiste una funzione del tipo "cestino" quindi invece di cancellarlo lo disabilita.
Tu come lo hai cancellato?

**Comment by cindy1979** [comment]
quando usi la funzione cancella account e poi in gestione, manutenzione,  Elimina i personaggi provvisoriamente cancellati, Non sarà più possibile ripristinarli.
dopo aver dato l'ok premendo invia, cancella solo l'account ma non cancella i messaggi che il player non aveva preventivamente cancellato prima di farsi cancellare

**Comment by BreakerYouko** [comment]
Risolto per la versione 5.4

**Comment by BreakerYouko** [comment]
Una rapida soluzione attuabile in poco tempo è la creazione di foreign Key, tra le tabelle del database.
