### ISSUE TITLE
Modifiche da effetuare in user_cambio_nome.inc.php

### ISSUE THREAD

**Issue by cindy1979** [GDRCD/GDRCD#73]
Righe da sostituire nel file user_cambio_nome.inc.php
righe dalla numero 88 alla righa numero 97 compresa

gdrcd_query("UPDATE log SET nome_interessato = '".gdrcd_filter('in',$_POST['new_name'])."' WHERE nome_interessato = '".gdrcd_filter('in',$_POST['account'])."'");
		     gdrcd_query("UPDATE log SET autore = '".gdrcd_filter('in',$_POST['new_name'])."' WHERE autore = '".gdrcd_filter('in',$_POST['account'])."'");
             gdrcd_query("UPDATE messaggi SET mittente = '".gdrcd_filter('in',$_POST['new_name'])."' WHERE mittente = '".gdrcd_filter('in',$_POST['account'])."'");
		     gdrcd_query("UPDATE messaggi SET destinatario = '".gdrcd_filter('in',$_POST['new_name'])."' WHERE destinatario = '".gdrcd_filter('in',$_POST['account'])."'");
             gdrcd_query("UPDATE backmessaggi SET mittente = '".gdrcd_filter('in',$_POST['new_name'])."' WHERE mittente = '".gdrcd_filter('in',$_POST['account'])."'");
		     gdrcd_query("UPDATE backmessaggi SET destinatario = '".gdrcd_filter('in',$_POST['new_name'])."' WHERE destinatario = '".gdrcd_filter('in',$_POST['account'])."'");
		     gdrcd_query("UPDATE clgpersonaggioabilita SET nome = '".gdrcd_filter('in',$_POST['new_name'])."' WHERE nome = '".gdrcd_filter('in',$_POST['account'])."'");
   		     gdrcd_query("UPDATE clgpersonaggiomostrine SET nome = '".gdrcd_filter('in',$_POST['new_name'])."' WHERE nome = '".gdrcd_filter('in',$_POST['account'])."'");
		     gdrcd_query("UPDATE clgpersonaggiooggetto SET nome = '".gdrcd_filter('in',$_POST['new_name'])."' WHERE nome = '".gdrcd_filter('in',$_POST['account'])."'");
   		     gdrcd_query("UPDATE clgpersonaggioruolo SET personaggio = '".gdrcd_filter('in',$_POST['new_name'])."' WHERE personaggio = '".gdrcd_filter('in',$_POST['account'])."'");

**Comment by BreakerYouko** [comment]
Modifiche inserite nella versione 5.3
