### ISSUE TITLE
parentesi graffe di php nell'output di forum.inc.php

### ISSUE THREAD

**Issue by Dyrr** [GDRCD/GDRCD#78]
Correggendo il bug del forum.inc.php probabilmente sono rimaste delle parentesi } fuori dai tag di php.

Visualizzando i forum infatti in cima alla paigna mi mostra : "} } } }"

Sicuramente ce n'è una a riga 627, la prima che mi è saltata all'occhio se faccio a tempo e le trovo vi indico anche le altre.

Mi correggo, basta togliere quella per far sparire anche le altre, non mi ero accorto che era dentro ad un ciclo per cui era la stessa ripetuta.

**Comment by Dyrr** [comment]
La nuova versione da errore:

Parse error: syntax error, unexpected '}' in forum.inc.php on line 654

Probabilmente quando è stato corretto il primo problema del forum ovvero l'if fuori dai tag

sotto ci fosse anche la } fuori dai tag.

E' stato corretto il problema dell'if, con la rispettiva } di chiusura, quindi è rimasta quella } fuori dai tag che è proprio in più visto come la segna errore se la si riporta dentro i tag di php come nel fix indicato sopra.

Spero non mi odierete troppo per le varie segnalazioni, dove posso cerco di dare la segnalazione assieme anche alla correizone

**Comment by ste-camp** [comment]
awww....e io che mi ero pure messo a contare le parentesi...ho pure sbagliato a contare XD

**Comment by BreakerYouko** [comment]
Ho formattato il codice per facilitare la lettura del codice, ma non ho trovato le parentesi fuori >.>

**Comment by Dyrr** [comment]
sono quelle che hai spostato dentro i tag phph qui:

https://github.com/GDRCD/GDRCD/commit/f0b48bb581fbe1f3f5f2f6f4029abf766bb592c3

infatti dopo quella modifica da di nuovo errore di parse

**Comment by BreakerYouko** [comment]
Ho risolto l'errore.
