### ISSUE TITLE
Ordine errato dei require in required.php

### ISSUE THREAD

**Issue by Dyrr** [GDRCD/GDRCD#80]
require_once(__DIR__.'/../config.inc.php');
	require_once(__DIR__.'/constant_values.inc.php');
	require_once(__DIR__.'/../vocabulary/'.$PARAMETERS['languages']['set'].'.vocabulary.php');
 	require_once(__DIR__.'/functions.inc.php');

il config viene richiesto prima del constant.php quindi tutti gli if tipo

if ($_SESSION['permessi'] >= MODERATOR) {

all'interno di quel file saltano.
Da cambiare l'ordine in:
	
require_once(__DIR__.'/constant_values.inc.php');
	require_once(__DIR__.'/../config.inc.php');
	require_once(__DIR__.'/../vocabulary/'.$PARAMETERS['languages']['set'].'.vocabulary.php');
 	require_once(__DIR__.'/functions.inc.php');

**Comment by BreakerYouko** [comment]
ottima osservazione.
Grazie per l'aiuto
