### ISSUE TITLE
Gestore di richieste

### ISSUE THREAD

**Issue by breakeryouko** [GDRCD/GDRCD#85]
trovo abbastanza poco pratico (annulla per esempio tutti i vantaggi di avere pagine caricate solo quando servono nelle finestre di dialog) il fatto che ad ogni link o form nel frame centrale venga ricaricata tutta la pagina.

Usando un paio di js, uno per i link, e uno per i form (ne esistono gia di pronti) e appunto un gestore di link sarebbe interessante far caricare solo il frame centrale (non volendosi avventurare in ajax se si vuole mantenere semplice la modifica dell´os si può usare un iframe centrale che tanto è gia utilizzato per la chat e altre cose e non è nemmeno deprecato visto che è presente come tag in html 5)

**Comment by ste-camp** [comment]
Ma veramente questo sarebbe un passo indietro. Il layout di GDRCD3 era fatto così e suoi problemi erano evidenti.
C'è una ragione se si usano poco gli iframe e si usa più js nel web moderno: perchè gli iframe sono difficili da gestire sia da un punto di vista di stile (i css della pagina esterna non sono in grado di interagire con gli elementi interni all'iframe e vice versa) che di funzionalità (è sempre un bel casino richiamare cose da dentro a fuori all'iframe e viceversa. Senza contare che tipo tutti i js andrebbero inclusi due volte perchè appunto l'iframe è isolato...)
Insomma...di solito quando si interagisce con un iframe, il codice lato client viene sempre un gran pasticcio. E dato che il futuro del web prevede sempre più js, io non andrei a usare un elemento che complica l'uso del codice javascript.

Si può pensare a fare tutto con richieste ajax, ma va fatto molto bene, in particolare la gestione degli errori ajax.

**Comment by BreakerYouko** [comment]
Sinceramente non mi ricordo chi l'aveva proposto su gdr-online all'epoca, ma leggendolo ora mi pare uno spreco inutile di risorse umane, bisognerebbe sviluppare tutto in ajax. Anzi sarebbe interessante sviluppare una land tramite angularjs, credo sia uno dei codici più adatti per un'applicazione tipo i pbc

**Comment by Dyrr** [comment]
In realtà avevo proposto io la cosa ma in altri termini, avevo proposto ambo le alternative sia ajax che gli iframe, considerando la seconda opzione pensando al target medio degli utilizzatori del gdrcd, che non so quanto saprebbero gestire la cosa.
