### ISSUE TITLE
Separare html dal php

### ISSUE THREAD

**Issue by breakeryouko** [GDRCD/GDRCD#86]
Man mano che vengono sistemate la pagine separare di più html da codice php.
basterebbe salvare i vari pezzi dell´output generato da php in un array associativo multidimensionale e far lavorare solo su quello quando si lavora sull´output perchè su alcune pagine (esempio le bacheche) nonostante i commenti al codice sono proprio incasinate.

**Comment by BreakerYouko** [comment]
Stavo valutando di riscrivere tutto il codice secondo il modello MVC, ma richiede molto tempo e probabilmente cambierebbe tutto l'approccio al pacchetto stesso.

**Comment by ste-camp** [comment]
Beh si potrebbe usare un framework già esistente, che ci dia basi solide e sistemi robusti su cui costruire un gdr. Sarebbe bello, ma come progetto nuovo (un po' come doveva essere GDRCD6 o RoleSource), semplicemente non sarebbe più GDRCD

**Comment by BreakerYouko** [comment]
Infatti, per questo credo che il ciclo di GDRCD per come è stato inteso finora è arrivato alla fine.
Un framework darebbe stabilità e metterebbe a disposizione le funzioni più usate. Il problema sarebbe poi infarinare tutti su come funziona il tutto. Diciamo che bene o male per quanto è scritto male GDRCD chiunque potrebbe modificarlo e le pretese a livello di codice per una land è meno dello standard minimo richiesto.

**Comment by Dyrr** [comment]
gia separare completamente html e php sarebbe una bella cosa perchè permetterebbe di aggiornare più facilmente alle land la versione o le varie pagine senza dover ogni volta la parte in html

**Comment by Dyrr** [comment]
Parliamo della parte template html, e delle varie opzioni possibili.

A suo tempo avevo parlato della cosa con blanks cercando di sentire anche la sua opinione sul trovare un sistema di template, semplice ed intuitivo visto anche il target del gdrcd tra le varie opzioni quella che era risultata più appetibile quella che avevo suggerito io, ovvero un semplice altro file dove usare le funzioni base di php, come if, for ecc sulla sola variabile contenente i dati prodotti dalla pagina con il codice.

Cosa ne pensate di questa soluzione anche in vista del target del gdrcd?
ci sono altre idee su come farlo ecc?

**Comment by BreakerYouko** [comment]
La soluzione più elegante a mio avviso sarebbe usare un template engine che gestisca le view. Sfruttare poi un sistema di controller per passare variabili attraverso la view.

**Comment by Dyrr** [comment]
Una volta che hai la pagina del codice che genera un array con i dati, puoi farci di tutto con una minima modifica.

Vuoi trasformare l'array in un xml, pe rusare l'estensione nativa di php di xls per usare xslt per generare l'output thml,

Vuoi usare un engine di template come smarty o altro per farlo

Il discorso non era legato all'eleganza, ma al rapporto praticità/facilità della cosa per permettere al target medio di usufruitori del gdrcd di lavorare sui template senza dover imparare preticamente un linguaggio nuovo come molti dei template hanno.

Prendi il caso di xml + xsl. Sebbene sia gestito tutto d auna classe nativa di php e sia un engine molto potente a livello di possibilità dubito che l'utente medio dell'os possa saper gestire un template in xsl, intendevo dire questo

**Comment by BreakerYouko** [comment]
Quindi la tua idea sarebbe quella di far passare un array (anche il formato json andrebbe bene a questo punto) con tutti i dati e poi dal, a pagina di output viene manipolata solo questa array?

**Comment by Dyrr** [comment]
L'idea di base si sarebbe far generare o in formato json, o in un array multidimensionale tutti i dati che andranno a riempire la pagina e poi chi lavora sul template lavora solo con le istruzioni base di php (alla fine più di qualche if per far visualizzare o meno le parti del template o un for per ciclare un elenco o delle righe di una tabella allo sviluppatore del template non servirebbero).

In questo modo si potrebbe anche alleggerire di parecchio il vocabolario, perchè non dovendo praticamente quasi più intervenire sulla parte di codice dei dati e rischiando di fare casino quindi, per il vocabolario basterebbero i campi con alcuni dati più ripetuti tipo che ne so la valuta, tutto il resto potrevve essere modificato nel trmplate.

**Comment by BreakerYouko** [comment]
La mia idea invece era quella di creare un sistema di view parziali, che vengono poi assemblate o richiamate a seconda delle necessità.  Essendo gran parte della grafica uguale per tutte le pagine si avrebbe un codice più pulito in questo modo

**Comment by Dyrr** [comment]
Una volta pulito la parte del codice dall'html, e creata una funzione generica per il richiamo del template, alla fine 8o nei punti in cui va generato l'html) tipo 

call_template($url_template,$dati_template);

diventa semplicemente sostituendo il contenuto di quella funzione ognuno può scegliere quello che vuole come modalità per fondere dati e template, lasciare quello di default se è l'utente inesperto come scegliersi l'engine di template che vuole aumentando la modularità e flessibilità dell'os. un poò come per il parser del bbcode che uno ha la possibilità di scegliersi tra quello base del gdrcd o quello di blanks, o se sostituisce uno suo a quello di blanks basta che ne crei uno che abbia la fonzione di parsering con lo stesso nome e il codice la sfrutta

**Comment by BreakerYouko** [comment]
Il mio approccio era leggermente diverso. Al fine di semplificare il tutto pensavo di prendere spunto dalla gestione dei template di Joomla!  In pratica ogni view diventava un blocco e tramite un pannello si possono caricare in varie posizioni del template con la possibilità di ordinarli. Semplificando al massimo potrei dirti di pensare al template come ad una scacchiera dove l'utente può decidere dove caricare i blocchi.

**Comment by ste-camp** [comment]
Io preferirei una gestione come quella proposta da Dyrr. La gestione stile Joomla/Drupal è carina, ma mi pare eccessiva

**Comment by BreakerYouko** [comment]
La mia idea sarebbe quella di dare un prodotto usabile anche da chi non conosce nulla di programmazione.  In questo modo potrebbe installare i moduli e metterli dove vuole senza dover imparare qualcosa di php

**Comment by Dyrr** [comment]
L'installazione dei moduli non è complessissima al momento una volta che si arriva ad avere un template, chi deve installare il modulo semplicemente usa la funzione di gdrcd gdrcd_load_modules() nel punto dove vuole inserirla del template.

Si potrebbe eventualmente migliorare la funzione o inserirne una nuova che sfrutti la prima perchè l'utente invece di inserire il path e nome completo del file inserisce solo il nome del modulo, per evitare errori di inserimento del path un po' come fa gia il gdrcd quando prende il nome della pagina dalla variabile $_GET['page'].

mettere in un template un:
<?php gdrcd_new_mod('new_meteo'); ?>

che includa da solo il file pages/new_meteo.inc.php;

esempio dovrebbe essere abbastanza intuitivo se lo si scrive in una documentazione  ben fatta

**Comment by BreakerYouko** [comment]
La mia idea era creare una pagina predefinita con i vari load _ module ('nome - posizione') poi tramite un pannello il gestore decidere per ogni modulo in che posizione caricarlo e un numero per l'ordine. Tipo: info location, posizione left ordinamento 1. Meteo, posizione left ordinamento 2. In pratica l'estensione del modello attuale sul config

**Comment by ste-camp** [comment]
Credo che stiamo parlando di due cose ben diverse. Dyrr sta pensando agli strumenti da dare agli sviluppatori, per creare temi. Breaker sta pensando invece a gestori che non sanno niente di codice e prendono pacchetti incollandoli alla cieca.

Le due cose non si escludono a vicenda. Può esserci un sistema con delle API fatte per bene per dividere grafica e codice, e allo stesso tempo supportare la gestione a blocchi dal browser.

**Comment by BreakerYouko** [comment]
La mia idea infatti prevede un modello MVC e quindi include di per se quanto proposto da dyrr, volevo solo esporre poi la mia idea di risultato finale. Ovvero invece di usare un file config, si crea un pannello di controllo da dove si può gestire il tutto.

**Comment by ste-camp** [comment]
Eh si ok. Ma è fattibile questo modello mvc per GDRCD? Perchè se dobbiamo rifare tutto per attuarlo non ne vale la pena (piuttosto si fa un progetto nuovo strutturato finalmente in modo decente) e conviene attuare qualcosa di più semplice per GDRCD

**Comment by BreakerYouko** [comment]
Infatti tutto questo discorso è in visione di un nuovo os. Da parte mia oltre a piccole implementazione è inutile fare un lavoro del genere su GDRCD, conviene piuttosto sviluppare un codice da zero (tempo libero permettendo xD).

**Comment by Dyrr** [comment]
Sul fatto che piuttosto che fare grossissime modifiche al gdrcd 5 convenga passare al sei concordo anche io, in questi giorni stavo provando  per fare pratica su alcune cose a ristrutturare alcune parti del codice giungendo sempre alla conclusione che si faceva prima a riscriverlo

**Comment by corocoropollon** [comment]
Oddio si, sarebbe decisamente più comodo!
