### ISSUE TITLE
Errori vari in js

### ISSUE THREAD

**Issue by Dyrr** [GDRCD/GDRCD#87]
corefunctions.js:
riga 41:
`var obj = $(id);`

da correggere in:
`var obj = gdrcd_selector(id);`

tooltip.js
righe 14-15
`gdrcd_selector('descriptionLoc').style.left=(parseInt(curX)-parseInt($('maincontent').offsetLeft)+tooltip_offsetX)+'px';
gdrcd_selector('descriptionLoc').style.top=(parseInt(curY)-parseInt($('maincontent').offsetTop)+tooltip_offsetY)+'px';`

da correggere in
`gdrcd_selector('descriptionLoc').style.left=(parseInt(curX)-parseInt(gdrcd_selector('maincontent').offsetLeft)+tooltip_offsetX)+'px';
gdrcd_selector('descriptionLoc').style.top=(parseInt(curY)-parseInt(gdrcd_selector('maincontent').offsetTop)+tooltip_offsetY)+'px';`

Qui ho un dubbio righe 9-10
`curX = (document.all)? event.clientX + document.body.scrollLeft : e.pageX;`
`curY = (document.all)? event.clientY + document.body.scrollTop : e.pageY;`

non dovrebbe essere:
`curX = (document.all)? e.clientX + document.body.scrollLeft : e.pageX;`
`curY = (document.all)? e.clientY + document.body.scrollTop : e.pageY;`

**Comment by BreakerYouko** [comment]
Io non vedo gli errori da te segnalati

**Comment by ste-camp** [comment]
Gli errori descritti da Dyrr sono presenti. Basta navigare il repository da qui su GitHub per vederli, sia nel branch master che nel 5.4

Sono tutti errori tranne l'ultimo:
l'ultimo non è un errore perchè è un fix per InternetExplorer. Quel browser pazzo inserisce le informazioni sugli eventi nella variabile "event" in automatico. Nel senso che ogni callback di un evento ha proprio la variabile "event" hard-coded, non importa se tu la chiami "ev" o "e", lui, silenzioso e letale, instanzierà sempre una variabile chiamata event. (non so se nelle versioni più recenti di IE è ancora così o meno.)

**Comment by BreakerYouko** [comment]
Avete ragione, per qualche ragione non li vedevo. Vedrò di correggerli il prima possibile.
Grazie per la segnalazione
