### ISSUE TITLE
Nomi Colorati per Sesso

### ISSUE THREAD

**Issue by corocoropollon** [GDRCD/GDRCD#88]
E' possibile poter aggiungere una parte di codice selezionabile (a scelta) per poter mettere nella lista dei presenti e presenti estesi i nomi colorati al posto dell'icona del sesso?

**Comment by BreakerYouko** [comment]
In linea teorica si, in linea pratica è più semplice copiare il codice della chat nelle pagine in cui ti serve.
Vedrò di fare una modifica per farla diventare una function stile gdrcd_chatme()

**Comment by Dyrr** [comment]
In teoria è piu semplice anche del previsto.

Sia presenti che presenti estesi recuperano il sesso del pg per l'icona del sesso basta semplicemente nel punto dove viene stampato il nome e cognome del pg in quelle due pagine

e precisamente righe 147-150 dei presenti_estes.inc.phpi:
```
	//Nome pg e link alla sua scheda
	  echo ' <a href="main.php?page=scheda&pg='.$record['nome'].'" class="link_sheet">'.gdrcd_filter('out',$record['nome']);
	  if (empty($record['cognome'])===FALSE){echo ' '.gdrcd_filter('out',$record['cognome']);}
      echo '</a> ';
```

e righe 177 - 180 di presenti.inc.php
```
	  //Nome pg e link alla sua scheda
	  echo ' <a href="../main.php?page=scheda&pg='.$record['nome'].'" class="link_sheet" target="_top">'.gdrcd_filter('out',$record['nome']);
	  if (empty($record['cognome'])===FALSE AND 0){echo ' '.gdrcd_filter('out',$record['cognome']);}
      echo '</a> ';
```

andare a lavorare dove viene assegnata la classe del link:
```
class="link_sheet" 
```
trasformandola in:
```
class="link_sheet colore_<?php echo gdrcd_filter_out($record['sesso']); ?>" 
```

in questo modo diventerà:
```
class="link_sheet colore_m"
```
e
```
 class="link_sheet colore_f"
```

Senza toccare nulla dal codice poi chi vuole potrà lasciare quelle due classi vuote nel file del css o stilarsele con stili diversi se le vuole diverse per sesso.

**Comment by BreakerYouko** [comment]
La mia idea era per poter riutilizzare il codice poi in altre parti e nel caso poi si decidesse di cambiare i colori avrebbe effetto da tutte le parti, ma come suggerisci tu è la via più semplice per ottenere il risultato voluto

**Comment by Dyrr** [comment]
Stavo pensando all'idea della funzione però mi sorgevano un paio di dubbi prima di esporli faccio prima a chiederti come avevi intenzione di impostarla prima di esporti i dubbi che ho al riguardo

**Comment by BreakerYouko** [comment]
Non l'ho ancora impostata in quanto sto cercando un modo per non dover fare una query per ogni pg

**Comment by Dyrr** [comment]
Era proprio  lo stesso dubbio che avevo anche io riguardo alla funzione. quella di non fare una query per ogni pg

**Comment by BreakerYouko** [comment]
l'unica alternativa che mi viene in mente è creare un'array globale dove sono salvati tutti i pg ed il loro sesso.

**Comment by ste-camp** [comment]
Un array globale io lo eviterei. Userei piuttosto una cache statica all'interno della funzione e permetterei di specificare o meno il nome e il sesso del pg. Così se chi usa la funzione ha già in possesso l'informazione del sesso la può passare alla funzione che l'andrà a mettere in html; altrimenti farà una query per recuperarla.

```php
function renderPgName($user, $sesso = null, $force_reload = false){
  static $cache=array();

  $lower_user=strtolower($user);
  if(!isset($cache[$lower_user]) || $force_reload){
    if(empty($sesso)){
      $info = gdrcd_query("SELECT sesso FROM personaggio WHERE Nome='".gdrcd_filter('in',$user)."'");
      $sesso = $info['sesso'];
    }
    $cache[$lower_user]='<span class="pg_'.$sesso.'">'.gdrcd_filter('out',$user).'</span>';
  }

  return $cache[$lower_user];
}
```

Eventualmente si può estendere per includere il cognome, etc

**Comment by Dyrr** [comment]
mmmm ma se lo scopo della funzione è ottenere il blocco riutilizzabile:
```
<span class="pg_'.$sesso.'">'.gdrcd_filter('out',$user).'</span>
```
perchè sia sempre riutilizzabile, e visto che la funzione andrà prativamente sempre riutilizzata in un punto dove si è gia recuperato il sesso del pg (chat, presenti, credo anche forum ma non ne sono sicuro) non è più semplice passare il sesso come parametro?

del tipo:
```
function($dati,$sesso)
{

    return '<span class="pg_'.$sesso.'">'.gdrcd_filter_out($dati).'</span>';

}
```

Due righe di funzione, nessuna query, possibilità di passare che parametro si come dati: solo nome, nome e cognome completo ecc.

**Comment by ste-camp** [comment]
Infatti il sesso l'ho fatto passare come parametro. Semplicemente mi sono riservato anche una scorciatoia nel caso che non ho già il sesso nella pagina.

Con tutte le aggiunte e le toppe che vengono messe in gdrcd da gestori vari, può essere utile avere una funzione che fa la query nel caso che i dati non li hai. Se li hai glieli passi e via, la query non viene fatta.

**Comment by Dyrr** [comment]
Me ne sono accorto dopo aver fatto il post della cosa :-(
Devo smetterla di guardare e commentare il codice non mio a mezzanotte passata, prendo ogni volta fischi per fiaschi XD

**Comment by ste-camp** [comment]
XD

**Comment by BreakerYouko** [comment]
Stavo pensando alla creazione di una pagina cache che viene cancellata ogni volta che qualcuno logga o cambia locazione per risparmiare risorse

**Comment by BreakerYouko** [comment]
Mi è venuto in mente che sarebbe possibile mettere di default un class css per i nomi in base al sesso. Tipo <span class="gender_X"> dove al posto di X si mette m o f, usando qualcosa di simile ai nomi sing_m sing_f. Poi sarebbe da modificare tramite CSS il colore (uguale oppure diverso).
Che ne pensate?

**Comment by ste-camp** [comment]
È proprio questa la soluzione proposta sopra
