### ISSUE TITLE
errore nei messaggi

### ISSUE THREAD

**Issue by Eriannen** [GDRCD/GDRCD#89]
Ciao a tutti ho riscontrato un errore inviando un messaggio a qualsiasi PG. il messaggio arriva è leggibile si può cancellare, ma appare un errore subito sopra la tabella del form, che trascrivo sotto. Premetto che sto testando il codice 5.4 in locale con 
xampp v 3.2.1.

questo l'errore

GDRCD MySQLi Error [File: messages_center.inc.php; Line: 569]
Error Code: 1064
Error String: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE nome='Super'' at line 1

Error Detail: UPDATE personaggio SET ultimo_messaggio = WHERE nome='Super'

avte avuto riscontro?
saluti!

**Comment by BreakerYouko** [comment]
L'errore è dovuto ad un errore nella compilazione della sessione almeno da quello che posso vedere
Ricordati che la 5.4 non è stabile e molti file non sono completi (nel senso che ha alcuni funzioni sviluppate a metà).

**Comment by Eriannen** [comment]
Ah ok avevo letto versione stabile nelle info, la lascio un attimo in
standby allora e passo alla precedente
grazie

Il giorno 28 maggio 2015 15:17, BreakerYouko <notifications@github.com> ha
scritto:

> L'errore è dovuto ad un errore nella compilazione della sessione almeno da
> quello che posso vedere
> Ricordati che la 5.4 non è stabile e molti file non sono completi (nel
> senso che ha alcuni funzioni sviluppate a metà).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GDRCD/GDRCD/issues/89#issuecomment-106306365>.
>



-- 
Cordiali Saluti

Paolo Bevilacqua

via Aldo Moro 10
10060 - PISCINA  (TORINO - ITALY)
Mobile +39.338.925.4051
RISERVATEZZA DELLE INFORMAZIONI
Questo messaggio e i documenti allegati, se ve ne sono, sono indirizzati
esclusivamente ai destinatari da diritti professionali, la cui diffusione è
tutelata dalla legge. Pertanto chiunque riceva questo messaggio in
indirizzo e possono contenere informazioni riservate e protette e non
appaia tra gli indirizzi dei destinatari o non sia autorizzato a riceverlo,
è informato della riservatezza delle informazioni e del divieto di
utilizzo, di copia e di diffusione. Se questo messaggio è stato ricevuto
per errore, vi chiediamo di informarci con un'email o telefonando al numero
+39 3389254051, e di provvedere a distruggerlo immediatamente. La
trasmissione in Internet di messaggi via email, non garantisce la
riservatezza dei messaggi inviati, e neppure la sicura ricezione. Se i
destinatari in indirizzo non consentono l'uso di Internet per l'invio di
tali messaggi, sono pregati di comunicarlo all'indirizzo sopra menzionato.
Eventuali dati personali verranno trattati ai sensi e per gli effetti del
D.Lgs. 196/2003

**Comment by Dyrr** [comment]
Anche il message_center.inc.php del 5.3.2 presenta lo stesso errore.

Presenta lo stesso errore e altri errori, nel senso che se non si tocca niente del file, sia sulla versione che ho scaricato io nelle release, sia nella versione attuale del codice in master se si lancia il gdrcd e si va ai messaggi il primo errore che si trova è pagina vuota con messaggio di errore:
```
Parse error: syntax error, unexpected '}' in F:\webserver\applications\gdrcd532\pages\messages_center.inc.php on line 646
```
che è un errore di corrispondenza parentesi chissà dove.

Provando ad eliminare per prova la mancata corrispondenza di aperte chiuse parentesi eliminando quella finale, a parte che appunto sballa tutta la formattazione della pagina, da lo stesso messaggio di errore proprio alla stessa riga.

la cosa che genera l'errore è una cosa un po' strana o almeno a me sembra strana, ed è questa riga:
```
$_SESSION['last_istant_message']=$row['id'];
```

che in origine è a riga 562:
```
   <?php $_SESSION['last_istant_message']=$row['id'];


 	}//while
```
la cosa strana è appunto che se si prova stampare il row o nello specifico il $row['id'] in quel punto non restituisce nessun valore, mentre se si sposta quell'assegnazione subito dopo il fetch tipo a riga 467 qui;
```
   <?php while ($row=gdrcd_query($result, 'fetch')){
   
		 $_SESSION['last_istant_message']=$row['id'];
```
fa sparire l'errore perchè $row['id']; risulta contenere il valore che viene assegnato correttamente alla variabile di sesisone.

Ho controllato il codice dentro il ciclo while e non mi sembra ci sia nulla che svuoti l'array. se qualcuno capisce il perchè si svuota sarebbe interessante.

a parte mettersi a capire quale parentesi graffa originariamente è sballata e da correggere un paio di tag dove viene aperto div e chiuso span e viceversa

**Comment by Dyrr** [comment]
La pagina del messages_center.inc.php continua ad avere lo stesso errore di parentesi spaiate sia sul master dove è rimasta intoccata sia nel 5.4 dopo i recenti commit

**Comment by BreakerYouko** [comment]
Essendo il bug risolto chiudo.

**Comment by Dyrr** [comment]
No non hai capito, nel 5.4 è risolto nel 5.3 no. avendolo corretto tu nel 5.4 non so se ti basti sostituire il file o se ha delle modifiche che nel 5.3 non lo farebbero funzionare

**Comment by BreakerYouko** [comment]
Basta sostituire il file

**Comment by ste-camp** [comment]
Comunque non penso che faremo una release corretta del GDRCD5.3.
Puntiamo a fare qualcosa di pulito per il 5.4

**Comment by BreakerYouko** [comment]
La 5.3 è così com'è. Per la struttura di GDRCD 5.x stessa è impossibile correggere quindi l'unica cosa fattibile è chiudere una release dandole un nome e poi partire per la prossima e sperare che l'utenza scarichi l'ultima disponibile e nel mentre aggiorni manualmente la sua seguendo i commit.
La speranza di @ste-camp è utopistica, credo che GDRCD 5.x sia arrivato al suo limite ora come ora non ha senso stravolgerlo per renderlo più pulito, quello che possiamo fare è risolvere i bug e fare piccole correzioni/implementazioni.
Qualsiasi altro discorso va fatto in ottica GDRCD 6 oppure OS nuovo.

**Comment by ste-camp** [comment]
Stavo solo dicendo che non volevo fare una release nuova del 5.3 in realtà XD
