### ISSUE TITLE
Gilda e Lavoro in chat

### ISSUE THREAD

**Issue by corocoropollon** [GDRCD/GDRCD#92]
Nel gdrcd 5.3 inserendo il pacchetto per visualizzare il simbolo di gilda in chat succede che compare anche quello del lavoro. Come si può evitare che compaia nella chat se non si vuole? Ho notato che nella tabella il valore cambia da gilda a lavoro...lo riconosce sempre come un valore di gilda ma per le gilde effettive tutti i valori sono dall'1 in su mentre per i lavori sono dal -1 in giù. Ho pensato che nel ref_header potevo inserire una stringa che dicesse di visualizzare solo i valori che risultano superiori a 0 di conseguenza si eviterebbe la visualizzazione di quelli che sono al di sotto e di conseguenza non dovrebbero vedersi i lavori ma solo le gilde. Ho pensato male? Però all'atto pratico non mi trovo a scrivere la stringa sarebbe comodo se tutto sto marasma di problema non si ponesse se gilde e lavori fossero ben distinti all'interno del database come non avviene avendo in comune il valore "ruolo" <.< che è presente in entrabe...io non so perchè siano stati legati così assieme...è scomodo....

**Comment by ste-camp** [comment]
Questo è un issue tracker, è usato per segnalare bug e suggerire miglioramenti. Non per porre domande.
Come scritto nella Wiki del progetto, le domande sull'utilizzo del pacchetto potete farle su gdr-online o sul forum di gdrcd
