### ISSUE TITLE
Prenotazione Stanze

### ISSUE THREAD

**Issue by cindy1979** [GDRCD/GDRCD#93]
Ho una domanda che da diverso tempo i player della land di cui faccio parte come gestore mi assillano, in pratica mi hanno chiesto di rendere disponibili delle stanze invece che a ore a settimana, io pensavo di mettere delle stanze a giorni con il limite di 7 giorni massimi, come succedeva nel vecchio Extreme, solo non ho capito come cambiare il sistema di conteggio da ore a giorno, o eventualmente avere sia l'uno che l'altro

**Comment by BreakerYouko** [comment]
In pratica vuoi modificare il conteggio da ore a giorni?

**Comment by cindy1979** [comment]
si ma volevo che le due cose fossero inttegrate, che ci siano sia le stanze prenotabili ad ore sia le eventuali stanze prenotabili a giorni

**Comment by BreakerYouko** [comment]
Per semplificare il tutto potresti mettere un nuovo campo chiamato "giorni" poi lato codice fai quel numero x24

**Comment by breakeryouko** [comment]
chiudo per inattività.
