### ISSUE TITLE
BUG Usa oggetti in chat

### ISSUE THREAD

**Issue by Shesleepwalker** [GDRCD/GDRCD#99]
Se ho un oggetto con numero di usi limitato e lo uso in chat tramite l´apposita funzionalità, terminate le cariche a disposizione l´oggetto sparisce dalla scheda, e fin qui tutto ok. 
Il problema nasce quando ho una certa quantità di oggetti uguali con un limitato numero di usi, per cui quando ne utilizzo uno in chat terminando tutte le cariche, dalla scheda non mi sparisce il solo oggetto utilizzato ma tutta la quantità, come se non tenesse minimamente conto del numero di oggetti posseduti. E´ uno scioglilingua, spero di essere stata chiara.

**Comment by BreakerYouko** [comment]
La risposta è già stata data su gdr-online.com
Ti basta aggiungere un cariche = 1 alla query di DELETE

**Comment by Shesleepwalker** [comment]
Si, ho segnalato anche qui perchè quella soluzione ahimè non risolve il problema.

**Comment by Dyrr** [comment]
Modificare la query in quel modo non serve a nulla in quanto il gdrcd per come è strutturato gestisce gli oggetti uguali non come record differenti nel database ma come multipli dello stesso oggetto.

Il campo numero nella tabella clgpersonaggiooggetto indica quanti oggetti del tipo x ha un pg.

Il bug segnalato è ancora più grosso di quanto segnalato, in quanto se io ho due oggetti X con 10 cariche e ne uso uno in chat, essendo salvati come unico record toglie una carica da entrambi gli oggetti e non da uno solo.

Bisognerebbe modificare la tabella clgpersonaggiooggetto nella sua struttura per permettere entrate multiple dello stesso oggetto se hanno cariche in maniera da distinguere i vari oggetti (attualmente la chiave primaria impedisce la cosa essendo un controllo sul campio nome e id_oggetto).
e assieme a questo modificare come gli oggetti sono inseriti in quella tabella quando comprati o assegnati.

Non è un lavoro da poco perchè bisogna toccare diversi file ma andrebbe fatto.

**Comment by gianni10049** [comment]
Ho creato una patch per questo, serve estrapolarlo e collegarlo al tuo gdr.

Ora quando arriva a 1 carica se hai un altro oggetto allora ricarica le cariche e mette l'altro oggetto, altirmenti lo elimina.

Non e' una soluzione a tutti i problemi degli oggetti, a livello logico, ma e' una patch specifica per questo problema.

Commit: f925a6e16024b43130280268781a7bdf01e5e149
